import {
  estimateProfile,
  recommendNext,
  type Cefr,
  type MistakeSignal,
  type Recommendation,
  type Skill,
  type SkillEvidence,
} from '@lingonest/core';
import { supabase } from './supabase';
import { query } from './api';

/**
 * Reads everything Home needs in one place.
 *
 * The ranking itself is done by `recommendNext` in @lingonest/core rather than
 * here, so the "why this?" the learner sees is generated by tested logic and
 * not by whatever the screen felt like showing.
 */

export interface HomeSnapshot {
  readonly languageCode: string;
  readonly languageName: string;
  readonly levels: Partial<Record<Skill | 'overall', Cefr | null>>;
  readonly streak: { current: number; longest: number; lastActiveDate: string | null };
  readonly goal: { targetMinutes: number; minutesDone: number; met: boolean };
  readonly dueVocabularyCount: number;
  readonly leechCount: number;
  readonly recommendations: readonly Recommendation[];
  readonly nextBooking: {
    id: string;
    startsAt: string;
    teacherName: string;
    durationMinutes: number;
  } | null;
  readonly assignments: readonly {
    id: string;
    title: string;
    kind: string;
    teacherName: string;
    targetRef: string | null;
  }[];
}

export async function fetchHomeSnapshot(userId: string, languageCode: string) {
  return query<HomeSnapshot>(async () => {
    const today = new Date().toISOString().slice(0, 10);

    const { data: language } = await supabase
      .from('languages')
      .select('id, name')
      .eq('code', languageCode)
      .maybeSingle();

    if (!language) return { data: null, error: { message: 'language not found' } };

    const [
      { data: skills },
      { data: evidence },
      { data: streak },
      { data: goal },
      { data: dueVocab },
      { data: leeches },
      { data: mistakes },
      { data: bookings },
      { data: assignments },
      { data: progress },
    ] = await Promise.all([
      supabase
        .from('skill_profiles')
        .select('id, overall_level, reading_level, writing_level, listening_level, speaking_level, vocabulary_level, grammar_level, pronunciation_level, interaction_level, mediation_level')
        .eq('user_id', userId)
        .eq('language_id', language.id)
        .maybeSingle(),
      supabase
        .from('skill_evidence')
        .select('skill, cefr, score, source, weight, created_at, skill_profiles!inner(user_id, language_id)')
        .eq('skill_profiles.user_id', userId)
        .eq('skill_profiles.language_id', language.id)
        .order('created_at', { ascending: false })
        .limit(200),
      supabase.from('streaks').select('current, longest, last_active_date').eq('user_id', userId).maybeSingle(),
      supabase
        .from('daily_goals')
        .select('target_minutes, minutes_done, met')
        .eq('user_id', userId)
        .eq('local_date', today)
        .maybeSingle(),
      supabase
        .from('user_vocabulary')
        .select('id', { count: 'exact', head: true })
        .eq('user_id', userId)
        .lte('due_at', new Date().toISOString()),
      supabase
        .from('user_vocabulary')
        .select('id', { count: 'exact', head: true })
        .eq('user_id', userId)
        .eq('state', 'leech'),
      supabase
        .from('user_mistakes')
        .select('tag, label, skill, count, last_seen_at, target_kind, target_id')
        .eq('user_id', userId)
        .eq('language_id', language.id)
        .is('resolved_at', null)
        .order('count', { ascending: false })
        .limit(10),
      supabase
        .from('bookings')
        .select('id, starts_at, duration_minutes, teacher_id, profiles!bookings_teacher_id_fkey(display_name)')
        .eq('learner_id', userId)
        .eq('status', 'confirmed')
        .gte('starts_at', new Date().toISOString())
        .order('starts_at', { ascending: true })
        .limit(1),
      supabase
        .from('booking_assignments')
        .select('id, title, kind, target_ref, teacher_id, profiles!booking_assignments_teacher_id_fkey(display_name)')
        .eq('learner_id', userId)
        .eq('status', 'assigned')
        .limit(5),
      supabase
        .from('user_progress')
        .select('lesson_id, status, updated_at, lessons(id, title, objective, estimated_minutes)')
        .eq('user_id', userId)
        .order('updated_at', { ascending: false })
        .limit(20),
    ]);

    // Rebuild the profile from evidence so the estimate the learner sees comes
    // from the same tested code as everything else.
    const evidenceRows: SkillEvidence[] = (evidence ?? []).map((row) => ({
      skill: row.skill as Skill,
      cefr: row.cefr as Cefr,
      score: Number(row.score),
      source: row.source as SkillEvidence['source'],
      weight: Number(row.weight),
      at: new Date(row.created_at).getTime(),
    }));
    const estimated = estimateProfile(evidenceRows);

    const levels: Partial<Record<Skill | 'overall', Cefr | null>> = {
      overall: (skills?.overall_level as Cefr | null) ?? estimated.overall,
      reading: (skills?.reading_level as Cefr | null) ?? estimated.bySkill.reading.level,
      writing: (skills?.writing_level as Cefr | null) ?? estimated.bySkill.writing.level,
      listening: (skills?.listening_level as Cefr | null) ?? estimated.bySkill.listening.level,
      speaking: (skills?.speaking_level as Cefr | null) ?? estimated.bySkill.speaking.level,
      vocabulary: (skills?.vocabulary_level as Cefr | null) ?? estimated.bySkill.vocabulary.level,
      grammar: (skills?.grammar_level as Cefr | null) ?? estimated.bySkill.grammar.level,
      pronunciation: (skills?.pronunciation_level as Cefr | null) ?? estimated.bySkill.pronunciation.level,
      interaction: (skills?.interaction_level as Cefr | null) ?? estimated.bySkill.interaction.level,
      mediation: (skills?.mediation_level as Cefr | null) ?? estimated.bySkill.mediation.level,
    };

    const inProgressRow = (progress ?? []).find((row) => row.status === 'in_progress');
    const nextRow = (progress ?? []).find((row) => row.status === 'not_started');

    const lessonOf = (row: typeof inProgressRow) => {
      const lesson = row?.lessons as unknown as
        | { id: string; title: string; objective: string; estimated_minutes: number }
        | undefined;
      return lesson
        ? { id: lesson.id, title: lesson.title, objective: lesson.objective, minutes: lesson.estimated_minutes }
        : undefined;
    };

    const mistakeSignals: MistakeSignal[] = (mistakes ?? []).map((row) => ({
      tag: row.tag,
      label: row.label,
      skill: row.skill as Skill,
      count: row.count,
      lastSeenAt: new Date(row.last_seen_at).getTime(),
      target: row.target_kind
        ? { kind: row.target_kind as never, id: row.target_id ?? undefined }
        : undefined,
    }));

    const lastActive = streak?.last_active_date ?? null;
    const daysSince = lastActive
      ? Math.round((Date.now() - new Date(lastActive).getTime()) / 86_400_000)
      : 99;

    const targetMinutes = goal?.target_minutes ?? 15;
    const minutesDone = goal?.minutes_done ?? 0;

    const recommendations = recommendNext({
      profile: estimated,
      mistakes: mistakeSignals,
      dueVocabularyCount: dueVocab?.length ?? 0,
      leechCount: leeches?.length ?? 0,
      inProgressLesson: lessonOf(inProgressRow),
      nextLesson: lessonOf(nextRow),
      daysSinceLastPractice: daysSince,
      minutesRemainingToday: Math.max(0, targetMinutes - minutesDone),
      cefr: (levels.overall ?? 'A1') as Cefr,
      teacherAssignments: (assignments ?? []).map((a) => ({
        id: a.id,
        kind: a.kind as never,
        targetId: a.target_ref ?? undefined,
        title: a.title,
        teacherName: (a.profiles as unknown as { display_name?: string })?.display_name ?? '',
      })),
    });

    const booking = bookings?.[0];

    return {
      data: {
        languageCode,
        languageName: language.name,
        levels,
        streak: {
          current: streak?.current ?? 0,
          longest: streak?.longest ?? 0,
          lastActiveDate: lastActive,
        },
        goal: { targetMinutes, minutesDone, met: goal?.met ?? false },
        dueVocabularyCount: dueVocab?.length ?? 0,
        leechCount: leeches?.length ?? 0,
        recommendations,
        nextBooking: booking
          ? {
              id: booking.id,
              startsAt: booking.starts_at,
              durationMinutes: booking.duration_minutes,
              teacherName:
                (booking.profiles as unknown as { display_name?: string })?.display_name ?? '',
            }
          : null,
        assignments: (assignments ?? []).map((a) => ({
          id: a.id,
          title: a.title,
          kind: a.kind,
          targetRef: a.target_ref,
          teacherName: (a.profiles as unknown as { display_name?: string })?.display_name ?? '',
        })),
      },
      error: null,
    };
  });
}
