import {
  buildSentence,
  categorize,
  converse,
  correctGrammar,
  dialogueCompletion,
  dictation,
  fillBlank,
  imageMatch,
  lesson,
  listen,
  mcq,
  multiAnswer,
  realWorldTask,
  reviewChallenge,
  speak,
  speakResponse,
  storyCompletion,
  tapTranslation,
  timedChallenge,
  translate,
  unit,
  wordMatch,
  write,
} from '../../dsl/builders';

/** Spanish A1, units 6-10: travel, home, work and school, time, and the level checkpoint. */

export const ES_A1_UNIT_6 = unit({
  slug: 'es-a1-u6',
  title: 'Getting Around',
  objective: 'Ask for and follow directions, and talk about transport.',
  theme: 'travel',
  cefr: 'A1',
  realWorldTask: 'Stop someone in the street, ask for a place, and follow the directions you are given.',
  lessons: [
    lesson({
      slug: 'es-a1-u6-l1',
      title: 'Where Is It?',
      objective: 'Ask where something is.',
      canDo: 'I can ask where a place is.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['donde-esta', 'estacion', 'cerca', 'lejos'],
      grammar: ['es-ser-estar'],
      activities: [
        mcq({
          question: 'Why is it "¿dónde está la estación?" and not "¿dónde es?"',
          options: ['Location takes estar', 'Estar is only for people', 'Both are equally common'],
          answer: 'Location takes estar',
          why: 'Ser is identity; estar is location and state. Where something is takes estar.',
          tags: ['grammar:es-ser-estar'],
        }),
        buildSentence({
          target: '¿Dónde está la estación?',
          tokens: ['la', '¿Dónde', 'estación?', 'está'],
          instruction: 'Ask where the station is.',
          why: 'Question word, verb, then the thing you are looking for.',
          tags: ['vocab:donde-esta'],
        }),
        wordMatch({
          instruction: 'Match each word.',
          pairs: [
            ['cerca', 'near'],
            ['lejos', 'far'],
            ['la estación', 'the station'],
          ],
          tags: ['vocab:cerca', 'vocab:lejos'],
        }),
        fillBlank({
          template: 'El hotel {{blank}} muy cerca.',
          answers: ['está'],
          wordBank: ['está', 'es', 'tiene'],
          why: 'Location is estar, even when it feels permanent.',
          tags: ['grammar:es-ser-estar'],
        }),
        speak({ target: '¿Dónde está la estación?', focusPhonemes: ['d'] }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u6-l2',
      title: 'Left, Right, Straight On',
      objective: 'Understand directions given to you.',
      canDo: 'I can follow simple spoken directions.',
      cefr: 'A1',
      minutes: 9,
      vocabulary: ['izquierda', 'derecha', 'recto'],
      culture: ['es-regional-vocabulary'],
      activities: [
        listen({
          audio: 'es/a1/u6/directions',
          instruction: 'Listen to the directions.',
          question: 'Which way do you turn after going straight?',
          options: ['Left', 'Right', 'Back'],
          answer: 'Left',
          transcript: '— Perdón, ¿dónde está la estación? — Todo recto y luego a la izquierda. Está muy cerca.',
          speed: 'slow',
          why: '"A la izquierda" — to the left.',
        }),
        wordMatch({
          instruction: 'Match each direction.',
          pairs: [
            ['a la izquierda', 'to the left'],
            ['a la derecha', 'to the right'],
            ['todo recto', 'straight ahead'],
          ],
          tags: ['vocab:izquierda', 'vocab:derecha', 'vocab:recto'],
        }),
        mcq({
          question: 'In Mexico, what would you more likely hear for "straight ahead"?',
          options: ['derecho', 'todo recto', 'a la derecha'],
          answer: 'derecho',
          why: 'Spain says "todo recto"; Mexico says "derecho". Confusingly, "a la derecha" is "to the right" everywhere.',
          tags: ['vocab:recto'],
        }),
        dialogueCompletion({
          lines: [
            { speaker: 'You', text: 'Perdón, ¿dónde está el mercado?' },
            { speaker: 'Local', text: '___' },
          ],
          options: ['Todo recto y a la derecha.', 'Me llamo Ana.', 'Son cinco euros.'],
          answer: 'Todo recto y a la derecha.',
          why: 'Directions answer a "where" question.',
        }),
        speak({ target: 'Todo recto y a la izquierda', focusPhonemes: ['rr'] }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u6-l3',
      title: 'Transport',
      objective: 'Talk about how you travel.',
      canDo: 'I can say how I get somewhere.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['coche', 'autobus', 'billete', 'aeropuerto'],
      culture: ['es-regional-vocabulary'],
      activities: [
        imageMatch({
          instruction: 'Which picture is "el autobús"?',
          word: 'el autobús',
          options: [
            { text: 'bus', image: 'es/img/autobus' },
            { text: 'car', image: 'es/img/coche' },
            { text: 'house', image: 'es/img/casa' },
          ],
          answer: 'bus',
          tags: ['vocab:autobus'],
        }),
        mcq({
          question: 'You are in Mexico City. How do you ask for a bus ticket?',
          options: ['un boleto de camión', 'un billete de autobús', 'un billete de coche'],
          answer: 'un boleto de camión',
          why: 'Mexico uses boleto and camión; Spain uses billete and autobús. Both are understood.',
          tags: ['vocab:billete', 'vocab:autobus'],
        }),
        translate({
          source: 'I go to work by bus.',
          answer: 'Voy al trabajo en autobús.',
          alternatives: ['Voy al trabajo en camión', 'Voy en autobús al trabajo'],
          why: 'Transport takes "en": en autobús, en coche, en tren. Walking is the exception: a pie.',
          tags: ['vocab:autobus'],
        }),
        multiAnswer({
          question: 'Which of these are places you travel through?',
          options: ['el aeropuerto', 'la estación', 'el desayuno', 'la fruta'],
          answers: ['el aeropuerto', 'la estación'],
          why: 'The other two are food.',
          tags: ['vocab:aeropuerto', 'vocab:estacion'],
        }),
        speak({ target: 'Un billete para Madrid, por favor' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u6-l4',
      title: 'Asking a Stranger',
      objective: 'Stop someone politely and ask for help.',
      canDo: 'I can politely stop someone and ask for directions.',
      cefr: 'A1',
      minutes: 9,
      activities: [
        mcq({
          question: 'How do you politely get a stranger\'s attention?',
          options: ['Perdón / Disculpe', '¡Oye!', 'Hola, ¿qué tal?'],
          answer: 'Perdón / Disculpe',
          why: '"Oye" is for friends; with a stranger it sounds rude. "Disculpe" is the formal option.',
          tags: ['vocab:perdon'],
        }),
        buildSentence({
          target: 'Perdón ¿dónde está el hotel?',
          tokens: ['el', 'Perdón', 'hotel?', '¿dónde', 'está'],
          instruction: 'Politely ask where the hotel is.',
          why: 'The apology-word opens, then the question.',
        }),
        converse({
          scenario: 'es-asking-directions',
          goals: ['Politely get their attention', 'Ask where the station is', 'Confirm you understood'],
          minTurns: 4,
        }),
        speakResponse({
          situation: 'A local gives you directions quickly and you did not catch them.',
          question: 'Todo recto, luego la segunda a la derecha, y está al lado del banco.',
          goal: 'Ask them to repeat more slowly',
          criteria: ['Asks for repetition politely', 'Uses a courtesy word'],
        }),
        realWorldTask({
          situation: 'You are lost and need to find the nearest station. Stop someone and get there.',
          goals: ['Get their attention politely', 'Ask for the station', 'Check you understood', 'Thank them'],
        }),
      ],
    }),

    lesson({
      slug: 'es-a1-u6-l5',
      title: 'Unit 6 Review',
      objective: 'Consolidate directions and travel.',
      canDo: 'I can find my way with Spanish alone.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      activities: [
        dictation({
          audio: 'es/a1/u6/directions',
          answer: 'Todo recto y luego a la izquierda',
          alternatives: ['todo recto y luego a la izquierda.'],
          instruction: 'Listen and write the directions.',
          speed: 'slow',
          why: 'Direction phrases are short and worth knowing by heart.',
        }),
        timedChallenge({
          instruction: 'Translate as many as you can.',
          items: [
            ['where is…?', '¿dónde está?'],
            ['to the left', 'a la izquierda'],
            ['to the right', 'a la derecha'],
            ['near', 'cerca'],
            ['far', 'lejos'],
            ['the airport', 'el aeropuerto'],
          ],
          seconds: 90,
        }),
        correctGrammar({
          incorrect: '¿Dónde es la estación?',
          correct: '¿Dónde está la estación?',
          why: 'Location always takes estar.',
          topic: 'es-ser-estar',
        }),
        write({
          task: 'Write directions from your home to the nearest shop, in three sentences.',
          goal: 'Give written directions',
          criteria: ['Uses at least two direction phrases', 'Uses estar for location'],
          minWords: 15,
        }),
        realWorldTask({
          situation: 'A Spanish-speaking visitor asks you how to get to the station from where you are.',
          goals: ['Give at least two directions', 'Say whether it is near or far'],
        }),
      ],
    }),
  ],
});

export const ES_A1_UNIT_7 = unit({
  slug: 'es-a1-u7',
  title: 'Home',
  objective: 'Describe where you live.',
  theme: 'home',
  cefr: 'A1',
  realWorldTask: 'Describe your home to a Spanish speaker in several sentences.',
  lessons: [
    lesson({
      slug: 'es-a1-u7-l1',
      title: 'Rooms',
      objective: 'Name the rooms of a home.',
      canDo: 'I can name the rooms in my home.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['habitacion', 'cocina', 'bano', 'casa'],
      activities: [
        imageMatch({
          instruction: 'Which picture is "la cocina"?',
          word: 'la cocina',
          options: [
            { text: 'kitchen', image: 'es/img/cocina' },
            { text: 'house', image: 'es/img/casa' },
            { text: 'table', image: 'es/img/mesa' },
          ],
          answer: 'kitchen',
          tags: ['vocab:cocina'],
        }),
        wordMatch({
          instruction: 'Match each room.',
          pairs: [
            ['la cocina', 'kitchen'],
            ['el baño', 'bathroom'],
            ['la habitación', 'bedroom'],
          ],
          tags: ['vocab:cocina', 'vocab:bano', 'vocab:habitacion'],
        }),
        mcq({
          question: 'In Mexico, what is another common word for "habitación"?',
          options: ['el cuarto', 'la cocina', 'la mesa'],
          answer: 'el cuarto',
          why: 'Both are used; "cuarto" is more common in Mexico for a bedroom.',
          tags: ['vocab:habitacion'],
        }),
        fillBlank({
          template: 'Mi casa tiene dos {{blank}} y un baño.',
          answers: ['habitaciones'],
          wordBank: ['habitaciones', 'habitación', 'cocinas'],
          why: 'The number "dos" requires the plural, and words ending in -ón add -es and drop the accent.',
          tags: ['grammar:es-articles-plural'],
        }),
        speak({ target: 'Mi casa tiene una cocina grande', focusPhonemes: ['ñ'] }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u7-l2',
      title: 'Furniture',
      objective: 'Name common objects in a home.',
      canDo: 'I can describe what is in a room.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['mesa', 'silla', 'ventana', 'puerta'],
      activities: [
        wordMatch({
          instruction: 'Match each object.',
          pairs: [
            ['la mesa', 'table'],
            ['la silla', 'chair'],
            ['la ventana', 'window'],
            ['la puerta', 'door'],
          ],
          tags: ['vocab:mesa', 'vocab:silla', 'vocab:ventana', 'vocab:puerta'],
        }),
        buildSentence({
          target: 'En la cocina hay una mesa',
          tokens: ['una', 'En', 'hay', 'la', 'mesa', 'cocina'],
          instruction: 'Say there is a table in the kitchen.',
          why: '"Hay" means "there is / there are" and never changes form.',
          tags: ['vocab:mesa'],
        }),
        mcq({
          question: 'Which is correct: "there are two chairs"?',
          options: ['Hay dos sillas.', 'Hayn dos sillas.', 'Son dos sillas.'],
          answer: 'Hay dos sillas.',
          why: '"Hay" is invariable — it is the same for singular and plural.',
        }),
        categorize({
          instruction: 'Sort each item by where it usually is.',
          categories: ['cocina', 'habitación'],
          mapping: { 'la mesa': 'cocina', 'la silla': 'cocina', 'la ventana': 'habitación' },
          why: 'A rough sort — the point is recalling the words, not interior design.',
        }),
        speak({ target: 'Hay una ventana grande en la habitación' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u7-l3',
      title: 'Describing Your Home',
      objective: 'Put rooms and objects into a description.',
      canDo: 'I can describe my home in several sentences.',
      cefr: 'A1',
      minutes: 9,
      activities: [
        listen({
          audio: 'es/a1/u7/home',
          instruction: 'Listen to the description.',
          question: 'How many bedrooms does the apartment have?',
          options: ['Two', 'One', 'Three'],
          answer: 'Two',
          transcript: 'Vivo en un apartamento pequeño. Tiene dos habitaciones, una cocina y un baño.',
          speed: 'slow',
          why: '"Dos habitaciones" — two bedrooms.',
        }),
        storyCompletion({
          story: '{{blank}} en un apartamento pequeño. {{blank}} dos habitaciones y una {{blank}}.',
          answers: ['Vivo', 'Tiene', 'cocina'],
          wordBank: ['Vivo', 'Tiene', 'cocina', 'Soy', 'mesa'],
          why: 'Vivir for where you live, tener for what the place has.',
        }),
        translate({
          source: 'My house has three rooms and a big kitchen.',
          answer: 'Mi casa tiene tres habitaciones y una cocina grande.',
          alternatives: ['Mi casa tiene tres cuartos y una cocina grande'],
          why: 'In Spanish the adjective usually follows the noun: cocina grande.',
        }),
        speakResponse({
          situation: 'A friend asks about your place.',
          question: '¿Cómo es tu casa?',
          goal: 'Describe your home in at least three sentences',
          criteria: ['Names at least two rooms', 'Uses tener or hay', 'Uses one adjective'],
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u7-l4',
      title: 'Where I Live',
      objective: 'Say where your home is and what is nearby.',
      canDo: 'I can say where I live and what is near me.',
      cefr: 'A1',
      minutes: 8,
      activities: [
        fillBlank({
          template: 'Vivo en Chicago, pero mi familia {{blank}} en México.',
          answers: ['vive'],
          wordBank: ['vive', 'vivo', 'viven'],
          why: '"Mi familia" is grammatically singular in Spanish, so the verb is vive.',
          tags: ['grammar:es-present-er-ir'],
        }),
        correctGrammar({
          incorrect: 'Mi casa es cerca del mercado.',
          correct: 'Mi casa está cerca del mercado.',
          why: 'Location takes estar, not ser.',
          topic: 'es-ser-estar',
        }),
        buildSentence({
          target: 'Mi casa está cerca de la estación',
          tokens: ['la', 'Mi', 'está', 'estación', 'casa', 'cerca', 'de'],
          instruction: 'Say your house is near the station.',
          why: '"Cerca de" needs the "de" before the place.',
          tags: ['grammar:es-ser-estar'],
        }),
        tapTranslation({
          source: 'Vivo lejos del centro.',
          options: ['I live far from the centre.', 'I live in the centre.', 'I work in the centre.'],
          answer: 'I live far from the centre.',
          why: '"Del" is the contraction of de + el.',
          tags: ['vocab:lejos'],
        }),
        speak({ target: 'Vivo cerca del centro' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u7-l5',
      title: 'Unit 7 Review',
      objective: 'Describe a home fully.',
      canDo: 'I can describe where and how I live.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      activities: [
        timedChallenge({
          instruction: 'Translate as many as you can.',
          items: [
            ['the kitchen', 'la cocina'],
            ['the bathroom', 'el baño'],
            ['there is', 'hay'],
            ['the window', 'la ventana'],
            ['I live', 'vivo'],
            ['near', 'cerca'],
          ],
          seconds: 90,
        }),
        write({
          task: 'Describe your home in five sentences: where it is, how many rooms, and what is in one of them.',
          goal: 'Write a connected description of a home',
          criteria: ['Uses estar for location', 'Uses hay or tener', 'Names at least three rooms or objects'],
          minWords: 25,
        }),
        realWorldTask({
          situation: 'A Spanish-speaking friend is coming to stay and asks what your place is like.',
          goals: ['Say where you live', 'Describe the rooms', 'Say what is nearby'],
        }),
      ],
    }),
  ],
});

export const ES_A1_UNIT_8 = unit({
  slug: 'es-a1-u8',
  title: 'Work and School',
  objective: 'Say what you do and ask what others do.',
  theme: 'work',
  cefr: 'A1',
  realWorldTask: 'Tell a Spanish speaker what you do for work or study, and ask what they do.',
  lessons: [
    lesson({
      slug: 'es-a1-u8-l1',
      title: 'What Do You Do?',
      objective: 'Name professions and ask about someone\'s work.',
      canDo: 'I can say what I do and ask someone what they do.',
      cefr: 'A1',
      minutes: 9,
      vocabulary: ['trabajo', 'profesor', 'medico', 'ingeniero', 'estudiante'],
      grammar: ['es-ser-estar'],
      activities: [
        listen({
          audio: 'es/a1/u8/work',
          instruction: 'Listen to the conversation about work.',
          question: 'What does the speaker do?',
          options: ['Engineer', 'Teacher', 'Doctor'],
          answer: 'Engineer',
          transcript: '— ¿En qué trabajas? — Soy ingeniera. Trabajo en una oficina en el centro. — ¿Y estudias? — Sí, estudio inglés los martes.',
          speed: 'slow',
          why: '"Soy ingeniera" — the -a ending marks a woman engineer.',
        }),
        mcq({
          question: 'Which is correct: "I am a teacher"?',
          options: ['Soy profesor.', 'Soy un profesor.', 'Estoy profesor.'],
          answer: 'Soy profesor.',
          why: 'Spanish drops the article before an unmodified profession, and a profession is identity, so it takes ser.',
          tags: ['grammar:es-ser-estar'],
        }),
        correctGrammar({
          incorrect: 'Estoy médico.',
          correct: 'Soy médico.',
          why: 'A profession is part of who you are, so it takes ser.',
          topic: 'es-ser-estar',
        }),
        wordMatch({
          instruction: 'Match each profession.',
          pairs: [
            ['el profesor', 'teacher'],
            ['el médico', 'doctor'],
            ['el ingeniero', 'engineer'],
            ['el estudiante', 'student'],
          ],
          tags: ['vocab:profesor', 'vocab:medico', 'vocab:ingeniero'],
        }),
        speakResponse({
          situation: 'Someone at a party asks what you do.',
          question: '¿En qué trabajas?',
          goal: 'Say what you do and ask them back',
          criteria: ['Uses ser with a profession or describes what they do', 'Returns the question'],
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u8-l2',
      title: 'At Work',
      objective: 'Describe where and when you work.',
      canDo: 'I can say where I work and what my day is like.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['oficina', 'trabajar'],
      activities: [
        fillBlank({
          template: '{{blank}} en una oficina en el centro.',
          answers: ['Trabajo'],
          wordBank: ['Trabajo', 'Trabajas', 'Trabajar'],
          why: 'First person of an -ar verb ends in -o.',
          tags: ['grammar:es-present-ar'],
        }),
        buildSentence({
          target: 'Trabajo de lunes a viernes',
          tokens: ['viernes', 'Trabajo', 'a', 'lunes', 'de'],
          instruction: 'Say you work Monday to Friday.',
          why: '"De… a…" expresses a range.',
        }),
        translate({
          source: 'I work in an office in the centre.',
          answer: 'Trabajo en una oficina en el centro.',
          alternatives: ['Trabajo en una oficina del centro'],
          why: '"En" marks the place; the article is needed before oficina.',
          tags: ['vocab:oficina'],
        }),
        multiAnswer({
          question: 'Which sentences describe work?',
          options: ['Trabajo en una oficina.', 'Soy ingeniero.', 'Me gusta el café.', 'Estudio inglés.'],
          answers: ['Trabajo en una oficina.', 'Soy ingeniero.'],
          why: 'The other two are about preference and study.',
        }),
        speak({ target: 'Trabajo en una oficina en el centro' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u8-l3',
      title: 'Studying',
      objective: 'Talk about what and where you study.',
      canDo: 'I can say what I study and where.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['universidad', 'clase', 'estudiar'],
      activities: [
        tapTranslation({
          source: 'Estudio en la universidad.',
          options: ['I study at the university.', 'I work at the university.', 'I live at the university.'],
          answer: 'I study at the university.',
          why: 'Estudiar is a regular -ar verb.',
          tags: ['vocab:universidad'],
        }),
        fillBlank({
          template: 'Mi clase de español {{blank}} los martes.',
          answers: ['es'],
          wordBank: ['es', 'está', 'tiene'],
          why: 'An event happening at a time takes ser, even though it feels like location: "la clase es a las seis".',
          tags: ['grammar:es-ser-estar'],
        }),
        mcq({
          question: 'Why is it "la clase es a las seis" but "la clase está en el aula 3"?',
          options: [
            'Ser for when an event happens, estar for where a thing is',
            'They are interchangeable',
            'Estar is never used with clase',
          ],
          answer: 'Ser for when an event happens, estar for where a thing is',
          why: 'This is the one place ser is used for something that looks like location — it is about the event, not the object.',
          tags: ['grammar:es-ser-estar'],
        }),
        buildSentence({
          target: 'Estudio español en la universidad',
          tokens: ['universidad', 'Estudio', 'la', 'español', 'en'],
          instruction: 'Say you study Spanish at university.',
          why: 'Verb, what you study, then where.',
        }),
        speak({ target: 'Estudio español los martes y los jueves' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u8-l4',
      title: 'Talking About Your Day at Work',
      objective: 'Combine work, study and routine.',
      canDo: 'I can hold a short conversation about work and study.',
      cefr: 'A1',
      minutes: 9,
      activities: [
        dialogueCompletion({
          lines: [
            { speaker: 'Colega', text: '¿En qué trabajas?' },
            { speaker: 'You', text: '___' },
            { speaker: 'Colega', text: 'Qué interesante. ¿Y dónde?' },
          ],
          options: ['Soy ingeniero.', 'Tengo treinta años.', 'Me gusta el café.'],
          answer: 'Soy ingeniero.',
          why: 'Answer the question you were asked.',
        }),
        dictation({
          audio: 'es/a1/u8/work',
          answer: 'Trabajo en una oficina en el centro',
          alternatives: ['trabajo en una oficina en el centro.'],
          instruction: 'Listen and write the sentence about where they work.',
          speed: 'slow',
          why: 'Practising this sentence prepares you for the most common small-talk question there is.',
        }),
        speakResponse({
          situation: 'A Spanish-speaking colleague asks about your work and study.',
          question: '¿En qué trabajas y qué estudias?',
          goal: 'Answer both parts of the question',
          criteria: ['Says what they do', 'Says what they study', 'Uses ser and a regular verb correctly'],
        }),
        realWorldTask({
          situation: 'At a work event, someone asks what you do. Answer, and ask them the same.',
          goals: ['Say your profession', 'Say where you work', 'Ask what they do'],
        }),
      ],
    }),

    lesson({
      slug: 'es-a1-u8-l5',
      title: 'Unit 8 Review',
      objective: 'Consolidate work and study language.',
      canDo: 'I can talk about work and study confidently.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      activities: [
        timedChallenge({
          instruction: 'Translate as many as you can.',
          items: [
            ['I work', 'trabajo'],
            ['the office', 'la oficina'],
            ['I am a teacher', 'soy profesor'],
            ['the university', 'la universidad'],
            ['I study', 'estudio'],
            ['what do you do?', '¿en qué trabajas?'],
          ],
          seconds: 90,
        }),
        correctGrammar({
          incorrect: 'Soy un ingeniero.',
          correct: 'Soy ingeniero.',
          why: 'Spanish drops the article before a bare profession. It comes back if you add an adjective: "soy un ingeniero excelente".',
          topic: 'es-ser-estar',
        }),
        write({
          task: 'Write four sentences about your work or studies: what you do, where, when, and one thing you like about it.',
          goal: 'Describe work in writing',
          criteria: ['Uses ser for the profession', 'Uses a regular present-tense verb', 'Includes a time expression'],
          minWords: 25,
        }),
        realWorldTask({
          situation: 'You meet a Spanish-speaking professional contact and need two minutes of small talk.',
          goals: ['Introduce yourself', 'Say what you do', 'Ask what they do', 'React to their answer'],
        }),
      ],
    }),
  ],
});

export const ES_A1_UNIT_9 = unit({
  slug: 'es-a1-u9',
  title: 'Time and Dates',
  objective: 'Tell the time, name the days, and arrange when to meet.',
  theme: 'time',
  cefr: 'A1',
  realWorldTask: 'Agree a day and time to meet someone.',
  lessons: [
    lesson({
      slug: 'es-a1-u9-l1',
      title: 'What Time Is It?',
      objective: 'Tell and ask the time.',
      canDo: 'I can ask and tell the time.',
      cefr: 'A1',
      minutes: 9,
      vocabulary: ['que-hora-es', 'hora', 'minuto'],
      activities: [
        listen({
          audio: 'es/a1/u9/time',
          instruction: 'Listen to the exchange.',
          question: 'What time is it?',
          options: ['4:30', '4:00', '6:30'],
          answer: '4:30',
          transcript: '— ¿Qué hora es? — Son las cuatro y media. — ¿La clase es el lunes? — No, es el miércoles a las seis.',
          speed: 'slow',
          why: '"Las cuatro y media" — half past four.',
        }),
        mcq({
          question: 'Why "son las dos" but "es la una"?',
          options: [
            'One o\'clock is singular, every other hour is plural',
            'It is a regional difference',
            'Both forms are always correct',
          ],
          answer: 'One o\'clock is singular, every other hour is plural',
          why: 'The verb agrees with the number of hours: es la una, son las dos.',
          tags: ['vocab:que-hora-es'],
        }),
        fillBlank({
          template: '{{blank}} las siete y cuarto.',
          answers: ['Son'],
          wordBank: ['Son', 'Es', 'Está'],
          why: 'Seven is plural, so "son".',
          tags: ['vocab:que-hora-es'],
        }),
        wordMatch({
          instruction: 'Match each time expression.',
          pairs: [
            ['y media', 'half past'],
            ['y cuarto', 'quarter past'],
            ['menos cuarto', 'quarter to'],
          ],
        }),
        speak({ target: 'Son las cuatro y media' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u9-l2',
      title: 'Days of the Week',
      objective: 'Name the days and say when something happens.',
      canDo: 'I can say what day something happens.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo'],
      activities: [
        wordMatch({
          instruction: 'Match each day.',
          pairs: [
            ['lunes', 'Monday'],
            ['miércoles', 'Wednesday'],
            ['viernes', 'Friday'],
            ['domingo', 'Sunday'],
          ],
          tags: ['vocab:lunes', 'vocab:miercoles', 'vocab:viernes'],
        }),
        mcq({
          question: 'How do you say "on Mondays"?',
          options: ['los lunes', 'en lunes', 'el lunes'],
          answer: 'los lunes',
          why: '"Los lunes" is every Monday; "el lunes" is this coming Monday. No word for "on" is needed.',
          tags: ['vocab:lunes'],
        }),
        correctGrammar({
          incorrect: 'La clase es en miércoles.',
          correct: 'La clase es el miércoles.',
          why: 'Spanish uses the article, not a preposition, for days: el miércoles.',
          topic: 'es-articles-plural',
        }),
        categorize({
          instruction: 'Sort the days.',
          categories: ['entre semana', 'fin de semana'],
          mapping: { lunes: 'entre semana', jueves: 'entre semana', sábado: 'fin de semana', domingo: 'fin de semana' },
          why: '"Entre semana" is weekdays, "fin de semana" is the weekend.',
        }),
        speak({ target: 'La clase es el miércoles a las seis' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u9-l3',
      title: 'Making Plans',
      objective: 'Suggest a time and agree on it.',
      canDo: 'I can suggest a time to meet and agree on one.',
      cefr: 'A1',
      minutes: 9,
      activities: [
        buildSentence({
          target: '¿Nos vemos el viernes a las ocho?',
          tokens: ['ocho?', '¿Nos', 'el', 'las', 'vemos', 'a', 'viernes'],
          instruction: 'Suggest meeting on Friday at eight.',
          why: 'Day first, then the time with "a las".',
        }),
        dialogueCompletion({
          lines: [
            { speaker: 'Ana', text: '¿Nos vemos el jueves?' },
            { speaker: 'You', text: '___' },
          ],
          options: ['El jueves no puedo. ¿El viernes?', 'Son las cuatro.', 'Me llamo Ana.'],
          answer: 'El jueves no puedo. ¿El viernes?',
          why: 'Decline and offer an alternative — the most useful move in any scheduling conversation.',
        }),
        fillBlank({
          template: 'La reunión es {{blank}} las diez de la mañana.',
          answers: ['a'],
          wordBank: ['a', 'en', 'de'],
          why: 'A clock time takes "a las".',
        }),
        speakResponse({
          situation: 'A friend suggests meeting at a time you cannot do.',
          question: '¿Nos vemos el sábado a las siete?',
          goal: 'Decline politely and suggest another time',
          criteria: ['Declines politely', 'Suggests a specific alternative day or time'],
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u9-l4',
      title: 'Schedules',
      objective: 'Understand opening hours and timetables.',
      canDo: 'I can understand when something is open.',
      cefr: 'A1',
      minutes: 8,
      culture: ['es-meal-times', 'es-punctuality'],
      activities: [
        mcq({
          question: 'A shop sign says "Abierto de 10:00 a 14:00 y de 17:00 a 20:00". Why the gap?',
          options: [
            'Many shops close in the middle of the day',
            'The sign is wrong',
            'It is closed on weekends',
          ],
          answer: 'Many shops close in the middle of the day',
          why: 'A midday closure is common in Spain and parts of Latin America — worth planning around.',
          tags: ['culture:meal-times'],
        }),
        tapTranslation({
          source: 'Abierto de lunes a viernes',
          options: ['Open Monday to Friday', 'Closed on Fridays', 'Open every day'],
          answer: 'Open Monday to Friday',
          why: '"De… a…" gives a range of days as well as times.',
        }),
        mcq({
          question: 'A friend invites you to dinner "a las nueve". When do you arrive?',
          options: ['Around 9:15–9:30', 'At 8:45', 'At 10:30'],
          answer: 'Around 9:15–9:30',
          why: 'For a social invitation, slightly late is normal; exactly on time can be early. For a professional appointment, be punctual.',
          tags: ['culture:punctuality'],
        }),
        translate({
          source: 'The shop opens at nine in the morning.',
          answer: 'La tienda abre a las nueve de la mañana.',
          alternatives: ['La tienda abre a las 9 de la mañana'],
          why: '"De la mañana" specifies am, since Spanish often uses the 12-hour clock in speech.',
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u9-l5',
      title: 'Unit 9 Review',
      objective: 'Consolidate time and dates.',
      canDo: 'I can arrange a meeting in Spanish.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      activities: [
        dictation({
          audio: 'es/a1/u9/time',
          answer: 'Son las cuatro y media',
          alternatives: ['son las 4 y media'],
          instruction: 'Listen and write the time.',
          speed: 'slow',
          why: 'Times are said as a set phrase; writing them fixes the pattern.',
        }),
        timedChallenge({
          instruction: 'Translate as many as you can.',
          items: [
            ['what time is it?', '¿qué hora es?'],
            ['Monday', 'lunes'],
            ['Friday', 'viernes'],
            ['half past', 'y media'],
            ['at eight', 'a las ocho'],
            ['the weekend', 'el fin de semana'],
          ],
          seconds: 90,
        }),
        write({
          task: 'Write a short message suggesting a day and time to meet, and give a reason.',
          goal: 'Arrange a meeting in writing',
          criteria: ['Names a day', 'Gives a clock time', 'Uses a courtesy phrase'],
          minWords: 15,
        }),
        realWorldTask({
          situation: 'You want to arrange a language exchange with a Spanish speaker this week.',
          goals: ['Suggest a day and time', 'Respond when they cannot make it', 'Agree on an alternative'],
        }),
      ],
    }),
  ],
});

export const ES_A1_UNIT_10 = unit({
  slug: 'es-a1-u10',
  title: 'A1 Checkpoint',
  objective: 'Put the whole level together and check what has stuck.',
  theme: 'review',
  cefr: 'A1',
  realWorldTask: 'Handle a complete real-world interaction — checking into a hotel — in Spanish only.',
  lessons: [
    lesson({
      slug: 'es-a1-u10-l1',
      title: 'Everything About You',
      objective: 'Review personal information.',
      canDo: 'I can give a full account of who I am.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      activities: [
        timedChallenge({
          instruction: 'Translate as many as you can.',
          items: [
            ['my name is', 'me llamo'],
            ["I'm from", 'soy de'],
            ['I have two sisters', 'tengo dos hermanas'],
            ["I'm 30 years old", 'tengo treinta años'],
            ['I live in', 'vivo en'],
            ["I'm a teacher", 'soy profesor'],
          ],
          seconds: 100,
        }),
        storyCompletion({
          story:
            'Hola, me {{blank}} Carlos. {{blank}} de Perú pero {{blank}} en Chicago. {{blank}} treinta años y {{blank}} ingeniero.',
          answers: ['llamo', 'Soy', 'vivo', 'Tengo', 'soy'],
          wordBank: ['llamo', 'Soy', 'vivo', 'Tengo', 'soy', 'estoy'],
          why: 'Ser for identity and origin, vivir for where you live, tener for age.',
        }),
        correctGrammar({
          incorrect: 'Soy treinta años y estoy ingeniero.',
          correct: 'Tengo treinta años y soy ingeniero.',
          why: 'Two errors: age takes tener, and a profession takes ser.',
          topic: 'es-tener',
        }),
        write({
          task: 'Write a six-sentence introduction covering your name, origin, home, age, work and one thing you like.',
          goal: 'Produce a full personal introduction',
          criteria: ['Uses ser and tener correctly', 'Uses gustar correctly', 'At least six sentences'],
          minWords: 40,
        }),
        speakResponse({
          situation: 'You are introducing yourself to a new Spanish class.',
          question: 'Cuéntanos un poco sobre ti.',
          goal: 'Introduce yourself fully',
          criteria: ['Name', 'Origin', 'Work or study', 'One personal detail'],
        }),
      ],
    }),

    lesson({
      slug: 'es-a1-u10-l2',
      title: 'Everyday Transactions',
      objective: 'Review shopping, ordering and directions together.',
      canDo: 'I can handle everyday transactions in Spanish.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      vocabulary: ['hotel', 'hasta-luego', 'amigo'],
      activities: [
        listen({
          audio: 'es/a1/u10/review-dialogue',
          instruction: 'Listen to the hotel check-in.',
          question: 'How many nights is the room for?',
          options: ['Two', 'One', 'Three'],
          answer: 'Two',
          transcript: '— Hola, buenas tardes. Quisiera una habitación para dos noches. — ¿A nombre de quién? — De Ana Ruiz. — Muy bien. Son cien euros.',
          speed: 'normal',
          why: '"Para dos noches" — for two nights.',
        }),
        mcq({
          question: 'How much does the room cost?',
          options: ['€100', '€10', '€150'],
          answer: '€100',
          why: '"Cien euros" is one hundred euros.',
          tags: ['vocab:cien'],
        }),
        buildSentence({
          target: 'Quisiera una habitación para dos noches',
          tokens: ['noches', 'Quisiera', 'para', 'una', 'dos', 'habitación'],
          instruction: 'Ask for a room for two nights.',
          why: '"Para" marks the purpose or duration here.',
        }),
        converse({
          scenario: 'es-cafe-order',
          goals: ['Greet', 'Order', 'Ask the price', 'Close politely'],
          minTurns: 5,
        }),
        converse({
          scenario: 'es-asking-directions',
          goals: ['Get attention politely', 'Ask for a place', 'Confirm understanding'],
          minTurns: 4,
        }),
      ],
    }),

    lesson({
      slug: 'es-a1-u10-l3',
      title: 'Listening Review',
      objective: 'Understand A1 material at normal speed.',
      canDo: 'I can follow a simple conversation at natural speed.',
      cefr: 'A1',
      minutes: 9,
      isReview: true,
      activities: [
        listen({
          audio: 'es/a1/u2/family',
          instruction: 'Listen at normal speed.',
          question: 'How many siblings does the speaker have in total?',
          options: ['Three', 'Two', 'Four'],
          answer: 'Three',
          transcript: '— ¿Tienes hermanos? — Sí, tengo dos hermanas y un hermano. — ¿Cuántos años tienen? — Mi hermana mayor tiene treinta años.',
          speed: 'normal',
          why: 'Two sisters plus one brother.',
        }),
        listen({
          audio: 'es/a1/u3/daily-routine',
          instruction: 'Listen at normal speed.',
          question: 'When does the speaker study Spanish?',
          options: ['At night', 'In the morning', 'At lunchtime'],
          answer: 'At night',
          transcript: 'Me levanto a las siete. Trabajo en una oficina. Como a la una y estudio español por la noche.',
          speed: 'normal',
          why: '"Por la noche" — at night.',
        }),
        dictation({
          audio: 'es/a1/u4/cafe',
          answer: 'Quisiera un café con leche, por favor',
          alternatives: ['quisiera un cafe con leche por favor'],
          instruction: 'Listen and write the order.',
          speed: 'normal',
          why: 'Writing at normal speed is a genuine A1 listening milestone.',
        }),
        reviewChallenge({ instruction: 'Review the words you have found hardest.', source: 'recent_mistakes', count: 12 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u10-l4',
      title: 'Grammar Review',
      objective: 'Check the grammar that A1 depends on.',
      canDo: 'I can use ser, estar, tener and the present tense reliably.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      activities: [
        correctGrammar({
          incorrect: 'Yo soy 25 años.',
          correct: 'Tengo 25 años.',
          why: 'Age uses tener.',
          topic: 'es-tener',
        }),
        correctGrammar({
          incorrect: 'Estoy de México.',
          correct: 'Soy de México.',
          why: 'Origin uses ser.',
          topic: 'es-ser-estar',
        }),
        correctGrammar({
          incorrect: 'Mi casa es cerca del centro.',
          correct: 'Mi casa está cerca del centro.',
          why: 'Location uses estar.',
          topic: 'es-ser-estar',
        }),
        correctGrammar({
          incorrect: 'Yo gusto el café.',
          correct: 'Me gusta el café.',
          why: 'Gustar puts the thing liked in the subject position.',
          topic: 'es-gustar',
        }),
        correctGrammar({
          incorrect: 'Nosotros vivemos en Madrid.',
          correct: 'Nosotros vivimos en Madrid.',
          why: '-ir verbs take -imos in the nosotros form.',
          topic: 'es-present-er-ir',
        }),
        multiAnswer({
          question: 'Which sentences are correct?',
          options: [
            'Tengo hambre.',
            'Soy hambre.',
            'Me gustan las frutas.',
            'Me gusta las frutas.',
          ],
          answers: ['Tengo hambre.', 'Me gustan las frutas.'],
          why: 'Hunger is something you have; gustar agrees with the plural thing liked.',
        }),
        reviewChallenge({ instruction: 'Grammar points you have missed recently.', source: 'recent_mistakes', count: 10 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u10-l5',
      title: 'A1 Checkpoint',
      objective: 'A full assessment of the level across all six skills.',
      canDo: 'I can handle everyday A1 situations across reading, listening, speaking and writing.',
      cefr: 'A1',
      minutes: 20,
      isCheckpoint: true,
      activities: [
        listen({
          audio: 'es/a1/u10/review-dialogue',
          instruction: 'Listening: hotel check-in at normal speed.',
          question: 'Whose name is the booking under?',
          options: ['Ana Ruiz', 'María Ruiz', 'Ana Ríos'],
          answer: 'Ana Ruiz',
          transcript: '— Hola, buenas tardes. Quisiera una habitación para dos noches. — ¿A nombre de quién? — De Ana Ruiz. — Muy bien. Son cien euros.',
          speed: 'normal',
          why: 'Catching a name at speed is a real listening skill, not a trick.',
        }),
        storyCompletion({
          story:
            'Reading: Marta {{blank}} de Colombia. {{blank}} en Madrid desde hace dos años. {{blank}} en una oficina y estudia inglés {{blank}} las tardes.',
          answers: ['es', 'Vive', 'Trabaja', 'por'],
          wordBank: ['es', 'Vive', 'Trabaja', 'por', 'está', 'en'],
          why: 'Ser for origin, vivir and trabajar in the present, "por las tardes" for a repeated time.',
        }),
        timedChallenge({
          instruction: 'Vocabulary: translate as many as you can.',
          items: [
            ['the bill', 'la cuenta'],
            ['to the left', 'a la izquierda'],
            ['I would like', 'quisiera'],
            ['expensive', 'caro'],
            ['the kitchen', 'la cocina'],
            ['Wednesday', 'miércoles'],
            ['I have', 'tengo'],
            ['how much?', '¿cuánto?'],
          ],
          seconds: 120,
        }),
        correctGrammar({
          incorrect: 'Grammar: Mi hermano es veinte años y estoy profesor.',
          correct: 'Mi hermano tiene veinte años y soy profesor.',
          why: 'Age takes tener; a profession takes ser.',
          topic: 'es-tener',
        }),
        speakResponse({
          situation: 'Speaking: you are meeting your new Spanish tutor for the first time.',
          question: 'Hola, cuéntame sobre ti: ¿de dónde eres y qué haces?',
          goal: 'Introduce yourself fully and ask a question back',
          criteria: ['Name and origin', 'Work or study', 'Correct ser/tener', 'Asks a question in return'],
        }),
        write({
          task: 'Writing: write a short message to a Spanish-speaking host family introducing yourself and your plans for the week.',
          goal: 'Produce connected written text at A1',
          criteria: ['At least five sentences', 'Uses the present tense correctly', 'Includes a day and a time'],
          minWords: 45,
        }),
        realWorldTask({
          situation:
            'You arrive at a small hotel in Mexico. Check in for two nights, ask what time breakfast is, and ask where the nearest station is.',
          goals: [
            'Check in and give your name',
            'Ask what time breakfast is',
            'Ask for directions to the station',
            'Thank them and close',
          ],
          constraints: ['Spanish only'],
        }),
      ],
    }),
  ],
});
