import {
  buildSentence,
  categorize,
  converse,
  correctGrammar,
  dialogueCompletion,
  dictation,
  fillBlank,
  hints,
  imageMatch,
  lesson,
  listen,
  mcq,
  multiAnswer,
  realWorldTask,
  reviewChallenge,
  speak,
  speakResponse,
  storyCompletion,
  tapTranslation,
  timedChallenge,
  translate,
  unit,
  wordMatch,
  write,
} from '../../dsl/builders';

/** Spanish A1, units 1-5: introductions, family, daily life, food, shopping. */

export const ES_A1_UNIT_1 = unit({
  slug: 'es-a1-u1',
  title: 'Introductions',
  objective: 'Introduce yourself, ask someone their name, and say where you are from.',
  theme: 'greetings',
  cefr: 'A1',
  realWorldTask: 'Introduce yourself to a Spanish speaker and find out their name and where they are from.',
  lessons: [
    lesson({
      slug: 'es-a1-u1-l1',
      title: 'Saying Hello',
      objective: 'Greet someone and ask how they are.',
      canDo: 'I can greet someone and ask how they are.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['hola', 'como-estas', 'bien', 'mal', 'mas-o-menos'],
      culture: ['es-tu-usted'],
      activities: [
        listen({
          audio: 'es/a1/u1/how-are-you',
          instruction: 'Listen to the exchange.',
          question: 'How does the second speaker say they are?',
          options: ['Very well', 'Not well', 'So-so'],
          answer: 'Very well',
          transcript: '— ¿Cómo estás? — Muy bien, gracias. ¿Y tú? — Más o menos.',
          speed: 'slow',
          why: '"Muy bien" is "very well". "Más o menos" is the so-so answer that follows.',
        }),
        wordMatch({
          instruction: 'Match each answer to its meaning.',
          pairs: [
            ['bien', 'well'],
            ['mal', 'badly'],
            ['más o menos', 'so-so'],
          ],
          tags: ['vocab:bien', 'vocab:mal', 'vocab:mas-o-menos'],
        }),
        mcq({
          question: 'How do you ask a friend how they are?',
          options: ['¿Cómo estás?', '¿Cómo te llamas?', '¿De dónde eres?'],
          answer: '¿Cómo estás?',
          why: '"¿Cómo estás?" uses estar, because how you feel is a state rather than an identity.',
          tags: ['vocab:como-estas', 'grammar:es-ser-estar'],
        }),
        mcq({
          question: 'You are speaking to your friend\'s grandmother. Which is more appropriate?',
          options: ['¿Cómo está usted?', '¿Cómo estás?', '¿Qué tal, tío?'],
          answer: '¿Cómo está usted?',
          why: 'Usted is the respectful form for someone older or someone you have just met.',
          tags: ['grammar:register'],
        }),
        dialogueCompletion({
          lines: [
            { speaker: 'Ana', text: 'Hola, ¿cómo estás?' },
            { speaker: 'You', text: '___, gracias. ¿Y tú?' },
          ],
          options: ['Bien', 'Adiós', 'Por favor'],
          answer: 'Bien',
          why: 'Answer the question, then return it with "¿Y tú?".',
          tags: ['vocab:bien'],
        }),
        speak({ target: '¿Cómo estás?', phonetic: 'KOH-moh es-TAHS' }),
        speakResponse({
          situation: 'A classmate greets you at the start of a lesson.',
          question: '¿Hola! ¿Cómo estás?',
          goal: 'Greet them back and say how you are',
          criteria: ['Uses a greeting', 'Answers how they are', 'Returns the question'],
          hints: hints('Start with "hola".', 'Then say how you are: bien, mal, más o menos.'),
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u1-l2',
      title: 'Introducing Yourself',
      objective: 'Say your name and ask someone theirs.',
      canDo: 'I can introduce myself and ask what someone is called.',
      cefr: 'A1',
      minutes: 9,
      vocabulary: ['me-llamo', 'como-te-llamas', 'mucho-gusto', 'encantado'],
      grammar: ['es-questions'],
      activities: [
        listen({
          audio: 'es/a1/u1/introductions',
          instruction: 'Listen. Two people meet for the first time.',
          question: 'What is the second speaker called?',
          options: ['Daniel', 'María', 'Ana'],
          answer: 'Daniel',
          transcript: '— Hola, me llamo María. ¿Y tú? — Me llamo Daniel. Mucho gusto. — Encantada.',
          speed: 'slow',
          why: 'He says "me llamo Daniel" — literally "I call myself Daniel".',
        }),
        tapTranslation({
          source: 'Me llamo Ana.',
          options: ['My name is Ana.', 'I know Ana.', 'I like Ana.'],
          answer: 'My name is Ana.',
          why: '"Me llamo" is literally "I call myself" — Spanish uses a reflexive verb here.',
          tags: ['vocab:me-llamo'],
        }),
        buildSentence({
          target: 'Hola me llamo Ana',
          tokens: ['llamo', 'Hola', 'Ana', 'me'],
          instruction: 'Introduce yourself as Ana.',
          why: 'The greeting comes first, then "me llamo", then your name.',
          hints: hints('Start with the greeting.', 'The phrase for "my name is" is two words.'),
          tags: ['vocab:me-llamo'],
        }),
        fillBlank({
          template: '¿Cómo te {{blank}}?',
          answers: ['llamas'],
          wordBank: ['llamas', 'llamo', 'llama'],
          why: 'Asking "you", the verb takes the -as ending: te llamas.',
          tags: ['vocab:como-te-llamas', 'grammar:es-present-ar'],
        }),
        mcq({
          question: 'A woman meets you and says "Encantada". What does it mean?',
          options: ['Delighted to meet you', 'Goodbye', 'How are you?'],
          answer: 'Delighted to meet you',
          why: 'The ending agrees with the speaker: a woman says encantada, a man encantado.',
          tags: ['vocab:encantado'],
        }),
        speak({ target: 'Hola, me llamo…', phonetic: 'OH-lah, meh YAH-moh', focusPhonemes: ['ll'] }),
        converse({
          scenario: 'es-meeting-a-classmate',
          goals: ['Greet the other person', 'Say your name and ask theirs', 'Say nice to meet you'],
          minTurns: 4,
          hints: hints('Open with a greeting.', 'Use "me llamo" and then ask "¿y tú?".'),
        }),
        realWorldTask({
          situation: 'A new classmate sits next to you on the first day of a Spanish course. Introduce yourself.',
          goals: ['Greet them', 'Give your name', 'Ask their name', 'Say nice to meet you'],
        }),
      ],
    }),

    lesson({
      slug: 'es-a1-u1-l3',
      title: 'Where Are You From?',
      objective: 'Say where you are from and ask someone else.',
      canDo: 'I can say what country I am from and ask someone else.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['de-donde-eres', 'soy-de'],
      grammar: ['es-ser-estar'],
      activities: [
        listen({
          audio: 'es/a1/u1/where-from',
          instruction: 'Listen to the exchange.',
          question: 'Where is the first speaker from?',
          options: ['Colombia', 'Mexico', 'Spain'],
          answer: 'Colombia',
          transcript: '— ¿De dónde eres? — Soy de Colombia. ¿Y tú? — Yo soy de México.',
          speed: 'slow',
          why: '"Soy de Colombia" — I am from Colombia.',
        }),
        mcq({
          question: 'Why is it "soy de México" and not "estoy de México"?',
          options: [
            'Origin is part of who you are, so it takes ser',
            'Estar is only for the past',
            'Both are equally correct',
          ],
          answer: 'Origin is part of who you are, so it takes ser',
          why: 'Ser covers identity and origin; estar covers location and temporary states.',
          tags: ['grammar:es-ser-estar'],
        }),
        fillBlank({
          template: '{{blank}} de Estados Unidos.',
          answers: ['Soy'],
          wordBank: ['Soy', 'Estoy', 'Tengo'],
          why: 'Origin takes ser: soy de…',
          tags: ['grammar:es-ser-estar', 'vocab:soy-de'],
        }),
        correctGrammar({
          incorrect: 'Estoy de Chile.',
          correct: 'Soy de Chile.',
          why: 'Where you are from is identity, so Spanish uses ser, not estar.',
          topic: 'es-ser-estar',
        }),
        buildSentence({
          target: '¿De dónde eres tú?',
          tokens: ['eres', '¿De', 'tú?', 'dónde'],
          instruction: 'Ask someone where they are from.',
          why: 'The question word opens the sentence; the subject pronoun is optional and comes last for emphasis.',
          tags: ['vocab:de-donde-eres'],
        }),
        speak({ target: 'Soy de Estados Unidos', phonetic: 'soy deh es-TAH-dohs oo-NEE-dohs' }),
        speakResponse({
          situation: 'Someone at a language exchange asks where you are from.',
          question: '¿De dónde eres?',
          goal: 'Say where you are from and ask them back',
          criteria: ['Uses ser correctly', 'Names a place', 'Returns the question'],
          mustInclude: ['soy'],
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u1-l4',
      title: 'Formal and Informal',
      objective: 'Choose between tú and usted.',
      canDo: 'I can decide whether to address someone as tú or usted.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['senor', 'senora'],
      grammar: ['es-present-ar'],
      culture: ['es-tu-usted', 'es-vosotros'],
      activities: [
        mcq({
          question: 'You are checking into a hotel. How do you ask the receptionist their name?',
          options: ['¿Cómo se llama usted?', '¿Cómo te llamas?', '¿Cómo se llaman?'],
          answer: '¿Cómo se llama usted?',
          why: 'A stranger in a professional setting takes usted, and the verb changes to "se llama".',
          tags: ['grammar:register'],
        }),
        categorize({
          instruction: 'Sort each situation by which form you would use.',
          categories: ['tú', 'usted'],
          mapping: {
            'a classmate your age': 'tú',
            'your friend’s grandmother': 'usted',
            'a police officer': 'usted',
            'a child': 'tú',
          },
          why: 'Age, seniority and professional distance push you towards usted; peers and children take tú.',
          tags: ['grammar:register'],
        }),
        multiAnswer({
          question: 'Which of these are usted forms?',
          options: ['¿Cómo está?', '¿Cómo estás?', '¿De dónde es?', '¿De dónde eres?'],
          answers: ['¿Cómo está?', '¿De dónde es?'],
          why: 'Usted takes the same verb ending as él/ella: está, es.',
          tags: ['grammar:register'],
        }),
        correctGrammar({
          incorrect: 'Señora, ¿cómo estás?',
          correct: 'Señora, ¿cómo está?',
          why: 'Addressing someone as "señora" signals formality, so the verb should be the usted form.',
          topic: 'es-ser-estar',
        }),
        mcq({
          question: 'In Latin America, how do you address a group informally?',
          options: ['ustedes', 'vosotros', 'tú'],
          answer: 'ustedes',
          why: 'Vosotros is used in Spain; Latin America uses ustedes for both formal and informal plural.',
          tags: ['grammar:register'],
        }),
        speak({ target: '¿Cómo está usted?', phonetic: 'KOH-moh es-TAH oos-TED' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u1-l5',
      title: 'Unit 1 Review',
      objective: 'Put the whole introduction together.',
      canDo: 'I can hold a complete first-meeting conversation.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      activities: [
        timedChallenge({
          instruction: 'Translate as many as you can.',
          items: [
            ['my name is', 'me llamo'],
            ["what's your name?", '¿cómo te llamas?'],
            ['where are you from?', '¿de dónde eres?'],
            ["I'm from", 'soy de'],
            ['nice to meet you', 'mucho gusto'],
            ['how are you?', '¿cómo estás?'],
          ],
          seconds: 90,
        }),
        dictation({
          audio: 'es/a1/u1/introductions',
          answer: 'Hola, me llamo María',
          alternatives: ['hola me llamo maria'],
          instruction: 'Listen and write the first sentence.',
          speed: 'slow',
          why: 'Listening and writing together is where spelling gaps show up.',
        }),
        storyCompletion({
          story:
            'Hola. Me {{blank}} Daniel. {{blank}} de México. Mucho {{blank}}.',
          answers: ['llamo', 'Soy', 'gusto'],
          wordBank: ['llamo', 'Soy', 'gusto', 'Estoy', 'tengo'],
          why: 'A full self-introduction is three short sentences: name, origin, courtesy.',
        }),
        write({
          task: 'Write three sentences introducing yourself: your name, where you are from, and a polite closing.',
          goal: 'Produce a complete written self-introduction',
          criteria: ['Uses me llamo', 'Uses ser for origin', 'Includes a courtesy phrase'],
          minWords: 8,
          mustInclude: ['llamo'],
        }),
        converse({
          scenario: 'es-meeting-a-classmate',
          goals: ['Greet', 'Exchange names', 'Say where you are from', 'Ask where they are from', 'Close politely'],
          minTurns: 6,
        }),
        realWorldTask({
          situation:
            'You are at a language exchange evening. Introduce yourself to someone new and find out two things about them.',
          goals: ['Introduce yourself', 'Ask their name', 'Ask where they are from', 'Respond to what they say'],
        }),
      ],
    }),
  ],
});

export const ES_A1_UNIT_2 = unit({
  slug: 'es-a1-u2',
  title: 'Family',
  objective: 'Describe your family and understand someone describing theirs.',
  theme: 'family',
  cefr: 'A1',
  realWorldTask: 'Tell a Spanish speaker about your family and ask about theirs.',
  lessons: [
    lesson({
      slug: 'es-a1-u2-l1',
      title: 'Family Words',
      objective: 'Name the members of a family.',
      canDo: 'I can name the people in my family.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['familia', 'madre', 'padre', 'hermano', 'hermana'],
      grammar: ['es-gender'],
      activities: [
        wordMatch({
          instruction: 'Match each family word to its meaning.',
          pairs: [
            ['la madre', 'mother'],
            ['el padre', 'father'],
            ['el hermano', 'brother'],
            ['la hermana', 'sister'],
          ],
          tags: ['vocab:madre', 'vocab:padre', 'vocab:hermano', 'vocab:hermana'],
        }),
        imageMatch({
          instruction: 'Which picture shows "la hermana"?',
          word: 'la hermana',
          options: [
            { text: 'sister', image: 'es/img/hermana' },
            { text: 'grandfather', image: 'es/img/abuelo' },
            { text: 'family', image: 'es/img/familia' },
          ],
          answer: 'sister',
          tags: ['vocab:hermana'],
        }),
        mcq({
          question: 'Why is it "la madre" but "el padre"?',
          options: [
            'Nouns have a gender and the article must match',
            'Because madre is longer',
            'Both articles are interchangeable',
          ],
          answer: 'Nouns have a gender and the article must match',
          why: 'Gender is a property of the noun itself, so learn each word with its article.',
          tags: ['grammar:es-gender'],
        }),
        categorize({
          instruction: 'Sort each word by its article.',
          categories: ['el', 'la'],
          mapping: {
            padre: 'el',
            madre: 'la',
            hermano: 'el',
            hermana: 'la',
            familia: 'la',
          },
          why: 'Most -o words are masculine and most -a words feminine, but the article is what you memorise.',
          tags: ['grammar:es-gender'],
        }),
        speak({ target: 'Mi familia es pequeña', phonetic: 'mee fah-MEE-lyah es peh-KEH-nyah', focusPhonemes: ['ñ'] }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u2-l2',
      title: 'How Many Do You Have?',
      objective: 'Use tener to say what family you have.',
      canDo: 'I can say how many brothers and sisters I have.',
      cefr: 'A1',
      minutes: 9,
      vocabulary: ['tener', 'hijo', 'hija'],
      grammar: ['es-tener'],
      activities: [
        listen({
          audio: 'es/a1/u2/family',
          instruction: 'Listen to the conversation about family.',
          question: 'How many sisters does the speaker have?',
          options: ['Two', 'One', 'Three'],
          answer: 'Two',
          transcript: '— ¿Tienes hermanos? — Sí, tengo dos hermanas y un hermano. — ¿Cuántos años tienen? — Mi hermana mayor tiene treinta años.',
          speed: 'slow',
          why: '"Tengo dos hermanas y un hermano" — two sisters and one brother.',
        }),
        fillBlank({
          template: '{{blank}} dos hermanas.',
          answers: ['Tengo'],
          wordBank: ['Tengo', 'Tienes', 'Tiene'],
          why: 'The first person of tener is irregular: tengo.',
          tags: ['grammar:es-tener'],
        }),
        fillBlank({
          template: '¿{{blank}} hermanos?',
          answers: ['Tienes'],
          wordBank: ['Tienes', 'Tengo', 'Tienen'],
          why: 'Asking "you", tener becomes tienes.',
          tags: ['grammar:es-tener'],
        }),
        buildSentence({
          target: 'Tengo un hermano y dos hermanas',
          tokens: ['hermanas', 'Tengo', 'y', 'un', 'dos', 'hermano'],
          instruction: 'Say you have one brother and two sisters.',
          why: 'The number goes before the noun, and "y" joins the two parts.',
          tags: ['grammar:es-tener'],
        }),
        speakResponse({
          situation: 'A new friend asks about your family.',
          question: '¿Tienes hermanos?',
          goal: 'Say whether you have brothers or sisters, and how many',
          criteria: ['Uses tengo', 'Gives a number', 'Names the family member'],
          mustInclude: ['tengo'],
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u2-l3',
      title: 'How Old Are You?',
      objective: 'Give ages using tener.',
      canDo: 'I can say how old I am and ask someone else.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['anos', 'veinte', 'treinta'],
      grammar: ['es-tener'],
      activities: [
        tapTranslation({
          source: 'Tengo veinticinco años.',
          options: ["I'm twenty-five years old.", 'I have twenty-five things.', 'I want twenty-five.'],
          answer: "I'm twenty-five years old.",
          why: 'Spanish "has" an age rather than "being" one.',
          tags: ['grammar:es-tener', 'vocab:anos'],
        }),
        correctGrammar({
          incorrect: 'Yo soy 25 años.',
          correct: 'Tengo 25 años.',
          why: 'Spanish expresses age with tener (to have), not ser (to be). This is the single most common English-speaker error at A1.',
          topic: 'es-tener',
          hints: hints(
            'Age is something you have in Spanish.',
            'The verb you want is tener.',
            'The first person of tener is irregular.',
          ),
        }),
        fillBlank({
          template: 'Mi hermana {{blank}} treinta años.',
          answers: ['tiene'],
          wordBank: ['tiene', 'tengo', 'es'],
          why: 'Third person singular of tener is tiene.',
          tags: ['grammar:es-tener'],
        }),
        mcq({
          question: 'How do you ask a friend their age?',
          options: ['¿Cuántos años tienes?', '¿Cuántos años eres?', '¿Qué edad estás?'],
          answer: '¿Cuántos años tienes?',
          why: 'Literally "how many years do you have?".',
          tags: ['grammar:es-tener'],
        }),
        translate({
          source: 'My brother is twenty years old.',
          answer: 'Mi hermano tiene veinte años.',
          alternatives: ['Mi hermano tiene 20 años'],
          why: 'Age uses tener, and the possessive "mi" agrees with the singular noun.',
          tags: ['grammar:es-tener', 'grammar:es-possessives'],
        }),
        speak({ target: 'Tengo veinticinco años', phonetic: 'TEN-goh bayn-tee-SEEN-koh AH-nyohs', focusPhonemes: ['ñ'] }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u2-l4',
      title: 'My, Your, Our',
      objective: 'Use possessive adjectives.',
      canDo: 'I can say whose family member I am talking about.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['abuelo', 'abuela', 'esposo', 'esposa'],
      grammar: ['es-possessives'],
      activities: [
        mcq({
          question: 'Which is correct: "my sisters"?',
          options: ['mis hermanas', 'mi hermanas', 'mío hermanas'],
          answer: 'mis hermanas',
          why: 'The possessive agrees in number with what is owned, not with the owner.',
          tags: ['grammar:es-possessives'],
        }),
        fillBlank({
          template: '{{blank}} abuela vive en Sevilla.',
          answers: ['Mi'],
          wordBank: ['Mi', 'Mis', 'Nuestros'],
          why: 'One grandmother, so the singular "mi".',
          tags: ['grammar:es-possessives'],
        }),
        correctGrammar({
          incorrect: 'Mis hermana tiene diez años.',
          correct: 'Mi hermana tiene diez años.',
          why: 'One sister, so the possessive is singular: mi.',
          topic: 'es-possessives',
        }),
        wordMatch({
          instruction: 'Match each word to its meaning.',
          pairs: [
            ['el abuelo', 'grandfather'],
            ['la abuela', 'grandmother'],
            ['el esposo', 'husband'],
            ['la esposa', 'wife'],
          ],
          tags: ['vocab:abuelo', 'vocab:abuela'],
        }),
        buildSentence({
          target: 'Nuestros abuelos viven en México',
          tokens: ['viven', 'Nuestros', 'México', 'abuelos', 'en'],
          instruction: 'Say your grandparents live in Mexico.',
          why: '"Nuestros" agrees with the masculine plural "abuelos".',
          tags: ['grammar:es-possessives'],
        }),
        speak({ target: 'Mi abuela vive en Sevilla', focusPhonemes: ['b', 'v'] }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u2-l5',
      title: 'Unit 2 Review',
      objective: 'Describe a whole family.',
      canDo: 'I can describe my family in several sentences.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      activities: [
        listen({
          audio: 'es/a1/u2/family',
          instruction: 'Listen again, this time at normal speed.',
          question: 'How old is the older sister?',
          options: ['Thirty', 'Thirteen', 'Twenty'],
          answer: 'Thirty',
          transcript: '— ¿Tienes hermanos? — Sí, tengo dos hermanas y un hermano. — ¿Cuántos años tienen? — Mi hermana mayor tiene treinta años.',
          speed: 'normal',
          why: '"Treinta" is thirty; "trece" would be thirteen.',
        }),
        timedChallenge({
          instruction: 'Translate as many as you can.',
          items: [
            ['mother', 'la madre'],
            ['brother', 'el hermano'],
            ['I have', 'tengo'],
            ['my sisters', 'mis hermanas'],
            ['grandmother', 'la abuela'],
            ['how old are you?', '¿cuántos años tienes?'],
          ],
          seconds: 90,
        }),
        storyCompletion({
          story: 'Mi familia es pequeña. {{blank}} dos hermanos. Mi hermana {{blank}} veinte años y vive con {{blank}} abuelos.',
          answers: ['Tengo', 'tiene', 'mis'],
          wordBank: ['Tengo', 'tiene', 'mis', 'soy', 'mi'],
          why: 'Tener for both having siblings and giving an age; "mis" agrees with the plural abuelos.',
        }),
        write({
          task: 'Write four sentences about your family: how many people, who they are, and one age.',
          goal: 'Describe a family in writing',
          criteria: ['Uses tener at least twice', 'Uses a possessive', 'Gives an age correctly'],
          minWords: 20,
          mustInclude: ['tengo'],
        }),
        realWorldTask({
          situation: 'A Spanish-speaking colleague asks about your family over lunch.',
          goals: ['Say how many siblings you have', 'Give one person\'s age', 'Ask about their family'],
        }),
      ],
    }),
  ],
});

export const ES_A1_UNIT_3 = unit({
  slug: 'es-a1-u3',
  title: 'Daily Life',
  objective: 'Describe your routine using regular present-tense verbs.',
  theme: 'daily routine',
  cefr: 'A1',
  realWorldTask: 'Describe your typical weekday to a Spanish speaker.',
  lessons: [
    lesson({
      slug: 'es-a1-u3-l1',
      title: 'Regular -ar Verbs',
      objective: 'Conjugate and use the most common verb pattern in Spanish.',
      canDo: 'I can say what I and others do, using -ar verbs.',
      cefr: 'A1',
      minutes: 9,
      vocabulary: ['trabajar', 'estudiar', 'hablar'],
      grammar: ['es-present-ar'],
      activities: [
        mcq({
          question: 'Which ending goes with "yo" for an -ar verb?',
          options: ['-o', '-as', '-amos'],
          answer: '-o',
          why: 'hablo, trabajo, estudio — the yo form always ends in -o.',
          tags: ['grammar:es-present-ar'],
        }),
        fillBlank({
          template: 'Yo {{blank}} español todos los días.',
          answers: ['estudio'],
          wordBank: ['estudio', 'estudias', 'estudiar'],
          why: 'The yo form of estudiar is estudio; the infinitive cannot be the main verb.',
          tags: ['grammar:es-present-ar'],
        }),
        fillBlank({
          template: 'Nosotros {{blank}} en una oficina.',
          answers: ['trabajamos'],
          wordBank: ['trabajamos', 'trabajan', 'trabajo'],
          why: 'The nosotros ending for -ar verbs is -amos.',
          tags: ['grammar:es-present-ar'],
        }),
        correctGrammar({
          incorrect: 'Ellos habla inglés.',
          correct: 'Ellos hablan inglés.',
          why: 'The third person plural of an -ar verb ends in -an.',
          topic: 'es-present-ar',
        }),
        categorize({
          instruction: 'Sort each form by who is doing the action.',
          categories: ['yo', 'tú', 'nosotros'],
          mapping: { hablo: 'yo', hablas: 'tú', hablamos: 'nosotros', trabajo: 'yo', trabajas: 'tú' },
          why: 'The ending alone tells you the subject, which is why Spanish usually drops the pronoun.',
          tags: ['grammar:es-present-ar'],
        }),
        speak({ target: 'Trabajo en una oficina', phonetic: 'trah-BAH-hoh en OO-nah oh-fee-SEE-nah', focusPhonemes: ['j'] }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u3-l2',
      title: '-er and -ir Verbs',
      objective: 'Handle the other two verb patterns.',
      canDo: 'I can use -er and -ir verbs in the present tense.',
      cefr: 'A1',
      minutes: 9,
      vocabulary: ['comer', 'beber', 'vivir'],
      grammar: ['es-present-er-ir'],
      activities: [
        fillBlank({
          template: 'Yo {{blank}} en Madrid.',
          answers: ['vivo'],
          wordBank: ['vivo', 'vives', 'vivimos'],
          why: 'The yo ending is -o for all three verb families.',
          tags: ['grammar:es-present-er-ir'],
        }),
        fillBlank({
          template: 'Nosotros {{blank}} a la una.',
          answers: ['comemos'],
          wordBank: ['comemos', 'comimos', 'comen'],
          why: '-er verbs take -emos in the nosotros form.',
          tags: ['grammar:es-present-er-ir'],
        }),
        correctGrammar({
          incorrect: 'Nosotros vivemos aquí.',
          correct: 'Nosotros vivimos aquí.',
          why: '-ir verbs take -imos, not -emos, in the nosotros form. This is the only place -er and -ir differ.',
          topic: 'es-present-er-ir',
        }),
        multiAnswer({
          question: 'Which of these are correctly conjugated?',
          options: ['como', 'vives', 'bebemos', 'vivimos', 'comen'],
          answers: ['como', 'vives', 'bebemos', 'vivimos', 'comen'],
          why: 'All five follow the regular patterns.',
          tags: ['grammar:es-present-er-ir'],
        }),
        buildSentence({
          target: 'Mi hermano vive en Barcelona',
          tokens: ['Barcelona', 'Mi', 'vive', 'hermano', 'en'],
          instruction: 'Say your brother lives in Barcelona.',
          why: 'Subject, verb, then the place.',
          tags: ['grammar:es-present-er-ir'],
        }),
        speak({ target: 'Vivo en Nueva York y como a la una' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u3-l3',
      title: 'My Daily Routine',
      objective: 'Put verbs together into a description of a normal day.',
      canDo: 'I can describe my daily routine.',
      cefr: 'A1',
      minutes: 9,
      vocabulary: ['levantarse', 'manana', 'tarde', 'noche'],
      grammar: ['es-present-ar'],
      activities: [
        listen({
          audio: 'es/a1/u3/daily-routine',
          instruction: 'Listen to someone describe their day.',
          question: 'What time do they get up?',
          options: ['Seven', 'One', 'Nine'],
          answer: 'Seven',
          transcript: 'Me levanto a las siete. Trabajo en una oficina. Como a la una y estudio español por la noche.',
          speed: 'slow',
          why: '"Me levanto a las siete" — I get up at seven.',
        }),
        mcq({
          question: 'Why is it "me levanto" rather than "levanto"?',
          options: [
            'The action is done to yourself, so the verb is reflexive',
            'It is a spelling rule',
            'Levantar has no other form',
          ],
          answer: 'The action is done to yourself, so the verb is reflexive',
          why: 'Levantar means to lift something; levantarse means to get yourself up.',
          tags: ['vocab:levantarse'],
        }),
        storyCompletion({
          story: 'Me {{blank}} a las siete. {{blank}} en una oficina. Por la {{blank}} estudio español.',
          answers: ['levanto', 'Trabajo', 'noche'],
          wordBank: ['levanto', 'Trabajo', 'noche', 'como', 'mañana'],
          why: 'A routine reads as a sequence of present-tense verbs with time expressions.',
        }),
        translate({
          source: 'I work in the morning and study at night.',
          answer: 'Trabajo por la mañana y estudio por la noche.',
          alternatives: ['Trabajo en la mañana y estudio en la noche'],
          why: 'Spanish marks parts of the day with "por la" (or "en la" in much of Latin America).',
          tags: ['vocab:manana', 'vocab:noche'],
        }),
        speakResponse({
          situation: 'A tutor asks about your typical day.',
          question: '¿Qué haces normalmente durante el día?',
          goal: 'Describe a normal day in at least three sentences',
          criteria: ['Uses at least three different verbs', 'Uses a time expression', 'Stays in the present tense'],
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u3-l4',
      title: 'How Often?',
      objective: 'Say how often you do things.',
      canDo: 'I can say how often I do something.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['siempre', 'nunca', 'a-veces', 'hoy'],
      grammar: ['es-negation'],
      activities: [
        wordMatch({
          instruction: 'Match each expression to its meaning.',
          pairs: [
            ['siempre', 'always'],
            ['nunca', 'never'],
            ['a veces', 'sometimes'],
          ],
          tags: ['vocab:siempre', 'vocab:nunca', 'vocab:a-veces'],
        }),
        mcq({
          question: 'Which sentence is correct Spanish?',
          options: ['No como nunca carne.', 'Como nunca carne.', 'No como algo carne.'],
          answer: 'No como nunca carne.',
          why: 'Spanish keeps the "no" even with another negative word — the double negative is correct here.',
          tags: ['grammar:es-negation'],
        }),
        correctGrammar({
          incorrect: 'Yo no tengo algo.',
          correct: 'No tengo nada.',
          why: 'After a negative, Spanish uses nada rather than algo.',
          topic: 'es-negation',
        }),
        fillBlank({
          template: '{{blank}} estudio por la mañana, pero a veces por la noche.',
          answers: ['Siempre'],
          wordBank: ['Siempre', 'Nunca', 'Nada'],
          why: 'The contrast with "pero a veces" tells you the first word is "siempre".',
          tags: ['vocab:siempre'],
        }),
        buildSentence({
          target: 'Nunca bebo café por la noche',
          tokens: ['noche', 'Nunca', 'café', 'bebo', 'por', 'la'],
          instruction: 'Say you never drink coffee at night.',
          why: 'When nunca opens the sentence, no "no" is needed.',
          tags: ['grammar:es-negation'],
        }),
        speak({ target: 'A veces estudio por la noche' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u3-l5',
      title: 'Unit 3 Review',
      objective: 'Talk about routines fluently.',
      canDo: 'I can describe what I do, when, and how often.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      activities: [
        dictation({
          audio: 'es/a1/u3/daily-routine',
          answer: 'Me levanto a las siete',
          alternatives: ['me levanto a las 7'],
          instruction: 'Listen and write the first sentence.',
          speed: 'slow',
          why: 'Reflexive verbs put the pronoun before the verb.',
        }),
        timedChallenge({
          instruction: 'Conjugate for "yo".',
          items: [
            ['hablar', 'hablo'],
            ['comer', 'como'],
            ['vivir', 'vivo'],
            ['trabajar', 'trabajo'],
            ['estudiar', 'estudio'],
          ],
          seconds: 60,
        }),
        correctGrammar({
          incorrect: 'Nosotros comen a la una.',
          correct: 'Nosotros comemos a la una.',
          why: 'The nosotros form of an -er verb ends in -emos.',
          topic: 'es-present-er-ir',
        }),
        write({
          task: 'Describe your typical Tuesday in five sentences.',
          goal: 'Write a connected description of a routine',
          criteria: ['At least four different verbs', 'At least two time expressions', 'Correct present-tense endings'],
          minWords: 25,
        }),
        realWorldTask({
          situation: 'Your new Spanish-speaking flatmate asks what your week looks like.',
          goals: ['Describe your working day', 'Say when you eat', 'Say how often you study Spanish'],
        }),
      ],
    }),
  ],
});

export const ES_A1_UNIT_4 = unit({
  slug: 'es-a1-u4',
  title: 'Food and Drink',
  objective: 'Order food and drink and say what you like.',
  theme: 'food',
  cefr: 'A1',
  realWorldTask: 'Order a drink and a snack in a café, and understand the price.',
  lessons: [
    lesson({
      slug: 'es-a1-u4-l1',
      title: 'Drinks',
      objective: 'Name common drinks and order one.',
      canDo: 'I can order a drink politely.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['cafe', 'te', 'leche', 'jugo', 'quisiera'],
      culture: ['es-regional-vocabulary'],
      activities: [
        imageMatch({
          instruction: 'Which picture is "el café"?',
          word: 'el café',
          options: [
            { text: 'coffee', image: 'es/img/cafe' },
            { text: 'milk', image: 'es/img/leche' },
            { text: 'water', image: 'es/img/agua' },
          ],
          answer: 'coffee',
          tags: ['vocab:cafe'],
        }),
        mcq({
          question: 'You are in Madrid and want orange juice. What do you ask for?',
          options: ['un zumo de naranja', 'un jugo de naranja', 'una leche de naranja'],
          answer: 'un zumo de naranja',
          why: 'Spain says zumo; most of Latin America says jugo. Both are understood, but each sounds local.',
          tags: ['vocab:jugo'],
        }),
        buildSentence({
          target: 'Quisiera un café con leche por favor',
          tokens: ['leche', 'Quisiera', 'por', 'un', 'con', 'favor', 'café'],
          instruction: 'Order a coffee with milk, politely.',
          why: '"Quisiera" is a softer, more polite "I want".',
          tags: ['vocab:quisiera'],
        }),
        mcq({
          question: 'Which is the most polite way to order?',
          options: ['Quisiera un té, por favor.', 'Quiero un té.', 'Dame un té.'],
          answer: 'Quisiera un té, por favor.',
          why: '"Quiero" is direct; "dame" is blunt. "Quisiera… por favor" is the safe register with a stranger.',
          tags: ['vocab:quisiera'],
        }),
        speak({ target: 'Quisiera un café, por favor', focusPhonemes: ['r'] }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u4-l2',
      title: 'Meals and Food',
      objective: 'Name meals and common dishes.',
      canDo: 'I can name the three meals and say what I eat.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['desayuno', 'almuerzo', 'cena', 'pollo', 'arroz', 'ensalada', 'fruta'],
      culture: ['es-meal-times'],
      activities: [
        wordMatch({
          instruction: 'Match the meal to its time of day.',
          pairs: [
            ['el desayuno', 'breakfast'],
            ['el almuerzo', 'lunch'],
            ['la cena', 'dinner'],
          ],
          tags: ['vocab:desayuno', 'vocab:almuerzo', 'vocab:cena'],
        }),
        mcq({
          question: 'In Spain, roughly when is the main meal of the day?',
          options: ['2–3pm', '12pm', '6pm'],
          answer: '2–3pm',
          why: 'Spanish meal times run later than in the United States; dinner rarely starts before 9pm.',
          tags: ['culture:meal-times'],
        }),
        categorize({
          instruction: 'Sort each item.',
          categories: ['comida', 'bebida'],
          mapping: { 'el pollo': 'comida', 'el arroz': 'comida', 'el café': 'bebida', 'la leche': 'bebida', 'la ensalada': 'comida' },
          why: 'Comida is food, bebida is drink.',
        }),
        imageMatch({
          instruction: 'Which picture is "el arroz"?',
          word: 'el arroz',
          options: [
            { text: 'rice', image: 'es/img/arroz' },
            { text: 'chicken', image: 'es/img/pollo' },
            { text: 'salad', image: 'es/img/ensalada' },
          ],
          answer: 'rice',
          tags: ['vocab:arroz'],
        }),
        translate({
          source: 'For lunch I eat chicken with rice.',
          answer: 'Para el almuerzo como pollo con arroz.',
          alternatives: ['En el almuerzo como pollo con arroz', 'Para la comida como pollo con arroz'],
          why: '"Para" marks purpose here; "con" joins the two foods.',
          tags: ['vocab:almuerzo', 'grammar:es-por-para'],
        }),
        speak({ target: 'Para el desayuno como fruta' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u4-l3',
      title: 'Saying What You Like',
      objective: 'Use gustar correctly.',
      canDo: 'I can say what food and drink I like.',
      cefr: 'A1',
      minutes: 9,
      grammar: ['es-gustar'],
      activities: [
        mcq({
          question: 'How does "me gusta el café" work literally?',
          options: ['Coffee pleases me', 'I please coffee', 'I want coffee'],
          answer: 'Coffee pleases me',
          why: 'The thing liked is the subject, and the person is an indirect object — which is why the verb agrees with the thing.',
          tags: ['grammar:es-gustar'],
        }),
        correctGrammar({
          incorrect: 'Yo gusto el café.',
          correct: 'Me gusta el café.',
          why: 'The person is an indirect object pronoun (me), not the subject.',
          topic: 'es-gustar',
          hints: hints(
            'Think about what is doing the pleasing.',
            'The person takes a pronoun: me, te, le…',
            'The sentence starts with "Me".',
          ),
        }),
        fillBlank({
          template: 'Me {{blank}} las ensaladas.',
          answers: ['gustan'],
          wordBank: ['gustan', 'gusta', 'gusto'],
          why: 'The verb agrees with the plural "las ensaladas".',
          tags: ['grammar:es-gustar'],
        }),
        multiAnswer({
          question: 'Which sentences are correct?',
          options: ['Me gusta el té.', 'Me gustan las frutas.', 'Me gusto el té.', 'Me gustan el té.'],
          answers: ['Me gusta el té.', 'Me gustan las frutas.'],
          why: 'Singular thing → gusta; plural things → gustan.',
          tags: ['grammar:es-gustar'],
        }),
        speakResponse({
          situation: 'A friend asks about your food preferences.',
          question: '¿Qué comida te gusta?',
          goal: 'Say what you like and do not like',
          criteria: ['Uses me gusta or me gustan correctly', 'Names at least two foods', 'Includes one dislike'],
          mustInclude: ['gust'],
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u4-l4',
      title: 'In the Café',
      objective: 'Complete a full café interaction.',
      canDo: 'I can order in a café and pay.',
      cefr: 'A1',
      minutes: 9,
      vocabulary: ['la-cuenta', 'cuanto-cuesta'],
      culture: ['es-restaurant-bill'],
      activities: [
        listen({
          audio: 'es/a1/u4/cafe',
          instruction: 'Listen to the café exchange.',
          question: 'How much does the coffee cost?',
          options: ['€2.50', '€3.50', '€2.15'],
          answer: '€2.50',
          transcript: '— Buenos días. ¿Qué le pongo? — Quisiera un café con leche, por favor. — ¿Algo más? — No, gracias. ¿Cuánto es? — Son dos euros cincuenta.',
          speed: 'slow',
          why: '"Dos euros cincuenta" — two euros fifty.',
        }),
        dialogueCompletion({
          lines: [
            { speaker: 'Camarero', text: '¿Algo más?' },
            { speaker: 'You', text: '___' },
            { speaker: 'Camarero', text: 'Son tres euros.' },
          ],
          options: ['No, gracias. ¿Cuánto es?', 'De nada.', 'Buenas noches.'],
          answer: 'No, gracias. ¿Cuánto es?',
          why: 'Decline politely, then ask the price.',
          tags: ['vocab:cuanto-cuesta'],
        }),
        mcq({
          question: 'Your server has not brought the bill. Why?',
          options: [
            'They are waiting for you to ask — bringing it unasked would be rushing you',
            'They forgot',
            'It is included automatically',
          ],
          answer: 'They are waiting for you to ask — bringing it unasked would be rushing you',
          why: 'In Spain and most of Latin America the bill comes only when you ask: "la cuenta, por favor".',
          tags: ['culture:restaurant-bill'],
        }),
        buildSentence({
          target: 'La cuenta por favor',
          tokens: ['favor', 'La', 'por', 'cuenta'],
          instruction: 'Ask for the bill.',
          why: 'The three-word phrase you will use in every restaurant.',
          tags: ['vocab:la-cuenta'],
        }),
        converse({
          scenario: 'es-cafe-order',
          goals: ['Greet the barista', 'Order a drink', 'Ask the price', 'Thank them and leave'],
          minTurns: 5,
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u4-l5',
      title: 'Unit 4 Review',
      objective: 'Handle a whole café or restaurant visit.',
      canDo: 'I can order food and drink, say what I like, and pay.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      activities: [
        listen({
          audio: 'es/a1/u4/cafe',
          instruction: 'Listen at normal speed.',
          question: 'What does the customer order?',
          options: ['A coffee with milk', 'A tea', 'A juice'],
          answer: 'A coffee with milk',
          transcript: '— Buenos días. ¿Qué le pongo? — Quisiera un café con leche, por favor. — ¿Algo más? — No, gracias. ¿Cuánto es? — Son dos euros cincuenta.',
          speed: 'normal',
          why: '"Un café con leche" — coffee with milk.',
        }),
        timedChallenge({
          instruction: 'Translate as many as you can.',
          items: [
            ['I would like', 'quisiera'],
            ['the bill', 'la cuenta'],
            ['breakfast', 'el desayuno'],
            ['I like coffee', 'me gusta el café'],
            ['how much is it?', '¿cuánto cuesta?'],
            ['chicken', 'el pollo'],
          ],
          seconds: 90,
        }),
        correctGrammar({
          incorrect: 'Me gustan el pollo.',
          correct: 'Me gusta el pollo.',
          why: 'One singular thing being liked, so the verb is singular.',
          topic: 'es-gustar',
        }),
        write({
          task: 'Write a short café order: greet, order two things, ask the price, close politely.',
          goal: 'Write a complete transactional exchange',
          criteria: ['Includes a greeting', 'Uses quisiera or another polite request', 'Asks the price'],
          minWords: 15,
        }),
        realWorldTask({
          situation: 'You are in a café in Mexico City. Order a coffee and something to eat, and pay.',
          goals: ['Greet appropriately', 'Order two items', 'Ask the price', 'Thank the server'],
        }),
      ],
    }),
  ],
});

export const ES_A1_UNIT_5 = unit({
  slug: 'es-a1-u5',
  title: 'Shopping and Numbers',
  objective: 'Buy something, ask prices, and understand larger numbers.',
  theme: 'shopping',
  cefr: 'A1',
  realWorldTask: 'Buy something at a market, ask the price, and ask for something cheaper.',
  lessons: [
    lesson({
      slug: 'es-a1-u5-l1',
      title: 'Bigger Numbers',
      objective: 'Understand numbers up to one hundred.',
      canDo: 'I can understand and say prices up to a hundred.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['veinte', 'treinta', 'cien'],
      activities: [
        wordMatch({
          instruction: 'Match the number.',
          pairs: [
            ['veinte', '20'],
            ['treinta', '30'],
            ['cien', '100'],
          ],
          tags: ['vocab:veinte', 'vocab:treinta', 'vocab:cien'],
        }),
        mcq({
          question: 'How do you say 25?',
          options: ['veinticinco', 'veinte cinco', 'dos cinco'],
          answer: 'veinticinco',
          why: 'The twenties are written as one word: veintiuno, veintidós, veinticinco.',
          tags: ['vocab:veinte'],
        }),
        mcq({
          question: 'How do you say 35?',
          options: ['treinta y cinco', 'treinticinco', 'treinta cinco'],
          answer: 'treinta y cinco',
          why: 'From thirty upwards the numbers separate with "y".',
          tags: ['vocab:treinta'],
        }),
        translate({
          source: 'It costs thirty euros.',
          answer: 'Cuesta treinta euros.',
          alternatives: ['Son treinta euros'],
          why: 'Prices use "cuesta" for one item or "son" for a total.',
          tags: ['vocab:treinta'],
        }),
        speak({ target: 'Son treinta y cinco euros' }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u5-l2',
      title: 'How Much Is It?',
      objective: 'Ask for prices and react to them.',
      canDo: 'I can ask a price and say something is expensive or cheap.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['cuanto-cuesta', 'caro', 'barato', 'dinero'],
      activities: [
        listen({
          audio: 'es/a1/u5/market',
          instruction: 'Listen to the market exchange.',
          question: 'What does the shopper say about the price?',
          options: ['It is a bit expensive', 'It is cheap', 'It is free'],
          answer: 'It is a bit expensive',
          transcript: '— ¿Cuánto cuesta el kilo de fruta? — Tres euros. — Es un poco caro. ¿Tiene algo más barato? — Sí, estas están a dos.',
          speed: 'slow',
          why: '"Es un poco caro" — it is a bit expensive.',
        }),
        buildSentence({
          target: '¿Tiene algo más barato?',
          tokens: ['barato?', '¿Tiene', 'más', 'algo'],
          instruction: 'Ask if they have anything cheaper.',
          why: '"Más barato" is the comparative: cheaper.',
          tags: ['vocab:barato'],
        }),
        fillBlank({
          template: 'Es muy {{blank}}. No tengo tanto dinero.',
          answers: ['caro'],
          wordBank: ['caro', 'barato', 'bien'],
          why: 'The second sentence tells you the price is too high.',
          tags: ['vocab:caro'],
        }),
        mcq({
          question: 'Which question asks the price of one specific item?',
          options: ['¿Cuánto cuesta?', '¿Cuántos años tienes?', '¿Cómo se dice?'],
          answer: '¿Cuánto cuesta?',
          why: '"Cuánto cuesta" for one item, "cuánto cuestan" for several.',
          tags: ['vocab:cuanto-cuesta'],
        }),
        speakResponse({
          situation: 'You are at a market stall and the price seems high.',
          question: 'Son quince euros el kilo.',
          goal: 'React to the price and ask for something cheaper',
          criteria: ['Comments on the price', 'Asks for a cheaper option politely'],
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u5-l3',
      title: 'Shops and Markets',
      objective: 'Talk about where you buy things.',
      canDo: 'I can say where I buy things.',
      cefr: 'A1',
      minutes: 8,
      vocabulary: ['tienda', 'mercado'],
      grammar: ['es-articles-plural'],
      activities: [
        mcq({
          question: 'What is the plural of "la tienda"?',
          options: ['las tiendas', 'los tiendas', 'las tienda'],
          answer: 'las tiendas',
          why: 'Both the article and the noun become plural, and both stay feminine.',
          tags: ['grammar:es-articles-plural'],
        }),
        mcq({
          question: 'What is the plural of "la ciudad"?',
          options: ['las ciudades', 'las ciudads', 'los ciudades'],
          answer: 'las ciudades',
          why: 'Nouns ending in a consonant add -es.',
          tags: ['grammar:es-articles-plural'],
        }),
        correctGrammar({
          incorrect: 'Los tiendas están cerca.',
          correct: 'Las tiendas están cerca.',
          why: '"Tienda" is feminine, so the plural article is "las".',
          topic: 'es-articles-plural',
        }),
        categorize({
          instruction: 'Sort each noun by its article.',
          categories: ['el', 'la'],
          mapping: { mercado: 'el', tienda: 'la', dinero: 'el', fruta: 'la' },
          why: 'Learning the article with the noun is faster than learning rules afterwards.',
          tags: ['grammar:es-gender'],
        }),
        translate({
          source: 'I buy fruit at the market.',
          answer: 'Compro fruta en el mercado.',
          alternatives: ['Compro la fruta en el mercado'],
          why: '"En" marks the place where an action happens.',
          tags: ['vocab:mercado'],
        }),
        reviewChallenge({ count: 6 }),
      ],
    }),

    lesson({
      slug: 'es-a1-u5-l4',
      title: 'A Market Conversation',
      objective: 'Complete a purchase from start to finish.',
      canDo: 'I can buy something at a market.',
      cefr: 'A1',
      minutes: 9,
      activities: [
        dialogueCompletion({
          lines: [
            { speaker: 'Vendedor', text: '¡Buenas! ¿Qué le doy?' },
            { speaker: 'You', text: '___' },
            { speaker: 'Vendedor', text: 'Son cuatro euros.' },
          ],
          options: ['Un kilo de fruta, por favor.', 'De nada.', 'Buenas noches.'],
          answer: 'Un kilo de fruta, por favor.',
          why: 'Answer the question you were asked: what you want.',
        }),
        dictation({
          audio: 'es/a1/u5/market',
          answer: '¿Cuánto cuesta el kilo de fruta?',
          alternatives: ['cuanto cuesta el kilo de fruta'],
          instruction: 'Listen and write the shopper\'s first question.',
          speed: 'slow',
          why: 'Question marks open and close the question in written Spanish.',
        }),
        converse({
          scenario: 'es-market-shopping',
          goals: ['Ask for a quantity', 'Ask the price', 'Ask for something cheaper', 'Pay'],
          minTurns: 5,
        }),
        speak({ target: '¿Cuánto cuesta el kilo?' }),
        realWorldTask({
          situation: 'You are at a market and want a kilo of fruit, but the first price is too high.',
          goals: ['Ask for what you want', 'Ask the price', 'Ask for a cheaper option', 'Complete the purchase'],
        }),
      ],
    }),

    lesson({
      slug: 'es-a1-u5-l5',
      title: 'Unit 5 Review',
      objective: 'Consolidate shopping language.',
      canDo: 'I can handle a simple purchase confidently.',
      cefr: 'A1',
      minutes: 10,
      isReview: true,
      activities: [
        timedChallenge({
          instruction: 'Translate as many as you can.',
          items: [
            ['how much does it cost?', '¿cuánto cuesta?'],
            ['expensive', 'caro'],
            ['cheap', 'barato'],
            ['the market', 'el mercado'],
            ['thirty', 'treinta'],
            ['money', 'el dinero'],
          ],
          seconds: 90,
        }),
        storyCompletion({
          story: 'Voy al {{blank}} los sábados. La fruta es {{blank}} pero muy buena. Cuesta {{blank}} euros el kilo.',
          answers: ['mercado', 'cara', 'tres'],
          wordBank: ['mercado', 'cara', 'tres', 'barata', 'tienda'],
          why: '"Cara" agrees with the feminine "la fruta".',
        }),
        write({
          task: 'Write four sentences about where you shop, what you buy and what it costs.',
          goal: 'Describe shopping habits in writing',
          criteria: ['Uses a price', 'Uses caro or barato correctly', 'Correct article and noun agreement'],
          minWords: 20,
        }),
        realWorldTask({
          situation: 'Buy two different items at a market, comparing prices before you decide.',
          goals: ['Ask two prices', 'Compare them', 'Choose and pay'],
        }),
      ],
    }),
  ],
});
