import {
  buildSentence,
  converse,
  correctGrammar,
  course,
  dialogueCompletion,
  dictation,
  fillBlank,
  hints,
  lesson,
  listen,
  mcq,
  multiAnswer,
  realWorldTask,
  reviewChallenge,
  speak,
  speakResponse,
  storyCompletion,
  timedChallenge,
  translate,
  unit,
  wordMatch,
  write,
} from '../../dsl/builders';

/**
 * Spanish A2 — routine everyday communication.
 *
 * The step up from A1 is the past tense and the ability to deal with a
 * situation that does not go to plan: a delayed flight, a dish you did not
 * expect, an appointment you have to move.
 */
export const ES_A2 = course({
  slug: 'es-a2-everyday',
  title: 'Spanish A2: Everyday Situations',
  description:
    'Order a full meal, talk about what you did last weekend, deal with a travel problem, describe symptoms to a doctor, and rearrange plans — the language for the situations that come up when you actually live in Spanish.',
  cefr: 'A2',
  units: [
    unit({
      slug: 'es-a2-u1',
      title: 'Eating Out',
      objective: 'Order a full meal and ask about dishes you do not recognise.',
      theme: 'food',
      cefr: 'A2',
      realWorldTask: 'Order a two-course meal, ask what a dish contains, and ask for the bill.',
      lessons: [
        lesson({
          slug: 'es-a2-u1-l1',
          title: 'A Full Order',
          objective: 'Order a starter, a main and a drink.',
          canDo: 'I can order a complete meal in a restaurant.',
          cefr: 'A2',
          minutes: 9,
          vocabulary: ['quisiera', 'ensalada', 'pollo', 'arroz'],
          culture: ['es-meal-times'],
          activities: [
            listen({
              audio: 'es/a2/u1/restaurant-order',
              instruction: 'Listen to the order.',
              question: 'What does the customer order as a main course?',
              options: ['Chicken with rice', 'Salad', 'Fish'],
              answer: 'Chicken with rice',
              transcript: '— Buenas tardes. ¿Ya sabe qué va a pedir? — Sí, de primero una ensalada y de segundo el pollo con arroz. — ¿Y para beber? — Agua, por favor.',
              speed: 'normal',
              why: '"De segundo" introduces the main course.',
            }),
            wordMatch({
              instruction: 'Match each part of the meal.',
              pairs: [
                ['de primero', 'for the starter'],
                ['de segundo', 'for the main course'],
                ['de postre', 'for dessert'],
                ['para beber', 'to drink'],
              ],
            }),
            buildSentence({
              target: 'De primero quisiera una ensalada',
              tokens: ['ensalada', 'De', 'quisiera', 'primero', 'una'],
              instruction: 'Order a salad as a starter.',
              why: 'The course marker opens the sentence, then the polite request.',
              tags: ['vocab:quisiera'],
            }),
            fillBlank({
              template: '¿Y {{blank}} beber? — Agua, por favor.',
              answers: ['para'],
              wordBank: ['para', 'por', 'de'],
              why: '"Para" marks purpose: what the drink is for.',
              tags: ['grammar:es-por-para'],
            }),
            speak({ target: 'De segundo, el pollo con arroz, por favor' }),
            reviewChallenge({ count: 6 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u1-l2',
          title: 'What Is In It?',
          objective: 'Ask what a dish contains and describe dietary needs.',
          canDo: 'I can ask what a dish contains and say what I cannot eat.',
          cefr: 'A2',
          minutes: 9,
          vocabulary: ['probar'],
          activities: [
            listen({
              audio: 'es/a2/u1/restaurant-question',
              instruction: 'Listen to the question about a dish.',
              question: 'What is in the house salad?',
              options: ['Tomato, onion and cheese', 'Chicken and rice', 'Fruit'],
              answer: 'Tomato, onion and cheese',
              transcript: '— ¿Qué lleva la ensalada de la casa? — Lleva tomate, cebolla y queso. — Perfecto, entonces esa.',
              speed: 'normal',
              why: '"Llevar" is the verb used for what a dish contains.',
            }),
            mcq({
              question: 'How do you ask what a dish contains?',
              options: ['¿Qué lleva?', '¿Qué tiene años?', '¿Cuánto cuesta?'],
              answer: '¿Qué lleva?',
              why: 'Literally "what does it carry?" — the standard restaurant question.',
            }),
            translate({
              source: "I can't eat cheese.",
              answer: 'No puedo comer queso.',
              alternatives: ['No como queso'],
              why: '"Poder" plus the infinitive expresses ability or permission.',
            }),
            buildSentence({
              target: 'Soy alérgico a los frutos secos',
              tokens: ['secos', 'Soy', 'a', 'frutos', 'alérgico', 'los'],
              instruction: 'Say you are allergic to nuts.',
              why: '"Alérgico a" takes the article before the food.',
            }),
            speakResponse({
              situation: 'A waiter recommends a dish you are unsure about.',
              question: 'Le recomiendo la paella de la casa.',
              goal: 'Ask what it contains and decide',
              criteria: ['Asks what is in the dish', 'Responds to the answer', 'Places an order'],
              hints: hints('The verb for what a dish contains is "llevar".'),
            }),
            reviewChallenge({ count: 6 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u1-l3',
          title: 'Paying and Tipping',
          objective: 'Close a restaurant visit correctly.',
          canDo: 'I can pay and tip appropriately.',
          cefr: 'A2',
          minutes: 8,
          vocabulary: ['la-cuenta'],
          culture: ['es-restaurant-bill'],
          activities: [
            mcq({
              question: 'You are in Mexico and the bill is 200 pesos. What is a normal tip?',
              options: ['Around 20 pesos (10%)', 'Nothing', '100 pesos'],
              answer: 'Around 20 pesos (10%)',
              why: 'Around 10% is standard in Mexico and much of Latin America; in Spain, rounding up is more usual.',
              tags: ['culture:restaurant-bill'],
            }),
            dialogueCompletion({
              lines: [
                { speaker: 'You', text: '___' },
                { speaker: 'Camarero', text: 'Ahora se la traigo.' },
              ],
              options: ['La cuenta, por favor.', 'Buenos días.', '¿Qué lleva?'],
              answer: 'La cuenta, por favor.',
              why: 'The bill only arrives when you ask for it.',
              tags: ['vocab:la-cuenta'],
            }),
            translate({
              source: 'Can we pay by card?',
              answer: '¿Podemos pagar con tarjeta?',
              alternatives: ['¿Se puede pagar con tarjeta?'],
              why: '"Con" for the means of payment.',
            }),
            speak({ target: '¿Podemos pagar con tarjeta?' }),
            reviewChallenge({ count: 5 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u1-l4',
          title: 'A Complete Restaurant Visit',
          objective: 'Handle a restaurant from arrival to payment.',
          canDo: 'I can manage a whole restaurant visit in Spanish.',
          cefr: 'A2',
          minutes: 10,
          activities: [
            converse({
              scenario: 'es-restaurant-meal',
              goals: ['Order a starter and a main course', 'Ask what a dish contains', 'Ask for the bill'],
              minTurns: 6,
              cefr: 'A2',
            }),
            dictation({
              audio: 'es/a2/u1/restaurant-order',
              answer: 'De primero una ensalada y de segundo el pollo con arroz',
              alternatives: ['de primero una ensalada y de segundo el pollo con arroz.'],
              instruction: 'Listen and write the order.',
              speed: 'normal',
              why: 'Long orders are where course markers and articles slip.',
            }),
            realWorldTask({
              situation:
                'You are at a restaurant with a Spanish-speaking friend. Order for yourself, ask about one dish, and settle the bill.',
              goals: ['Order two courses', 'Ask what one dish contains', 'Ask for the bill and pay'],
              cefr: 'A2',
            }),
          ],
        }),

        lesson({
          slug: 'es-a2-u1-l5',
          title: 'Unit 1 Review',
          objective: 'Consolidate restaurant language.',
          canDo: 'I can eat out confidently in Spanish.',
          cefr: 'A2',
          minutes: 9,
          isReview: true,
          vocabulary: ['reserva'],
          activities: [
            timedChallenge({
              instruction: 'Translate as many as you can.',
              items: [
                ['what does it contain?', '¿qué lleva?'],
                ['for the starter', 'de primero'],
                ['the bill', 'la cuenta'],
                ["I can't eat", 'no puedo comer'],
                ['to drink', 'para beber'],
                ['by card', 'con tarjeta'],
              ],
              seconds: 90,
            }),
            write({
              task: 'Write a short restaurant dialogue: greeting, order, a question about a dish, and asking for the bill.',
              goal: 'Write a complete transactional dialogue',
              criteria: ['Includes both speakers', 'Uses a polite request form', 'Asks about a dish'],
              minWords: 40,
              cefr: 'A2',
            }),
            reviewChallenge({ source: 'recent_mistakes', count: 10 }),
          ],
        }),
      ],
    }),

    unit({
      slug: 'es-a2-u2',
      title: 'Talking About the Past',
      objective: 'Say what you did, using the preterite.',
      theme: 'past experiences',
      cefr: 'A2',
      realWorldTask: 'Tell a Spanish speaker what you did at the weekend, in at least five sentences.',
      lessons: [
        lesson({
          slug: 'es-a2-u2-l1',
          title: 'Regular Preterite',
          objective: 'Form the preterite of regular verbs.',
          canDo: 'I can say what I did using regular verbs.',
          cefr: 'A2',
          minutes: 10,
          vocabulary: ['ayer', 'anoche', 'comi'],
          grammar: ['es-preterite'],
          activities: [
            mcq({
              question: 'Which ending marks "I" in the preterite of an -ar verb?',
              options: ['-é', '-o', '-aba'],
              answer: '-é',
              why: 'hablé, trabajé, estudié. The accent is what distinguishes it from the present.',
              tags: ['grammar:es-preterite'],
            }),
            fillBlank({
              template: 'Ayer {{blank}} en un restaurante.',
              answers: ['comí'],
              wordBank: ['comí', 'como', 'comía'],
              why: '"Ayer" marks a finished action, so the preterite is required.',
              tags: ['grammar:es-preterite'],
              hints: hints(
                'The word "ayer" tells you this is finished.',
                'The verb is comer.',
                'The first-person preterite of an -er verb ends in -í.',
              ),
            }),
            correctGrammar({
              incorrect: 'Ayer como en un restaurante.',
              correct: 'Ayer comí en un restaurante.',
              why: 'A completed action in the past needs the preterite, not the present.',
              topic: 'es-preterite',
            }),
            multiAnswer({
              question: 'Which are preterite forms?',
              options: ['hablé', 'hablo', 'comiste', 'vivimos', 'estudio'],
              answers: ['hablé', 'comiste'],
              why: '"Vivimos" is identical in the present and the preterite for -ir verbs; only context tells them apart, so it is not a safe answer here.',
              tags: ['grammar:es-preterite'],
            }),
            speak({ target: 'Ayer comí con mi familia' }),
            reviewChallenge({ count: 8 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u2-l2',
          title: 'Irregular Preterite',
          objective: 'Handle the common irregular past forms.',
          canDo: 'I can use ir, ser, tener and hacer in the past.',
          cefr: 'A2',
          minutes: 10,
          vocabulary: ['fui', 'la-semana-pasada'],
          grammar: ['es-preterite'],
          activities: [
            mcq({
              question: '"Fui" can mean two things. Which?',
              options: ['I went / I was', 'I did / I have', 'I ate / I drank'],
              answer: 'I went / I was',
              why: 'Ir and ser share the same preterite forms; only context distinguishes them.',
              tags: ['grammar:es-preterite'],
            }),
            fillBlank({
              template: 'La semana pasada {{blank}} al mercado.',
              answers: ['fui'],
              wordBank: ['fui', 'voy', 'iba'],
              why: 'A completed trip last week takes the preterite of ir.',
              tags: ['grammar:es-preterite'],
            }),
            wordMatch({
              instruction: 'Match each infinitive to its "yo" preterite form.',
              pairs: [
                ['ir', 'fui'],
                ['tener', 'tuve'],
                ['hacer', 'hice'],
                ['estar', 'estuve'],
              ],
              tags: ['grammar:es-preterite'],
            }),
            translate({
              source: 'What did you do at the weekend?',
              answer: '¿Qué hiciste el fin de semana?',
              alternatives: ['¿Qué hiciste este fin de semana?'],
              why: 'The second person preterite of hacer is hiciste.',
              tags: ['grammar:es-preterite'],
              cefr: 'A2',
            }),
            speak({ target: 'El fin de semana fui a la playa' }),
            reviewChallenge({ count: 8 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u2-l3',
          title: 'Telling a Story',
          objective: 'Sequence several past events.',
          canDo: 'I can tell a short story about something I did.',
          cefr: 'A2',
          minutes: 10,
          grammar: ['es-preterite'],
          activities: [
            listen({
              audio: 'es/a2/u2/weekend-past',
              instruction: 'Listen to the account of a weekend.',
              question: 'When did they come back?',
              options: ['Sunday night', 'Saturday morning', 'Monday'],
              answer: 'Sunday night',
              transcript: '— ¿Qué hiciste el fin de semana? — Fui a la playa con mi familia. Comimos en un restaurante y volvimos el domingo por la noche.',
              speed: 'normal',
              why: '"Volvimos el domingo por la noche" — we came back on Sunday night.',
            }),
            storyCompletion({
              story:
                'El sábado {{blank}} a la playa. {{blank}} en un restaurante y por la noche {{blank}} a casa.',
              answers: ['fui', 'Comí', 'volví'],
              wordBank: ['fui', 'Comí', 'volví', 'voy', 'como'],
              why: 'A narrative is a chain of preterite verbs joined by time markers.',
              cefr: 'A2',
            }),
            buildSentence({
              target: 'Primero fuimos al mercado y después comimos en casa',
              tokens: ['comimos', 'Primero', 'y', 'al', 'fuimos', 'después', 'mercado', 'en', 'casa'],
              instruction: 'Sequence two past events.',
              why: '"Primero… después…" is the simplest way to order a story.',
              cefr: 'A2',
              tags: ['grammar:es-preterite'],
            }),
            speakResponse({
              situation: 'A friend asks about your weekend.',
              question: '¿Qué hiciste el fin de semana?',
              goal: 'Describe at least three things you did, in order',
              criteria: ['At least three preterite verbs', 'Uses a sequencing word', 'Stays in the past'],
              cefr: 'A2',
            }),
            reviewChallenge({ count: 8 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u2-l4',
          title: 'Past and Background',
          objective: 'Meet the imperfect and see how it differs from the preterite.',
          canDo: 'I can describe how things were, as well as what happened.',
          cefr: 'A2',
          minutes: 10,
          grammar: ['es-imperfect'],
          activities: [
            mcq({
              question: 'Which sentence describes a repeated childhood habit?',
              options: ['Siempre íbamos a la playa.', 'Fuimos a la playa el sábado.', 'Vamos a la playa.'],
              answer: 'Siempre íbamos a la playa.',
              why: 'The imperfect covers what used to happen; the preterite reports one finished event.',
              tags: ['grammar:es-imperfect'],
            }),
            fillBlank({
              template: 'Cuando {{blank}} niño, vivía en Lima.',
              answers: ['era'],
              wordBank: ['era', 'fui', 'soy'],
              why: 'Childhood is background, so it takes the imperfect of ser: era.',
              tags: ['grammar:es-imperfect'],
            }),
            correctGrammar({
              incorrect: 'Cuando fui niño, viví en Lima.',
              correct: 'Cuando era niño, vivía en Lima.',
              why: 'A state that lasted years is background, so both verbs take the imperfect.',
              topic: 'es-imperfect',
              hints: hints(
                'Was this one finished event, or how things were for a long time?',
                'Ongoing background takes the imperfect.',
              ),
            }),
            mcq({
              question: 'In "Comía cuando llamaste", which verb is the interruption?',
              options: ['llamaste', 'comía', 'neither'],
              answer: 'llamaste',
              why: 'The imperfect sets the scene; the preterite is the event that cuts into it.',
              tags: ['grammar:es-imperfect', 'grammar:es-preterite'],
            }),
            translate({
              source: 'I was eating when you called.',
              answer: 'Comía cuando llamaste.',
              alternatives: ['Estaba comiendo cuando llamaste'],
              why: 'Background in the imperfect, interruption in the preterite.',
              cefr: 'A2',
              tags: ['grammar:es-imperfect'],
            }),
            reviewChallenge({ count: 8 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u2-l5',
          title: 'Unit 2 Review',
          objective: 'Consolidate the past tenses.',
          canDo: 'I can talk about the past accurately enough to be understood.',
          cefr: 'A2',
          minutes: 12,
          isReview: true,
          activities: [
            timedChallenge({
              instruction: 'Give the "yo" preterite.',
              items: [
                ['hablar', 'hablé'],
                ['comer', 'comí'],
                ['ir', 'fui'],
                ['tener', 'tuve'],
                ['hacer', 'hice'],
                ['vivir', 'viví'],
              ],
              seconds: 90,
            }),
            correctGrammar({
              incorrect: 'Ayer iba al cine y veía una película muy buena.',
              correct: 'Ayer fui al cine y vi una película muy buena.',
              why: 'Both are single finished events on a specific day, so both take the preterite.',
              topic: 'es-preterite',
            }),
            write({
              task: 'Write about a memorable day: what you did, and what the situation was like.',
              goal: 'Narrate a past experience',
              criteria: ['At least four preterite verbs', 'At least one imperfect verb', 'Events in a clear order'],
              minWords: 50,
              cefr: 'A2',
            }),
            realWorldTask({
              situation: 'A Spanish-speaking friend asks what you did on your last holiday.',
              goals: ['Say where you went', 'Say three things you did', 'Describe what the place was like'],
              cefr: 'A2',
            }),
          ],
        }),
      ],
    }),

    unit({
      slug: 'es-a2-u3',
      title: 'When Travel Goes Wrong',
      objective: 'Deal with a delay, a missed connection or lost luggage.',
      theme: 'travel',
      cefr: 'A2',
      realWorldTask: 'Explain a travel problem at a desk and negotiate a solution.',
      lessons: [
        lesson({
          slug: 'es-a2-u3-l1',
          title: 'Delays and Cancellations',
          objective: 'Understand and report a delay.',
          canDo: 'I can explain that my flight was delayed or cancelled.',
          cefr: 'A2',
          minutes: 9,
          vocabulary: ['retraso', 'vuelo', 'perder'],
          activities: [
            listen({
              audio: 'es/a2/u3/travel-problem',
              instruction: 'Listen to the exchange at the airline desk.',
              question: 'What solution is offered?',
              options: ["Tomorrow's 8am flight", 'A refund', 'A hotel'],
              answer: "Tomorrow's 8am flight",
              transcript: '— Mi vuelo tuvo un retraso de tres horas y perdí la conexión. — Lo siento. Le puedo poner en el vuelo de mañana a las ocho.',
              speed: 'normal',
              why: '"Le puedo poner en el vuelo de mañana a las ocho."',
            }),
            buildSentence({
              target: 'Mi vuelo tuvo un retraso de tres horas',
              tokens: ['horas', 'Mi', 'un', 'tuvo', 'retraso', 'de', 'tres', 'vuelo'],
              instruction: 'Explain that your flight was delayed by three hours.',
              why: '"Tener un retraso de…" is the standard phrasing.',
              cefr: 'A2',
              tags: ['grammar:es-preterite'],
            }),
            translate({
              source: 'I missed my connection.',
              answer: 'Perdí la conexión.',
              alternatives: ['Perdí mi conexión'],
              why: 'Perder is used for missing a flight or train, not only for losing an object.',
              cefr: 'A2',
              tags: ['vocab:perder'],
            }),
            mcq({
              question: 'Which sentence reports a cancellation?',
              options: ['Cancelaron el vuelo.', 'El vuelo sale a las ocho.', 'Perdí la maleta.'],
              answer: 'Cancelaron el vuelo.',
              why: 'The third person plural without a subject is the normal way to say "it was cancelled".',
            }),
            speak({ target: 'Mi vuelo tuvo un retraso y perdí la conexión' }),
            reviewChallenge({ count: 7 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u3-l2',
          title: 'Lost Luggage',
          objective: 'Report lost luggage and describe it.',
          canDo: 'I can report lost luggage and describe my bag.',
          cefr: 'A2',
          minutes: 9,
          vocabulary: ['equipaje'],
          activities: [
            translate({
              source: 'My luggage did not arrive.',
              answer: 'Mi equipaje no llegó.',
              alternatives: ['No llegó mi equipaje'],
              why: 'Preterite for a completed non-event, with "no" before the verb.',
              cefr: 'A2',
              tags: ['vocab:equipaje', 'grammar:es-negation'],
            }),
            buildSentence({
              target: 'Es una maleta negra grande',
              tokens: ['grande', 'Es', 'negra', 'maleta', 'una'],
              instruction: 'Describe your bag: a large black suitcase.',
              why: 'Adjectives follow the noun, and colour comes before size in this order.',
              cefr: 'A2',
            }),
            dialogueCompletion({
              lines: [
                { speaker: 'Agente', text: '¿Puede describir su maleta?' },
                { speaker: 'You', text: '___' },
              ],
              options: ['Es negra, grande y tiene una etiqueta roja.', 'Son las cuatro.', 'Me llamo Ana.'],
              answer: 'Es negra, grande y tiene una etiqueta roja.',
              why: 'A description answers the question with adjectives and a distinguishing feature.',
            }),
            speakResponse({
              situation: 'Your suitcase has not arrived and the agent asks for details.',
              question: '¿Cuándo llegó su vuelo y cómo es su maleta?',
              goal: 'Give the flight details and describe the bag',
              criteria: ['States when the flight arrived', 'Describes the bag with at least two adjectives'],
              cefr: 'A2',
            }),
            reviewChallenge({ count: 7 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u3-l3',
          title: 'Asking Who Pays',
          objective: 'Ask about costs and responsibility politely but firmly.',
          canDo: 'I can ask who is responsible for the cost of a change.',
          cefr: 'A2',
          minutes: 9,
          activities: [
            translate({
              source: 'Who pays for the change?',
              answer: '¿Quién paga el cambio?',
              alternatives: ['¿Quién paga por el cambio?'],
              why: '"Quién" asks who; the verb stays in the present.',
              cefr: 'A2',
            }),
            mcq({
              question: 'Which is the politest way to push back on a refusal?',
              options: [
                '¿Podría comprobarlo otra vez, por favor?',
                '¡Eso no es verdad!',
                'Compruébalo.',
              ],
              answer: '¿Podría comprobarlo otra vez, por favor?',
              why: 'The conditional "podría" softens a request considerably, which matters when you need someone\'s help.',
            }),
            fillBlank({
              template: '¿{{blank}} ayudarme con el cambio de vuelo?',
              answers: ['Podría'],
              wordBank: ['Podría', 'Puedo', 'Quiero'],
              why: 'Asking someone else what they could do takes podría.',
            }),
            speak({ target: '¿Podría ayudarme, por favor?' }),
            reviewChallenge({ count: 7 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u3-l4',
          title: 'Solving the Problem',
          objective: 'Handle the whole situation end to end.',
          canDo: 'I can resolve a travel problem in Spanish.',
          cefr: 'A2',
          minutes: 12,
          activities: [
            dialogueCompletion({
              lines: [
                { speaker: 'Agente', text: 'Lo siento, ese cambio no está cubierto.' },
                { speaker: 'You', text: '___' },
              ],
              options: [
                '¿Podría comprobarlo otra vez, por favor? El retraso fue de la aerolínea.',
                'Vale, gracias.',
                '¡Eso no es verdad!',
              ],
              answer: '¿Podría comprobarlo otra vez, por favor? El retraso fue de la aerolínea.',
              why: 'Pushing back politely with a reason keeps the conversation open; anger or acceptance both end it.',
            }),
            converse({
              scenario: 'es-missed-flight',
              goals: [
                'Explain what happened',
                'Ask about the next available flight',
                'Ask who pays for the change',
                'Reach an agreed solution',
              ],
              minTurns: 7,
              cefr: 'A2',
            }),
            realWorldTask({
              situation:
                'Your connecting flight has gone and the desk agent initially says the change is not covered. Get to a solution.',
              goals: ['Explain the problem clearly', 'Ask for options', 'Push back politely once', 'Confirm what will happen'],
              constraints: ['Stay polite throughout'],
              cefr: 'A2',
            }),
          ],
        }),

        lesson({
          slug: 'es-a2-u3-l5',
          title: 'Unit 3 Review',
          objective: 'Consolidate problem-solving language.',
          canDo: 'I can deal with things going wrong while travelling.',
          cefr: 'A2',
          minutes: 10,
          isReview: true,
          activities: [
            timedChallenge({
              instruction: 'Translate as many as you can.',
              items: [
                ['the delay', 'el retraso'],
                ['I missed the flight', 'perdí el vuelo'],
                ['my luggage', 'mi equipaje'],
                ['could you help me?', '¿podría ayudarme?'],
                ['they cancelled it', 'lo cancelaron'],
              ],
              seconds: 90,
            }),
            dictation({
              audio: 'es/a2/u3/travel-problem',
              answer: 'Mi vuelo tuvo un retraso de tres horas y perdí la conexión',
              alternatives: ['mi vuelo tuvo un retraso de tres horas y perdi la conexion'],
              instruction: 'Listen and write the traveller\'s explanation.',
              speed: 'normal',
              why: 'Long sentences at natural speed are the real A2 listening test.',
            }),
            write({
              task: 'Write a short complaint email about a delayed flight and what you want done about it.',
              goal: 'Write a clear complaint with a request',
              criteria: ['Explains what happened in the past tense', 'States what you want', 'Uses a formal opening and closing'],
              minWords: 50,
              cefr: 'A2',
            }),
          ],
        }),
      ],
    }),

    unit({
      slug: 'es-a2-u4',
      title: 'Health',
      objective: 'Describe symptoms and understand simple medical advice.',
      theme: 'health',
      cefr: 'A2',
      realWorldTask: 'Describe a symptom at a pharmacy or clinic and understand the advice.',
      lessons: [
        lesson({
          slug: 'es-a2-u4-l1',
          title: 'It Hurts',
          objective: 'Use doler to describe pain.',
          canDo: 'I can say what hurts.',
          cefr: 'A2',
          minutes: 9,
          vocabulary: ['doler', 'cabeza', 'estomago'],
          grammar: ['es-gustar'],
          activities: [
            mcq({
              question: 'Why is it "me duele la cabeza" and not "duelo mi cabeza"?',
              options: [
                'Doler works like gustar: the body part is the subject',
                'It is an irregular exception',
                'Both are correct',
              ],
              answer: 'Doler works like gustar: the body part is the subject',
              why: 'Literally "the head hurts me". The person is an indirect object.',
              tags: ['grammar:es-gustar', 'vocab:doler'],
            }),
            fillBlank({
              template: 'Me {{blank}} los pies.',
              answers: ['duelen'],
              wordBank: ['duelen', 'duele', 'duelo'],
              why: 'Plural body part, so the verb is plural.',
              tags: ['vocab:doler'],
            }),
            correctGrammar({
              incorrect: 'Yo duelo mi cabeza.',
              correct: 'Me duele la cabeza.',
              why: 'Doler follows the gustar pattern, and Spanish uses the definite article with body parts, not a possessive.',
              topic: 'es-gustar',
            }),
            wordMatch({
              instruction: 'Match each body part.',
              pairs: [
                ['la cabeza', 'head'],
                ['el estómago', 'stomach'],
                ['la garganta', 'throat'],
              ],
              tags: ['vocab:cabeza', 'vocab:estomago'],
            }),
            speak({ target: 'Me duele la cabeza desde ayer' }),
            reviewChallenge({ count: 7 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u4-l2',
          title: 'At the Doctor',
          objective: 'Answer a doctor\'s questions.',
          canDo: 'I can describe a symptom and how long I have had it.',
          cefr: 'A2',
          minutes: 10,
          vocabulary: ['cita', 'receta', 'farmacia'],
          activities: [
            listen({
              audio: 'es/a2/u4/doctor',
              instruction: 'Listen to the consultation.',
              question: 'How long has the patient had the headache?',
              options: ['Since yesterday', 'For a week', 'Since this morning'],
              answer: 'Since yesterday',
              transcript: '— ¿Qué le pasa? — Me duele la cabeza desde ayer y no dormí bien. — ¿Tiene fiebre? — No, creo que no.',
              speed: 'normal',
              why: '"Desde ayer" — since yesterday.',
            }),
            fillBlank({
              template: 'Me duele el estómago {{blank}} el lunes.',
              answers: ['desde'],
              wordBank: ['desde', 'hace', 'para'],
              why: '"Desde" plus a point in time; "hace" plus a length of time ("hace tres días").',
            }),
            translate({
              source: 'I have had a sore throat for three days.',
              answer: 'Me duele la garganta desde hace tres días.',
              alternatives: ['Hace tres días que me duele la garganta'],
              why: '"Desde hace" combines the starting point with the duration.',
              cefr: 'A2',
            }),
            speakResponse({
              situation: 'A doctor asks what is wrong.',
              question: 'Cuénteme, ¿qué le pasa?',
              goal: 'Describe a symptom and how long it has lasted',
              criteria: ['Uses doler correctly', 'Gives a duration', 'Answers a follow-up question'],
              cefr: 'A2',
              mustInclude: ['duele'],
            }),
            reviewChallenge({ count: 7 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u4-l3',
          title: 'At the Pharmacy',
          objective: 'Ask for medicine and understand instructions.',
          canDo: 'I can ask for something at a pharmacy and understand the dosage.',
          cefr: 'A2',
          minutes: 9,
          activities: [
            translate({
              source: 'Do you have something for a headache?',
              answer: '¿Tiene algo para el dolor de cabeza?',
              alternatives: ['¿Tienen algo para el dolor de cabeza?'],
              why: '"Para" marks purpose; "dolor de cabeza" is the noun form of the pain.',
              cefr: 'A2',
              tags: ['grammar:es-por-para'],
            }),
            mcq({
              question: '"Tome una pastilla cada ocho horas." What does this mean?',
              options: ['One tablet every eight hours', 'Eight tablets a day', 'One tablet at eight'],
              answer: 'One tablet every eight hours',
              why: '"Cada" means every, and this is the standard dosage phrasing.',
            }),
            mcq({
              question: 'What is a "receta" in a pharmacy?',
              options: ['A prescription', 'A recipe', 'A receipt'],
              answer: 'A prescription',
              why: 'Receta means both prescription and recipe — the context decides. It is never a receipt, which is "recibo".',
              tags: ['vocab:receta'],
            }),
            converse({
              scenario: 'es-doctor-appointment',
              goals: ['Describe your symptom', 'Say how long it has lasted', 'Understand the advice given'],
              minTurns: 5,
              cefr: 'A2',
            }),
            reviewChallenge({ count: 7 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u4-l4',
          title: 'Unit 4 Review',
          objective: 'Consolidate health language.',
          canDo: 'I can get help when I am unwell.',
          cefr: 'A2',
          minutes: 10,
          isReview: true,
          vocabulary: ['devolver', 'tallar'],
          activities: [
            timedChallenge({
              instruction: 'Translate as many as you can.',
              items: [
                ['my head hurts', 'me duele la cabeza'],
                ['since yesterday', 'desde ayer'],
                ['the pharmacy', 'la farmacia'],
                ['a prescription', 'una receta'],
                ['an appointment', 'una cita'],
              ],
              seconds: 90,
            }),
            correctGrammar({
              incorrect: 'Mi estómago duele.',
              correct: 'Me duele el estómago.',
              why: 'Doler needs the indirect object pronoun, and Spanish uses the article with body parts.',
              topic: 'es-gustar',
            }),
            realWorldTask({
              situation: 'You feel unwell while travelling and go to a pharmacy.',
              goals: ['Describe the symptom', 'Say how long it has lasted', 'Ask for something for it', 'Confirm the dosage'],
              cefr: 'A2',
            }),
          ],
        }),
      ],
    }),

    unit({
      slug: 'es-a2-u5',
      title: 'Making and Changing Plans',
      objective: 'Arrange, decline and rearrange plans with people.',
      theme: 'relationships',
      cefr: 'A2',
      realWorldTask: 'Arrange to meet someone, then message them to move it, giving a reason.',
      lessons: [
        lesson({
          slug: 'es-a2-u5-l1',
          title: 'Shall We Meet?',
          objective: 'Propose a plan.',
          canDo: 'I can suggest a plan and a time.',
          cefr: 'A2',
          minutes: 9,
          vocabulary: ['quedar'],
          activities: [
            listen({
              audio: 'es/a2/u5/appointment',
              instruction: 'Listen to the two friends arranging to meet.',
              question: 'Which day do they agree on?',
              options: ['Friday', 'Thursday', 'Saturday'],
              answer: 'Friday',
              transcript: '— ¿Quedamos el jueves a las siete? — El jueves no puedo. ¿Te va bien el viernes? — Sí, perfecto.',
              speed: 'normal',
              why: 'Thursday is refused and Friday is agreed.',
            }),
            mcq({
              question: 'What does "quedar" mean here?',
              options: ['To arrange to meet', 'To stay', 'To remain'],
              answer: 'To arrange to meet',
              why: 'Quedar has several meanings; with a time it means to arrange a meeting.',
              tags: ['vocab:quedar'],
            }),
            buildSentence({
              target: '¿Te va bien el viernes por la tarde?',
              tokens: ['tarde?', '¿Te', 'el', 'bien', 'viernes', 'va', 'por', 'la'],
              instruction: 'Ask if Friday afternoon suits them.',
              why: '"¿Te va bien…?" is the natural way to check a time suits someone.',
              cefr: 'A2',
            }),
            speak({ target: '¿Quedamos el viernes a las siete?' }),
            reviewChallenge({ count: 7 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u5-l2',
          title: 'Saying No Politely',
          objective: 'Decline and offer an alternative.',
          canDo: 'I can decline a plan politely and suggest another.',
          cefr: 'A2',
          minutes: 9,
          activities: [
            mcq({
              question: 'Which is the most natural polite refusal?',
              options: [
                'Lo siento, el jueves no puedo. ¿Qué tal el viernes?',
                'No.',
                'No quiero.',
              ],
              answer: 'Lo siento, el jueves no puedo. ¿Qué tal el viernes?',
              why: 'Apologise, give a reason, offer an alternative — the same structure works in almost any language.',
            }),
            fillBlank({
              template: 'Lo siento, ese día no {{blank}}. Tengo una cita.',
              answers: ['puedo'],
              wordBank: ['puedo', 'quiero', 'voy'],
              why: '"No puedo" (I can\'t) is softer than "no quiero" (I don\'t want to).',
            }),
            translate({
              source: 'Sorry, I can\'t on Thursday. How about Saturday?',
              answer: 'Lo siento, el jueves no puedo. ¿Qué tal el sábado?',
              alternatives: ['Lo siento, no puedo el jueves. ¿Y el sábado?'],
              why: 'The apology, the refusal and the counter-offer in one move.',
              cefr: 'A2',
            }),
            speakResponse({
              situation: 'A colleague suggests a meeting when you are busy.',
              question: '¿Quedamos el martes a las diez?',
              goal: 'Decline politely and propose another time',
              criteria: ['Apologises or softens the refusal', 'Gives a reason', 'Proposes a specific alternative'],
              cefr: 'A2',
            }),
            reviewChallenge({ count: 7 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u5-l3',
          title: 'Changing a Plan',
          objective: 'Move an arrangement you have already made.',
          canDo: 'I can move a plan and apologise for the change.',
          cefr: 'A2',
          minutes: 9,
          grammar: ['es-future'],
          activities: [
            mcq({
              question: 'Which expresses a plan most naturally in everyday Spanish?',
              options: ['Voy a llegar tarde.', 'Llegaré tarde.', 'Llego tarde ayer.'],
              answer: 'Voy a llegar tarde.',
              why: '"Ir a + infinitive" is the everyday future; the simple future is more formal or predictive.',
              tags: ['grammar:es-future'],
            }),
            correctGrammar({
              incorrect: 'Voy llegar tarde.',
              correct: 'Voy a llegar tarde.',
              why: 'The construction needs "a" between ir and the infinitive.',
              topic: 'es-future',
            }),
            write({
              task: 'Write a message moving a dinner from Thursday to Saturday, with an apology and a reason.',
              goal: 'Write a message that changes a plan',
              criteria: ['Apologises', 'Gives a reason', 'Proposes a specific new time'],
              minWords: 30,
              cefr: 'A2',
            }),
            speak({ target: 'Lo siento, voy a llegar unos minutos tarde' }),
            reviewChallenge({ count: 7 }),
          ],
        }),

        lesson({
          slug: 'es-a2-u5-l4',
          title: 'A2 Checkpoint',
          objective: 'Assess the level across all six skills.',
          canDo: 'I can handle routine everyday situations, including ones that go wrong.',
          cefr: 'A2',
          minutes: 20,
          isCheckpoint: true,
          activities: [
            listen({
              audio: 'es/a2/u2/weekend-past',
              instruction: 'Listening at natural speed.',
              question: 'Who did they go with?',
              options: ['Their family', 'Alone', 'Colleagues'],
              answer: 'Their family',
              transcript: '— ¿Qué hiciste el fin de semana? — Fui a la playa con mi familia. Comimos en un restaurante y volvimos el domingo por la noche.',
              speed: 'natural',
              why: '"Con mi familia" — with my family.',
            }),
            storyCompletion({
              story:
                'Reading: El año pasado {{blank}} a México. {{blank}} en un hotel pequeño cerca del centro. Todos los días {{blank}} en restaurantes locales y {{blank}} mucho español.',
              answers: ['fui', 'Estuve', 'comía', 'practiqué'],
              wordBank: ['fui', 'Estuve', 'comía', 'practiqué', 'voy', 'como'],
              why: 'Single events in the preterite, the repeated daily habit in the imperfect.',
              cefr: 'A2',
            }),
            timedChallenge({
              instruction: 'Vocabulary and grammar.',
              items: [
                ['I went', 'fui'],
                ['the delay', 'el retraso'],
                ['my head hurts', 'me duele la cabeza'],
                ['shall we meet?', '¿quedamos?'],
                ['what does it contain?', '¿qué lleva?'],
                ['I am going to arrive late', 'voy a llegar tarde'],
              ],
              seconds: 120,
            }),
            correctGrammar({
              incorrect: 'Ayer voy al médico porque mi cabeza duele.',
              correct: 'Ayer fui al médico porque me dolía la cabeza.',
              why: 'Three fixes: "ayer" needs the preterite, doler takes an indirect object pronoun, and the ongoing pain is background so it takes the imperfect.',
              topic: 'es-preterite',
            }),
            speakResponse({
              situation: 'Speaking: your tutor asks about a trip that did not go to plan.',
              question: 'Cuéntame sobre un viaje en el que algo salió mal. ¿Qué pasó?',
              goal: 'Narrate a past problem and how it was resolved',
              criteria: ['Uses the preterite for events', 'Uses the imperfect for background', 'Explains the resolution'],
              cefr: 'A2',
            }),
            write({
              task:
                'Writing: write an email to a hotel explaining that your flight was delayed, that you will arrive after midnight, and asking them to hold the room.',
              goal: 'Write a clear message combining a past problem and a future arrangement',
              criteria: [
                'Explains the problem in the past tense',
                'States the new arrival time',
                'Makes a polite request',
                'Uses a formal opening and closing',
              ],
              minWords: 60,
              cefr: 'A2',
            }),
            realWorldTask({
              situation:
                'You arrive at a restaurant with a reservation that has been given away. Sort it out and end up with a table or a plan.',
              goals: [
                'Explain that you have a reservation',
                'Say when you made it',
                'Ask what they can do',
                'Agree on an outcome',
              ],
              constraints: ['Stay polite', 'Spanish only'],
              cefr: 'A2',
            }),
          ],
        }),
      ],
    }),
  ],
});
