import {
  audioChoice,
  buildSentence,
  categorize,
  converse,
  course,
  dialogueCompletion,
  fillBlank,
  hints,
  imageMatch,
  listen,
  lesson,
  mcq,
  realWorldTask,
  reviewChallenge,
  speak,
  spelling,
  tapTranslation,
  timedChallenge,
  unit,
  wordMatch,
} from '../../dsl/builders';

/**
 * Spanish Pre-A1 — for someone who genuinely knows nothing.
 *
 * The goal is recognition and reproduction: sounds, greetings, courtesy,
 * numbers and the handful of phrases that let a learner survive a lesson
 * ("no entiendo", "repite, por favor"). Grammar is deliberately absent.
 */
export const ES_PRE_A1 = course({
  slug: 'es-pre-a1-foundations',
  title: 'First Steps in Spanish',
  description:
    'Before grammar: the sounds of Spanish, greetings, courtesy, numbers and the phrases that keep a conversation going when you understand almost nothing.',
  cefr: 'PRE_A1',
  units: [
    unit({
      slug: 'es-pre-a1-u1',
      title: 'Hello and Goodbye',
      objective: 'Greet someone and say goodbye at any time of day.',
      theme: 'greetings',
      cefr: 'PRE_A1',
      realWorldTask: 'Greet a Spanish speaker and say goodbye without switching to English.',
      lessons: [
        lesson({
          slug: 'es-pre-a1-u1-l1',
          title: 'Hola and Adiós',
          objective: 'Recognise and say the two most useful words in Spanish.',
          canDo: 'I can say hello and goodbye in Spanish.',
          cefr: 'PRE_A1',
          minutes: 5,
          vocabulary: ['hola', 'adios'],
          culture: ['es-greeting-customs'],
          activities: [
            audioChoice({
              audio: 'es/vocab/hola',
              instruction: 'Listen. Which word did you hear?',
              options: ['hola', 'adiós'],
              answer: 'hola',
              tags: ['vocab:hola'],
            }),
            tapTranslation({
              source: 'hola',
              options: ['hello', 'goodbye', 'thank you'],
              answer: 'hello',
              why: '"Hola" is the everyday greeting, used at any time of day.',
              tags: ['vocab:hola'],
            }),
            tapTranslation({
              source: 'adiós',
              options: ['goodbye', 'hello', 'please'],
              answer: 'goodbye',
              why: '"Adiós" ends a conversation. For "see you later", Spanish uses "hasta luego".',
              tags: ['vocab:adios'],
            }),
            speak({
              target: 'Hola',
              audio: 'es/vocab/hola',
              phonetic: 'OH-lah',
              focusPhonemes: ['h-silent'],
              why: 'The h is always silent in Spanish: "hola" starts with the o sound.',
              tags: ['phoneme:h-silent'],
            }),
            speak({
              target: 'Adiós',
              audio: 'es/vocab/adios',
              phonetic: 'ah-DYOHS',
              focusPhonemes: ['d'],
            }),
            wordMatch({
              instruction: 'Match each Spanish word to its meaning.',
              pairs: [
                ['hola', 'hello'],
                ['adiós', 'goodbye'],
              ],
              tags: ['vocab:hola', 'vocab:adios'],
            }),
            listen({
              audio: 'es/pre-a1/u1/greetings',
              instruction: 'Listen to the short exchange.',
              question: 'How does the second person reply to "¡Hola!"?',
              options: ['Hola, buenos días.', 'Adiós.', 'Gracias.'],
              answer: 'Hola, buenos días.',
              transcript: '— ¡Hola! — Hola, buenos días. — Adiós. — Hasta luego.',
              speed: 'slow',
              why: 'A greeting is normally returned before anything else is said.',
            }),
            reviewChallenge({ instruction: 'Quick check on today\'s words.', count: 4 }),
          ],
        }),

        lesson({
          slug: 'es-pre-a1-u1-l2',
          title: 'Good Morning, Good Evening',
          objective: 'Greet someone appropriately for the time of day.',
          canDo: 'I can greet someone in the morning, afternoon or evening.',
          cefr: 'PRE_A1',
          minutes: 6,
          vocabulary: ['buenos-dias', 'buenas-tardes', 'buenas-noches'],
          activities: [
            wordMatch({
              instruction: 'Match the greeting to the time of day.',
              pairs: [
                ['buenos días', 'good morning'],
                ['buenas tardes', 'good afternoon'],
                ['buenas noches', 'good evening / good night'],
              ],
              tags: ['vocab:buenos-dias', 'vocab:buenas-tardes', 'vocab:buenas-noches'],
            }),
            mcq({
              question: 'It is 9 in the morning. What do you say?',
              options: ['Buenos días', 'Buenas tardes', 'Buenas noches'],
              answer: 'Buenos días',
              why: '"Buenos días" is used until roughly midday.',
              tags: ['vocab:buenos-dias'],
            }),
            mcq({
              question: 'It is 5 in the afternoon. What do you say?',
              options: ['Buenas tardes', 'Buenos días', 'Buenas noches'],
              answer: 'Buenas tardes',
              why: '"Buenas tardes" covers the afternoon and early evening — in Spain, until around 8 or 9pm.',
              tags: ['vocab:buenas-tardes'],
            }),
            mcq({
              question: 'Which greeting also works as "good night" when you leave?',
              options: ['Buenas noches', 'Buenos días', 'Hola'],
              answer: 'Buenas noches',
              why: '"Buenas noches" is both a greeting and a farewell at night.',
              tags: ['vocab:buenas-noches'],
            }),
            speak({ target: 'Buenos días', audio: 'es/vocab/buenos-dias', phonetic: 'BWEH-nohs DEE-ahs' }),
            speak({ target: 'Buenas tardes', audio: 'es/vocab/buenas-tardes', phonetic: 'BWEH-nahs TAR-dehs' }),
            categorize({
              instruction: 'Sort each greeting by when you use it.',
              categories: ['morning', 'afternoon', 'night'],
              mapping: {
                'buenos días': 'morning',
                'buenas tardes': 'afternoon',
                'buenas noches': 'night',
              },
              why: 'Spanish greetings change with the time of day, unlike a single all-purpose "hi".',
            }),
            reviewChallenge({ count: 5 }),
          ],
        }),

        lesson({
          slug: 'es-pre-a1-u1-l3',
          title: 'Please and Thank You',
          objective: 'Use the courtesy words that make every interaction go better.',
          canDo: 'I can say please, thank you, you\'re welcome and sorry.',
          cefr: 'PRE_A1',
          minutes: 6,
          vocabulary: ['gracias', 'por-favor', 'de-nada', 'perdon'],
          culture: ['es-greeting-customs'],
          activities: [
            wordMatch({
              instruction: 'Match each courtesy word to its meaning.',
              pairs: [
                ['gracias', 'thank you'],
                ['por favor', 'please'],
                ['de nada', "you're welcome"],
                ['perdón', 'sorry / excuse me'],
              ],
              tags: ['vocab:gracias', 'vocab:por-favor', 'vocab:de-nada', 'vocab:perdon'],
            }),
            mcq({
              question: 'Someone says "gracias". What do you reply?',
              options: ['De nada', 'Por favor', 'Perdón'],
              answer: 'De nada',
              why: '"De nada" literally means "of nothing" and is the standard reply to thanks.',
              tags: ['vocab:de-nada'],
            }),
            mcq({
              question: 'You need to get past someone in a narrow aisle. What do you say?',
              options: ['Perdón', 'Gracias', 'De nada'],
              answer: 'Perdón',
              why: '"Perdón" works both as an apology and as "excuse me".',
              tags: ['vocab:perdon'],
            }),
            listen({
              audio: 'es/pre-a1/u1/courtesy',
              instruction: 'Listen to four short exchanges.',
              question: 'Which word means "please"?',
              options: ['por favor', 'gracias', 'perdón'],
              answer: 'por favor',
              transcript: '— Gracias. — De nada. — Por favor. — Perdón.',
              speed: 'slow',
              why: '"Por favor" is added to a request, usually at the end.',
            }),
            speak({ target: 'Gracias', audio: 'es/vocab/gracias', phonetic: 'GRAH-syahs', focusPhonemes: ['c-soft'] }),
            speak({ target: 'Por favor', audio: 'es/vocab/por-favor', phonetic: 'por fah-BOR', focusPhonemes: ['r'] }),
            dialogueCompletion({
              lines: [
                { speaker: 'You', text: 'Un café, ___.' },
                { speaker: 'Barista', text: 'Aquí tiene.' },
                { speaker: 'You', text: 'Gracias.' },
              ],
              options: ['por favor', 'de nada', 'adiós'],
              answer: 'por favor',
              why: 'A request is softened with "por favor", usually at the end of the sentence.',
              tags: ['vocab:por-favor'],
            }),
            reviewChallenge({ count: 6 }),
          ],
        }),

        lesson({
          slug: 'es-pre-a1-u1-l4',
          title: 'Yes, No and Review',
          objective: 'Answer simple yes/no questions and review the unit.',
          canDo: 'I can answer yes or no, and use the greetings I have learned.',
          cefr: 'PRE_A1',
          minutes: 7,
          isReview: true,
          vocabulary: ['si', 'no'],
          activities: [
            audioChoice({
              audio: 'es/vocab/si',
              instruction: 'Listen. Did you hear "yes" or "no"?',
              options: ['sí', 'no'],
              answer: 'sí',
              tags: ['vocab:si'],
            }),
            mcq({
              question: 'Which written form means "yes"?',
              options: ['sí', 'si', 'se'],
              answer: 'sí',
              why: 'With the accent, "sí" means yes; without it, "si" means "if".',
              tags: ['vocab:si', 'accent'],
            }),
            timedChallenge({
              instruction: 'Translate as many as you can before time runs out.',
              items: [
                ['hello', 'hola'],
                ['goodbye', 'adiós'],
                ['thank you', 'gracias'],
                ['please', 'por favor'],
                ['good morning', 'buenos días'],
                ['yes', 'sí'],
              ],
              seconds: 60,
            }),
            converse({
              scenario: 'es-meeting-a-classmate',
              goals: ['Greet the other person', 'Say goodbye politely'],
              minTurns: 3,
              hints: hints(
                'Start with the word you use at any time of day.',
                'Try "hola" — then listen for what they say back.',
              ),
            }),
            realWorldTask({
              situation:
                'You walk into a small shop in a Spanish-speaking neighbourhood. Greet the shopkeeper, and say goodbye as you leave.',
              goals: ['Greet appropriately for the time of day', 'Thank them', 'Say goodbye'],
              constraints: ['Use only Spanish'],
            }),
          ],
        }),
      ],
    }),

    unit({
      slug: 'es-pre-a1-u2',
      title: 'The Sounds of Spanish',
      objective: 'Read Spanish aloud with the right sounds, including the ones English does not have.',
      theme: 'pronunciation',
      cefr: 'PRE_A1',
      realWorldTask: 'Read a Spanish street sign or menu item aloud so a Spanish speaker understands it.',
      lessons: [
        lesson({
          slug: 'es-pre-a1-u2-l1',
          title: 'Five Vowels, Always the Same',
          objective: 'Pronounce the five Spanish vowels consistently.',
          canDo: 'I can pronounce Spanish vowels the same way every time.',
          cefr: 'PRE_A1',
          minutes: 6,
          activities: [
            listen({
              audio: 'es/pre-a1/u2/alphabet-vowels',
              instruction: 'Listen to the five Spanish vowels.',
              question: 'How many vowel sounds does Spanish have?',
              options: ['Five', 'Twelve', 'Twenty'],
              answer: 'Five',
              transcript: 'a, e, i, o, u',
              speed: 'slow',
              why: 'Spanish has exactly five vowel sounds, and each letter always makes the same one — unlike English, where "a" varies in cat, car and cake.',
            }),
            speak({ target: 'a, e, i, o, u', phonetic: 'ah, eh, ee, oh, oo', focusPhonemes: ['a', 'e', 'i', 'o', 'u'] }),
            mcq({
              question: 'In Spanish, how does the letter "e" sound in "mesa" and in "café"?',
              options: ['The same in both', 'Different in each', 'It is silent in one'],
              answer: 'The same in both',
              why: 'Spanish vowels do not change with position: "e" is always "eh".',
              tags: ['phoneme:e'],
            }),
            speak({ target: 'mesa', phonetic: 'MEH-sah', focusPhonemes: ['e', 'a'] }),
            spelling({
              instruction: 'You hear "casa". Type it.',
              answer: 'casa',
              letters: ['c', 'a', 's', 'a'],
              why: 'Spanish spelling is highly regular: what you hear is what you write.',
              tags: ['vocab:casa'],
            }),
            reviewChallenge({ count: 4 }),
          ],
        }),

        lesson({
          slug: 'es-pre-a1-u2-l2',
          title: 'The Rolled R and the Silent H',
          objective: 'Handle the two sounds English speakers find hardest.',
          canDo: 'I can attempt the rolled r and I know the h is silent.',
          cefr: 'PRE_A1',
          minutes: 7,
          activities: [
            listen({
              audio: 'es/pre-a1/u2/rr-sound',
              instruction: 'Listen to four words with r sounds.',
              question: 'Which word has the strong rolled r?',
              options: ['perro', 'arroz', 'both perro and arroz'],
              answer: 'both perro and arroz',
              transcript: 'perro, carro, arroz, correr',
              speed: 'slow',
              why: 'A double rr, and a single r at the start of a word, are both rolled.',
              tags: ['phoneme:rr'],
            }),
            speak({ target: 'perro', phonetic: 'PEH-rroh', focusPhonemes: ['rr'], why: 'The rolled rr distinguishes "perro" (dog) from "pero" (but).' }),
            mcq({
              question: 'How is the h pronounced in "hola"?',
              options: ['It is silent', 'Like English h', 'Like a j'],
              answer: 'It is silent',
              why: 'The Spanish h is never pronounced: "hola" begins with the o sound.',
              tags: ['phoneme:h-silent'],
            }),
            mcq({
              question: 'Which pair sounds different in Spanish?',
              options: ['perro / pero', 'hola / ola', 'hasta / asta'],
              answer: 'perro / pero',
              why: 'Because h is silent, "hola" and "ola" sound identical — but the rolled rr in "perro" is a real difference.',
              tags: ['phoneme:rr', 'phoneme:h-silent'],
            }),
            speak({ target: 'Hola, ¿qué tal?', phonetic: 'OH-lah, keh tahl', focusPhonemes: ['h-silent'] }),
            reviewChallenge({ count: 4 }),
          ],
        }),

        lesson({
          slug: 'es-pre-a1-u2-l3',
          title: 'Written Accents',
          objective: 'Understand what the accent mark does.',
          canDo: 'I know that an accent shows which syllable is stressed, and can change meaning.',
          cefr: 'PRE_A1',
          minutes: 6,
          isReview: true,
          activities: [
            mcq({
              question: 'What does the accent in "adiós" tell you?',
              options: ['Stress the last syllable', 'The word is a question', 'The o is silent'],
              answer: 'Stress the last syllable',
              why: 'A written accent marks the stressed syllable: a-DIÓS.',
              tags: ['accent'],
            }),
            mcq({
              question: 'Which pair changes meaning because of the accent?',
              options: ['sí / si', 'casa / casa', 'mesa / mesa'],
              answer: 'sí / si',
              why: '"Sí" is yes; "si" is if. The accent is not decoration.',
              tags: ['accent'],
            }),
            spelling({
              instruction: 'Write "goodbye" in Spanish, with the accent.',
              answer: 'adiós',
              why: 'Without the accent the stress falls in the wrong place.',
              tags: ['vocab:adios', 'accent'],
            }),
            speak({ target: 'adiós', audio: 'es/vocab/adios', phonetic: 'ah-DYOHS' }),
            reviewChallenge({ count: 5 }),
          ],
        }),
      ],
    }),

    unit({
      slug: 'es-pre-a1-u3',
      title: 'Numbers One to Ten',
      objective: 'Understand and say the numbers you need for prices, times and quantities.',
      theme: 'numbers',
      cefr: 'PRE_A1',
      realWorldTask: 'Understand a price said aloud and repeat it back to confirm.',
      lessons: [
        lesson({
          slug: 'es-pre-a1-u3-l1',
          title: 'One to Five',
          objective: 'Recognise and say the numbers one to five.',
          canDo: 'I can count to five in Spanish.',
          cefr: 'PRE_A1',
          minutes: 6,
          vocabulary: ['uno', 'dos', 'tres', 'cuatro', 'cinco'],
          activities: [
            wordMatch({
              instruction: 'Match the number to the digit.',
              pairs: [
                ['uno', '1'],
                ['dos', '2'],
                ['tres', '3'],
                ['cuatro', '4'],
                ['cinco', '5'],
              ],
              tags: ['vocab:uno', 'vocab:dos', 'vocab:tres'],
            }),
            audioChoice({
              audio: 'es/vocab/tres',
              instruction: 'Listen. Which number is it?',
              options: ['tres', 'dos', 'seis'],
              answer: 'tres',
              tags: ['vocab:tres'],
            }),
            mcq({
              question: 'Which number comes after "cuatro"?',
              options: ['cinco', 'tres', 'dos'],
              answer: 'cinco',
              why: 'uno, dos, tres, cuatro, cinco.',
              tags: ['vocab:cinco'],
            }),
            speak({ target: 'uno, dos, tres, cuatro, cinco', audio: 'es/vocab/uno' }),
            timedChallenge({
              instruction: 'Say the Spanish for each number before time runs out.',
              items: [
                ['1', 'uno'],
                ['2', 'dos'],
                ['3', 'tres'],
                ['4', 'cuatro'],
                ['5', 'cinco'],
              ],
              seconds: 45,
            }),
            reviewChallenge({ count: 5 }),
          ],
        }),

        lesson({
          slug: 'es-pre-a1-u3-l2',
          title: 'Six to Ten',
          objective: 'Complete the first ten numbers.',
          canDo: 'I can count to ten and understand a number said to me.',
          cefr: 'PRE_A1',
          minutes: 6,
          vocabulary: ['seis', 'siete', 'ocho', 'nueve', 'diez'],
          activities: [
            wordMatch({
              instruction: 'Match the number to the digit.',
              pairs: [
                ['seis', '6'],
                ['siete', '7'],
                ['ocho', '8'],
                ['nueve', '9'],
                ['diez', '10'],
              ],
              tags: ['vocab:seis', 'vocab:siete', 'vocab:ocho'],
            }),
            listen({
              audio: 'es/pre-a1/u3/numbers-1-10',
              instruction: 'Listen to the numbers one to ten.',
              question: 'Which number comes immediately before "diez"?',
              options: ['nueve', 'ocho', 'siete'],
              answer: 'nueve',
              transcript: 'uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez',
              speed: 'slow',
              why: 'The sequence ends nueve, diez.',
            }),
            mcq({
              question: 'You hear "ocho euros". How much is it?',
              options: ['8 euros', '4 euros', '11 euros'],
              answer: '8 euros',
              why: '"Ocho" is eight.',
              tags: ['vocab:ocho'],
            }),
            speak({ target: 'seis, siete, ocho, nueve, diez', audio: 'es/vocab/seis' }),
            spelling({
              instruction: 'Write the Spanish for 10.',
              answer: 'diez',
              why: 'Ten is "diez" — one syllable, with the z pronounced as s in Latin America.',
              tags: ['vocab:diez'],
            }),
            reviewChallenge({ count: 6 }),
          ],
        }),

        lesson({
          slug: 'es-pre-a1-u3-l3',
          title: 'Numbers in Use',
          objective: 'Use numbers to understand a price and a quantity.',
          canDo: 'I can understand a simple price and ask for a quantity.',
          cefr: 'PRE_A1',
          minutes: 7,
          isReview: true,
          vocabulary: ['agua', 'pan'],
          activities: [
            imageMatch({
              instruction: 'Which picture is "el agua"?',
              word: 'el agua',
              options: [
                { text: 'water', image: 'es/img/agua' },
                { text: 'bread', image: 'es/img/pan' },
                { text: 'book', image: 'es/img/libro' },
              ],
              answer: 'water',
              tags: ['vocab:agua'],
            }),
            buildSentence({
              target: 'dos panes por favor',
              tokens: ['por', 'dos', 'favor', 'panes'],
              instruction: 'Ask for two breads, politely.',
              why: 'The quantity comes before the noun, and "por favor" closes the request.',
              tags: ['vocab:pan', 'vocab:por-favor'],
            }),
            mcq({
              question: 'The shopkeeper says "son cinco euros". What do you owe?',
              options: ['5 euros', '15 euros', '9 euros'],
              answer: '5 euros',
              why: '"Son cinco euros" — it comes to five euros.',
              tags: ['vocab:cinco'],
            }),
            timedChallenge({
              instruction: 'All ten numbers, as fast as you can.',
              items: [
                ['1', 'uno'], ['2', 'dos'], ['3', 'tres'], ['4', 'cuatro'], ['5', 'cinco'],
                ['6', 'seis'], ['7', 'siete'], ['8', 'ocho'], ['9', 'nueve'], ['10', 'diez'],
              ],
              seconds: 75,
            }),
            realWorldTask({
              situation: 'You are buying two bottles of water. Ask for them and understand the price.',
              goals: ['Ask for two waters politely', 'Understand the price you are told'],
            }),
          ],
        }),
      ],
    }),

    unit({
      slug: 'es-pre-a1-u4',
      title: 'Surviving a Conversation',
      objective: 'Keep a conversation going when you understand almost nothing.',
      theme: 'classroom language',
      cefr: 'PRE_A1',
      realWorldTask: 'Ask a Spanish speaker to repeat something, and ask how to say a word you do not know.',
      lessons: [
        lesson({
          slug: 'es-pre-a1-u4-l1',
          title: 'I Don\'t Understand',
          objective: 'Say that you have not understood, and ask for a repeat.',
          canDo: 'I can say I do not understand and ask someone to repeat.',
          cefr: 'PRE_A1',
          minutes: 6,
          vocabulary: ['no-entiendo', 'repite-por-favor'],
          activities: [
            tapTranslation({
              source: 'No entiendo.',
              options: ["I don't understand.", "I don't know.", "I don't speak."],
              answer: "I don't understand.",
              why: 'This is the single most useful sentence for a beginner.',
              tags: ['vocab:no-entiendo'],
            }),
            mcq({
              question: 'Someone speaks too fast. What do you say?',
              options: ['Repite, por favor.', 'De nada.', 'Buenas noches.'],
              answer: 'Repite, por favor.',
              why: 'Asking for a repeat keeps the conversation alive instead of ending it.',
              tags: ['vocab:repite-por-favor'],
            }),
            speak({ target: 'No entiendo', phonetic: 'noh en-TYEN-doh' }),
            speak({ target: 'Repite, por favor', phonetic: 'rreh-PEE-teh por fah-BOR', focusPhonemes: ['rr'] }),
            listen({
              audio: 'es/pre-a1/u4/classroom',
              instruction: 'Listen to the classroom exchange.',
              question: 'What does the learner ask for?',
              options: ['A repeat, and how to say a word', 'The bill', 'Directions'],
              answer: 'A repeat, and how to say a word',
              transcript: '— No entiendo. — Repite, por favor. — ¿Cómo se dice "book" en español? — Se dice "libro".',
              speed: 'slow',
              why: 'These two phrases together get you through almost any early conversation.',
            }),
            reviewChallenge({ count: 4 }),
          ],
        }),

        lesson({
          slug: 'es-pre-a1-u4-l2',
          title: 'How Do You Say…?',
          objective: 'Ask for a word you do not know.',
          canDo: 'I can ask how to say something in Spanish.',
          cefr: 'PRE_A1',
          minutes: 6,
          vocabulary: ['como-se-dice', 'libro'],
          activities: [
            tapTranslation({
              source: '¿Cómo se dice "water" en español?',
              options: ['How do you say "water" in Spanish?', 'What is water?', 'Where is the water?'],
              answer: 'How do you say "water" in Spanish?',
              why: 'This question turns any conversation into a lesson.',
              tags: ['vocab:como-se-dice'],
            }),
            fillBlank({
              template: '¿{{blank}} se dice "book" en español?',
              answers: ['cómo'],
              alternatives: [['como']],
              wordBank: ['cómo', 'dónde', 'qué'],
              why: '"Cómo" asks how. With the accent it is a question word; without it, "como" means "as" or "I eat".',
              tags: ['vocab:como-se-dice', 'accent'],
            }),
            imageMatch({
              instruction: 'Which picture is "el libro"?',
              word: 'el libro',
              options: [
                { text: 'book', image: 'es/img/libro' },
                { text: 'house', image: 'es/img/casa' },
                { text: 'bread', image: 'es/img/pan' },
              ],
              answer: 'book',
              tags: ['vocab:libro'],
            }),
            buildSentence({
              target: '¿Cómo se dice casa en inglés?',
              tokens: ['inglés?', '¿Cómo', 'se', 'casa', 'dice', 'en'],
              instruction: 'Ask how to say "casa" in English.',
              why: 'The question word opens the sentence; "en inglés" closes it.',
              tags: ['vocab:como-se-dice'],
            }),
            speak({ target: '¿Cómo se dice?', phonetic: 'KOH-moh seh DEE-seh' }),
            reviewChallenge({ count: 5 }),
          ],
        }),

        lesson({
          slug: 'es-pre-a1-u4-l3',
          title: 'Pre-A1 Checkpoint',
          objective: 'Check that everything from this level has stuck.',
          canDo: 'I can greet, thank, count to ten and keep a simple conversation going.',
          cefr: 'PRE_A1',
          minutes: 12,
          isCheckpoint: true,
          activities: [
            listen({
              audio: 'es/pre-a1/u1/greetings',
              instruction: 'Listen and answer.',
              question: 'What is the second speaker\'s first word?',
              options: ['Hola', 'Adiós', 'Gracias'],
              answer: 'Hola',
              transcript: '— ¡Hola! — Hola, buenos días. — Adiós. — Hasta luego.',
              speed: 'normal',
              why: 'At normal speed the greeting is still the first thing you hear.',
            }),
            mcq({
              question: 'It is 8pm and you are leaving a friend\'s house. What do you say?',
              options: ['Buenas noches', 'Buenos días', 'Buenas tardes'],
              answer: 'Buenas noches',
              why: '"Buenas noches" works both as an evening greeting and as a farewell.',
            }),
            timedChallenge({
              instruction: 'Translate as many as you can.',
              items: [
                ['thank you', 'gracias'],
                ['please', 'por favor'],
                ['I don\'t understand', 'no entiendo'],
                ['seven', 'siete'],
                ['water', 'agua'],
                ['hello', 'hola'],
              ],
              seconds: 90,
            }),
            buildSentence({
              target: 'Repite por favor',
              tokens: ['favor', 'Repite', 'por'],
              instruction: 'Ask someone to repeat.',
              why: 'The polite phrase follows the request.',
            }),
            speak({ target: 'Hola, buenos días. Gracias.', focusPhonemes: ['h-silent', 'd'] }),
            converse({
              scenario: 'es-meeting-a-classmate',
              goals: ['Greet the other person', 'Say you do not understand when they speak too fast', 'Say goodbye'],
              minTurns: 4,
            }),
            realWorldTask({
              situation:
                'A Spanish speaker greets you and asks something you do not catch. Keep the conversation going without switching to English.',
              goals: ['Greet them back', 'Say you did not understand', 'Ask them to repeat', 'Close politely'],
            }),
          ],
        }),
      ],
    }),
  ],
});
