import type { AuthoredScenario } from '../../dsl/types';

/**
 * AI conversation scenarios for Spanish.
 *
 * Each scenario names the character the model plays, what the learner is
 * trying to achieve, and the complications the model may introduce at higher
 * levels. Goals are checked by the evaluator, so the learner is judged on
 * whether they communicated, not on whether they hit a script.
 */
export const ES_SCENARIOS: AuthoredScenario[] = [
  {
    key: 'es-meeting-a-classmate',
    title: 'Meeting a classmate',
    setting: 'The first day of a language course. Another student sits down next to you.',
    partnerRole: 'A friendly fellow student, patient and slow-speaking',
    learnerRole: 'A new student',
    cefr: 'A1',
    goals: ['Greet the other person', 'Say your name and ask theirs', 'Say where you are from'],
    openingLine: 'Hola. ¿Cómo te llamas?',
    vocabulary: ['hola', 'me-llamo', 'como-te-llamas', 'soy-de', 'mucho-gusto'],
  },
  {
    key: 'es-cafe-order',
    title: 'Ordering in a café',
    setting: 'A small café in the morning. There is a short queue behind you.',
    partnerRole: 'A busy but polite barista',
    learnerRole: 'A customer',
    cefr: 'A1',
    goals: ['Greet the barista', 'Order a drink', 'Ask the price', 'Thank them and say goodbye'],
    openingLine: 'Buenos días. ¿Qué le pongo?',
    complications: ['The item the learner asks for has run out'],
    vocabulary: ['buenos-dias', 'quisiera', 'cafe', 'cuanto-cuesta', 'gracias'],
  },
  {
    key: 'es-asking-directions',
    title: 'Asking for directions',
    setting: 'You are lost in a city centre and stop a passer-by.',
    partnerRole: 'A helpful local in a hurry',
    learnerRole: 'A visitor',
    cefr: 'A1',
    goals: ['Politely get their attention', 'Ask where the station is', 'Confirm you understood'],
    openingLine: '¿Sí? ¿En qué te puedo ayudar?',
    complications: ['The passer-by gives directions quickly and the learner must ask them to repeat'],
    vocabulary: ['perdon', 'donde-esta', 'estacion', 'izquierda', 'derecha', 'recto'],
  },
  {
    key: 'es-restaurant-meal',
    title: 'Ordering a meal',
    setting: 'A restaurant at lunchtime. You have a table and the waiter approaches.',
    partnerRole: 'A waiter who suggests the daily specials',
    learnerRole: 'A diner',
    cefr: 'A2',
    goals: ['Order a starter and a main course', 'Ask what a dish contains', 'Ask for the bill'],
    openingLine: 'Buenas tardes. ¿Ya sabe qué va a pedir?',
    complications: ['The waiter recommends something the learner did not plan to order'],
    vocabulary: ['quisiera', 'pollo', 'arroz', 'ensalada', 'la-cuenta', 'probar'],
  },
  {
    key: 'es-market-shopping',
    title: 'Shopping at the market',
    setting: 'A busy market stall selling fruit and vegetables.',
    partnerRole: 'A market vendor who quotes prices quickly',
    learnerRole: 'A shopper',
    cefr: 'A2',
    goals: ['Ask for a quantity of something', 'Ask the price', 'Ask for something cheaper', 'Pay'],
    openingLine: '¡Buenas! ¿Qué le doy?',
    complications: ['The vendor quotes a price the learner must ask them to repeat'],
    vocabulary: ['cuanto-cuesta', 'caro', 'barato', 'fruta', 'dinero'],
  },
  {
    key: 'es-doctor-appointment',
    title: 'At the doctor',
    setting: 'A clinic. You have an appointment about a persistent headache.',
    partnerRole: 'A doctor asking diagnostic questions',
    learnerRole: 'A patient',
    cefr: 'A2',
    goals: ['Describe your symptom', 'Say how long it has lasted', 'Understand the advice given'],
    openingLine: 'Buenos días. Cuénteme, ¿qué le pasa?',
    vocabulary: ['doler', 'cabeza', 'estomago', 'farmacia', 'receta'],
  },
  {
    key: 'es-missed-flight',
    title: 'You missed your flight',
    setting: 'An airline desk at the airport. Your connection has already left.',
    partnerRole: 'An airline representative following policy but willing to help',
    learnerRole: 'A stranded traveller',
    cefr: 'B1',
    goals: [
      'Explain what happened',
      'Ask about the next available flight',
      'Ask who pays for the change',
      'Reach an agreed solution',
    ],
    openingLine: 'Buenas tardes. ¿En qué puedo ayudarle?',
    complications: [
      'The next flight is tomorrow',
      'The representative first says the change is not covered',
    ],
    vocabulary: ['perder', 'vuelo', 'retraso', 'equipaje', 'reserva'],
  },
  {
    key: 'es-job-interview',
    title: 'A job interview',
    setting: 'An interview for a role at a Spanish-speaking company.',
    partnerRole: 'A hiring manager who asks follow-up questions',
    learnerRole: 'A candidate',
    cefr: 'B2',
    goals: [
      'Introduce your professional background',
      'Explain a strength with a concrete example',
      'Ask an informed question about the role',
    ],
    openingLine: 'Gracias por venir. Cuénteme un poco sobre su experiencia.',
    complications: ['The manager challenges a claim and asks for evidence'],
    vocabulary: ['trabajo', 'oficina', 'ingeniero'],
  },
  {
    key: 'es-remote-work-debate',
    title: 'Arguing a position on remote work',
    setting: 'A discussion with a colleague who disagrees with you.',
    partnerRole: 'A colleague who argues the opposite position and interrupts',
    learnerRole: 'A participant in the discussion',
    cefr: 'B2',
    goals: ['State your position clearly', 'Support it with a reason', 'Respond to a counter-argument'],
    openingLine: 'No estoy de acuerdo. Creo que el trabajo remoto perjudica a los equipos jóvenes. ¿Tú qué opinas?',
    complications: ['The colleague interrupts mid-sentence', 'The colleague uses an idiom'],
  },
  {
    key: 'es-negotiate-contract',
    title: 'Negotiating a contract',
    setting: 'A meeting with a supplier about delivery terms and price.',
    partnerRole: 'A supplier who resists concessions and uses indirect language',
    learnerRole: 'A business negotiator',
    cefr: 'C1',
    goals: [
      'Open the negotiation appropriately for the register',
      'Make a proposal and justify it',
      'Handle a refusal without ending the discussion',
      'Reach or postpone agreement politely',
    ],
    openingLine: 'Le agradezco que haya venido. Debo decirle que el precio que propone nos resulta difícil de aceptar.',
    complications: ['The supplier says no indirectly rather than plainly', 'A deadline is introduced mid-conversation'],
  },
];
