import type { AuthoredVocabulary } from '../../dsl/types';

/**
 * Spanish vocabulary catalogue.
 *
 * `variantOverrides` is how one lesson serves several regions: a learner who
 * chose es-MX sees "carro", one who chose es-ES sees "coche", and the lesson
 * itself is written once. Audio keys follow `es/<level>/<key>` and resolve
 * against the media manifest.
 */

const v = (
  key: string,
  term: string,
  translation: string,
  cefr: AuthoredVocabulary['cefr'],
  categories: string[],
  extra: Partial<AuthoredVocabulary> = {},
): AuthoredVocabulary => ({
  key,
  term,
  translation,
  cefr,
  categories,
  audio: `es/vocab/${key}`,
  ...extra,
});

export const ES_VOCABULARY: AuthoredVocabulary[] = [
  // --- Pre-A1: sounds, greetings, courtesy, numbers -------------------------
  v('hola', 'hola', 'hello', 'PRE_A1', ['greetings'], { example: '¡Hola! ¿Qué tal?', exampleTranslation: 'Hi! How are you?' }),
  v('adios', 'adiós', 'goodbye', 'PRE_A1', ['greetings'], { example: 'Adiós, hasta mañana.', exampleTranslation: 'Goodbye, see you tomorrow.' }),
  v('si', 'sí', 'yes', 'PRE_A1', ['greetings']),
  v('no', 'no', 'no', 'PRE_A1', ['greetings']),
  v('gracias', 'gracias', 'thank you', 'PRE_A1', ['greetings'], { example: 'Muchas gracias.', exampleTranslation: 'Thank you very much.' }),
  v('por-favor', 'por favor', 'please', 'PRE_A1', ['greetings']),
  v('de-nada', 'de nada', "you're welcome", 'PRE_A1', ['greetings']),
  v('perdon', 'perdón', 'sorry / excuse me', 'PRE_A1', ['greetings']),
  v('buenos-dias', 'buenos días', 'good morning', 'PRE_A1', ['greetings']),
  v('buenas-tardes', 'buenas tardes', 'good afternoon', 'PRE_A1', ['greetings']),
  v('buenas-noches', 'buenas noches', 'good evening / good night', 'PRE_A1', ['greetings']),
  v('uno', 'uno', 'one', 'PRE_A1', ['numbers']),
  v('dos', 'dos', 'two', 'PRE_A1', ['numbers']),
  v('tres', 'tres', 'three', 'PRE_A1', ['numbers']),
  v('cuatro', 'cuatro', 'four', 'PRE_A1', ['numbers']),
  v('cinco', 'cinco', 'five', 'PRE_A1', ['numbers']),
  v('seis', 'seis', 'six', 'PRE_A1', ['numbers']),
  v('siete', 'siete', 'seven', 'PRE_A1', ['numbers']),
  v('ocho', 'ocho', 'eight', 'PRE_A1', ['numbers']),
  v('nueve', 'nueve', 'nine', 'PRE_A1', ['numbers']),
  v('diez', 'diez', 'ten', 'PRE_A1', ['numbers']),
  v('agua', 'el agua', 'water', 'PRE_A1', ['drinks', 'food'], { gender: 'f', partOfSpeech: 'noun' }),
  v('pan', 'el pan', 'bread', 'PRE_A1', ['food'], { gender: 'm', partOfSpeech: 'noun' }),
  v('casa', 'la casa', 'house', 'PRE_A1', ['home'], { gender: 'f', partOfSpeech: 'noun' }),
  v('libro', 'el libro', 'book', 'PRE_A1', ['school'], { gender: 'm', partOfSpeech: 'noun' }),
  v('no-entiendo', 'no entiendo', "I don't understand", 'PRE_A1', ['school']),
  v('repite-por-favor', 'repite, por favor', 'please repeat', 'PRE_A1', ['school']),
  v('como-se-dice', '¿cómo se dice…?', 'how do you say…?', 'PRE_A1', ['school']),

  // --- A1 Unit 1: introductions --------------------------------------------
  v('me-llamo', 'me llamo', 'my name is', 'A1', ['greetings'], { example: 'Hola, me llamo Ana.', exampleTranslation: "Hi, I'm Ana." }),
  v('como-te-llamas', '¿cómo te llamas?', "what's your name?", 'A1', ['greetings']),
  v('mucho-gusto', 'mucho gusto', 'nice to meet you', 'A1', ['greetings']),
  v('encantado', 'encantado / encantada', 'delighted to meet you', 'A1', ['greetings'], { partOfSpeech: 'adjective' }),
  v('como-estas', '¿cómo estás?', 'how are you?', 'A1', ['greetings']),
  v('bien', 'bien', 'well / fine', 'A1', ['greetings']),
  v('mal', 'mal', 'badly / not well', 'A1', ['greetings']),
  v('mas-o-menos', 'más o menos', 'so-so', 'A1', ['greetings']),
  v('de-donde-eres', '¿de dónde eres?', 'where are you from?', 'A1', ['greetings']),
  v('soy-de', 'soy de', "I'm from", 'A1', ['greetings']),
  v('hasta-luego', 'hasta luego', 'see you later', 'A1', ['greetings']),
  v('senor', 'el señor', 'sir / Mr', 'A1', ['greetings'], { gender: 'm' }),
  v('senora', 'la señora', 'madam / Mrs', 'A1', ['greetings'], { gender: 'f' }),

  // --- A1 Unit 2: family ----------------------------------------------------
  v('familia', 'la familia', 'family', 'A1', ['family'], { gender: 'f' }),
  v('madre', 'la madre', 'mother', 'A1', ['family'], { gender: 'f', variantOverrides: { 'es-MX': 'la mamá' } }),
  v('padre', 'el padre', 'father', 'A1', ['family'], { gender: 'm', variantOverrides: { 'es-MX': 'el papá' } }),
  v('hermano', 'el hermano', 'brother', 'A1', ['family'], { gender: 'm' }),
  v('hermana', 'la hermana', 'sister', 'A1', ['family'], { gender: 'f' }),
  v('hijo', 'el hijo', 'son', 'A1', ['family'], { gender: 'm' }),
  v('hija', 'la hija', 'daughter', 'A1', ['family'], { gender: 'f' }),
  v('abuelo', 'el abuelo', 'grandfather', 'A1', ['family'], { gender: 'm' }),
  v('abuela', 'la abuela', 'grandmother', 'A1', ['family'], { gender: 'f' }),
  v('esposo', 'el esposo', 'husband', 'A1', ['family', 'relationships'], { gender: 'm', variantOverrides: { 'es-ES': 'el marido' } }),
  v('esposa', 'la esposa', 'wife', 'A1', ['family', 'relationships'], { gender: 'f', variantOverrides: { 'es-ES': 'la mujer' } }),
  v('amigo', 'el amigo', 'friend', 'A1', ['relationships'], { gender: 'm' }),
  v('tener', 'tener', 'to have', 'A1', ['family'], { partOfSpeech: 'verb', example: 'Tengo dos hermanas.', exampleTranslation: 'I have two sisters.' }),
  v('anos', 'los años', 'years (of age)', 'A1', ['family', 'numbers'], { example: 'Tengo veinticinco años.', exampleTranslation: "I'm twenty-five." }),

  // --- A1 Unit 3: daily life ------------------------------------------------
  v('trabajar', 'trabajar', 'to work', 'A1', ['work'], { partOfSpeech: 'verb' }),
  v('estudiar', 'estudiar', 'to study', 'A1', ['school'], { partOfSpeech: 'verb' }),
  v('vivir', 'vivir', 'to live', 'A1', ['home'], { partOfSpeech: 'verb' }),
  v('hablar', 'hablar', 'to speak', 'A1', ['school'], { partOfSpeech: 'verb' }),
  v('comer', 'comer', 'to eat', 'A1', ['food'], { partOfSpeech: 'verb' }),
  v('beber', 'beber', 'to drink', 'A1', ['drinks'], { partOfSpeech: 'verb', variantOverrides: { 'es-MX': 'tomar' } }),
  v('levantarse', 'levantarse', 'to get up', 'A1', ['home'], { partOfSpeech: 'verb' }),
  v('manana', 'la mañana', 'morning', 'A1', ['time'], { gender: 'f' }),
  v('tarde', 'la tarde', 'afternoon', 'A1', ['time'], { gender: 'f' }),
  v('noche', 'la noche', 'night', 'A1', ['time'], { gender: 'f' }),
  v('hoy', 'hoy', 'today', 'A1', ['time']),
  v('siempre', 'siempre', 'always', 'A1', ['time']),
  v('nunca', 'nunca', 'never', 'A1', ['time']),
  v('a-veces', 'a veces', 'sometimes', 'A1', ['time']),

  // --- A1 Unit 4: food ------------------------------------------------------
  v('cafe', 'el café', 'coffee', 'A1', ['drinks'], { gender: 'm' }),
  v('te', 'el té', 'tea', 'A1', ['drinks'], { gender: 'm' }),
  v('leche', 'la leche', 'milk', 'A1', ['drinks'], { gender: 'f' }),
  v('jugo', 'el jugo', 'juice', 'A1', ['drinks'], { gender: 'm', variantOverrides: { 'es-ES': 'el zumo' } }),
  v('desayuno', 'el desayuno', 'breakfast', 'A1', ['food'], { gender: 'm' }),
  v('almuerzo', 'el almuerzo', 'lunch', 'A1', ['food'], { gender: 'm', variantOverrides: { 'es-ES': 'la comida' } }),
  v('cena', 'la cena', 'dinner', 'A1', ['food'], { gender: 'f' }),
  v('pollo', 'el pollo', 'chicken', 'A1', ['food'], { gender: 'm' }),
  v('arroz', 'el arroz', 'rice', 'A1', ['food'], { gender: 'm' }),
  v('ensalada', 'la ensalada', 'salad', 'A1', ['food'], { gender: 'f' }),
  v('fruta', 'la fruta', 'fruit', 'A1', ['food'], { gender: 'f' }),
  v('la-cuenta', 'la cuenta', 'the bill / check', 'A1', ['food', 'shopping'], { gender: 'f' }),
  v('quisiera', 'quisiera', 'I would like', 'A1', ['food', 'shopping'], { example: 'Quisiera un café, por favor.', exampleTranslation: "I'd like a coffee, please." }),

  // --- A1 Unit 5: shopping and numbers -------------------------------------
  v('cuanto-cuesta', '¿cuánto cuesta?', 'how much does it cost?', 'A1', ['shopping']),
  v('dinero', 'el dinero', 'money', 'A1', ['shopping'], { gender: 'm' }),
  v('caro', 'caro', 'expensive', 'A1', ['shopping'], { partOfSpeech: 'adjective' }),
  v('barato', 'barato', 'cheap', 'A1', ['shopping'], { partOfSpeech: 'adjective' }),
  v('tienda', 'la tienda', 'shop', 'A1', ['shopping'], { gender: 'f' }),
  v('mercado', 'el mercado', 'market', 'A1', ['shopping'], { gender: 'm' }),
  v('veinte', 'veinte', 'twenty', 'A1', ['numbers']),
  v('treinta', 'treinta', 'thirty', 'A1', ['numbers']),
  v('cien', 'cien', 'one hundred', 'A1', ['numbers']),

  // --- A1 Unit 6: travel and directions ------------------------------------
  v('donde-esta', '¿dónde está…?', 'where is…?', 'A1', ['directions', 'travel']),
  v('izquierda', 'la izquierda', 'left', 'A1', ['directions'], { gender: 'f' }),
  v('derecha', 'la derecha', 'right', 'A1', ['directions'], { gender: 'f' }),
  v('recto', 'todo recto', 'straight ahead', 'A1', ['directions'], { variantOverrides: { 'es-MX': 'derecho' } }),
  v('cerca', 'cerca', 'near', 'A1', ['directions']),
  v('lejos', 'lejos', 'far', 'A1', ['directions']),
  v('estacion', 'la estación', 'station', 'A1', ['transportation'], { gender: 'f' }),
  v('aeropuerto', 'el aeropuerto', 'airport', 'A1', ['travel', 'transportation'], { gender: 'm' }),
  v('billete', 'el billete', 'ticket', 'A1', ['travel'], { gender: 'm', variantOverrides: { 'es-MX': 'el boleto', 'es-419': 'el boleto' } }),
  v('hotel', 'el hotel', 'hotel', 'A1', ['travel'], { gender: 'm' }),
  v('coche', 'el coche', 'car', 'A1', ['transportation'], { gender: 'm', variantOverrides: { 'es-MX': 'el carro', 'es-419': 'el carro' } }),
  v('autobus', 'el autobús', 'bus', 'A1', ['transportation'], { gender: 'm', variantOverrides: { 'es-MX': 'el camión', 'es-AR': 'el colectivo' } }),

  // --- A1 Unit 7: home ------------------------------------------------------
  v('habitacion', 'la habitación', 'room', 'A1', ['home'], { gender: 'f', variantOverrides: { 'es-MX': 'el cuarto' } }),
  v('cocina', 'la cocina', 'kitchen', 'A1', ['home'], { gender: 'f' }),
  v('bano', 'el baño', 'bathroom', 'A1', ['home'], { gender: 'm' }),
  v('mesa', 'la mesa', 'table', 'A1', ['home'], { gender: 'f' }),
  v('silla', 'la silla', 'chair', 'A1', ['home'], { gender: 'f' }),
  v('ventana', 'la ventana', 'window', 'A1', ['home'], { gender: 'f' }),
  v('puerta', 'la puerta', 'door', 'A1', ['home'], { gender: 'f' }),

  // --- A1 Unit 8: work and school ------------------------------------------
  v('trabajo', 'el trabajo', 'work / job', 'A1', ['work'], { gender: 'm' }),
  v('oficina', 'la oficina', 'office', 'A1', ['work'], { gender: 'f' }),
  v('profesor', 'el profesor', 'teacher', 'A1', ['school', 'work'], { gender: 'm' }),
  v('estudiante', 'el/la estudiante', 'student', 'A1', ['school'], { partOfSpeech: 'noun' }),
  v('medico', 'el médico', 'doctor', 'A1', ['work', 'health'], { gender: 'm' }),
  v('ingeniero', 'el ingeniero', 'engineer', 'A1', ['work'], { gender: 'm' }),
  v('universidad', 'la universidad', 'university', 'A1', ['school'], { gender: 'f' }),
  v('clase', 'la clase', 'class', 'A1', ['school'], { gender: 'f' }),

  // --- A1 Unit 9: time and dates -------------------------------------------
  v('que-hora-es', '¿qué hora es?', "what time is it?", 'A1', ['time']),
  v('lunes', 'lunes', 'Monday', 'A1', ['time']),
  v('martes', 'martes', 'Tuesday', 'A1', ['time']),
  v('miercoles', 'miércoles', 'Wednesday', 'A1', ['time']),
  v('jueves', 'jueves', 'Thursday', 'A1', ['time']),
  v('viernes', 'viernes', 'Friday', 'A1', ['time']),
  v('sabado', 'sábado', 'Saturday', 'A1', ['time']),
  v('domingo', 'domingo', 'Sunday', 'A1', ['time']),
  v('hora', 'la hora', 'hour / time', 'A1', ['time'], { gender: 'f' }),
  v('minuto', 'el minuto', 'minute', 'A1', ['time'], { gender: 'm' }),

  // --- A2: past, travel problems, health, appointments ---------------------
  v('ayer', 'ayer', 'yesterday', 'A2', ['time']),
  v('anoche', 'anoche', 'last night', 'A2', ['time']),
  v('la-semana-pasada', 'la semana pasada', 'last week', 'A2', ['time']),
  v('fui', 'fui', 'I went / I was', 'A2', ['travel'], { partOfSpeech: 'verb', example: 'Ayer fui al mercado.', exampleTranslation: 'Yesterday I went to the market.' }),
  v('comi', 'comí', 'I ate', 'A2', ['food'], { partOfSpeech: 'verb' }),
  v('reserva', 'la reserva', 'reservation', 'A2', ['travel', 'food'], { gender: 'f', variantOverrides: { 'es-MX': 'la reservación' } }),
  v('retraso', 'el retraso', 'delay', 'A2', ['travel'], { gender: 'm', variantOverrides: { 'es-MX': 'la demora' } }),
  v('equipaje', 'el equipaje', 'luggage', 'A2', ['travel'], { gender: 'm' }),
  v('perder', 'perder', 'to miss / to lose', 'A2', ['travel'], { partOfSpeech: 'verb', example: 'Perdí el vuelo.', exampleTranslation: 'I missed the flight.' }),
  v('vuelo', 'el vuelo', 'flight', 'A2', ['travel'], { gender: 'm' }),
  v('cita', 'la cita', 'appointment', 'A2', ['health', 'work'], { gender: 'f' }),
  v('doler', 'doler', 'to hurt', 'A2', ['health'], { partOfSpeech: 'verb', example: 'Me duele la cabeza.', exampleTranslation: 'My head hurts.' }),
  v('cabeza', 'la cabeza', 'head', 'A2', ['body', 'health'], { gender: 'f' }),
  v('estomago', 'el estómago', 'stomach', 'A2', ['body', 'health'], { gender: 'm' }),
  v('farmacia', 'la farmacia', 'pharmacy', 'A2', ['health'], { gender: 'f' }),
  v('receta', 'la receta', 'prescription / recipe', 'A2', ['health', 'food'], { gender: 'f' }),
  v('quedar', 'quedar', 'to arrange to meet', 'A2', ['relationships'], { partOfSpeech: 'verb', example: '¿Quedamos a las ocho?', exampleTranslation: 'Shall we meet at eight?' }),
  v('probar', 'probar', 'to try / to taste', 'A2', ['food', 'shopping'], { partOfSpeech: 'verb' }),
  v('devolver', 'devolver', 'to return (something)', 'A2', ['shopping'], { partOfSpeech: 'verb' }),
  v('tallar', 'la talla', 'size (clothing)', 'A2', ['shopping', 'clothing'], { gender: 'f' }),
];
