import {
  buildSentence,
  categorize,
  converse,
  correctGrammar,
  course,
  dialogueCompletion,
  fillBlank,
  lesson,
  listen,
  mcq,
  realWorldTask,
  reviewChallenge,
  speak,
  speakResponse,
  spelling,
  storyCompletion,
  tapTranslation,
  timedChallenge,
  translate,
  unit,
  wordMatch,
  write,
} from '../../dsl/builders';
import type {
  AuthoredCulture,
  AuthoredCurriculum,
  AuthoredGrammar,
  AuthoredMedia,
  AuthoredScenario,
  AuthoredVocabulary,
} from '../../dsl/types';

/** French for English speakers. Pre-A1 sounds and A1 units 1-4 at launch. */

const v = (
  key: string,
  term: string,
  translation: string,
  cefr: AuthoredVocabulary['cefr'],
  categories: string[],
  extra: Partial<AuthoredVocabulary> = {},
): AuthoredVocabulary => ({ key, term, translation, cefr, categories, audio: `fr/vocab/${key}`, ...extra });

const FR_VOCABULARY: AuthoredVocabulary[] = [
  v('bonjour', 'bonjour', 'hello / good morning', 'PRE_A1', ['greetings']),
  v('bonsoir', 'bonsoir', 'good evening', 'PRE_A1', ['greetings']),
  v('au-revoir', 'au revoir', 'goodbye', 'PRE_A1', ['greetings']),
  v('merci', 'merci', 'thank you', 'PRE_A1', ['greetings']),
  v('sil-vous-plait', "s'il vous plaît", 'please (formal)', 'PRE_A1', ['greetings']),
  v('pardon', 'pardon', 'sorry / excuse me', 'PRE_A1', ['greetings']),
  v('oui', 'oui', 'yes', 'PRE_A1', ['greetings']),
  v('non', 'non', 'no', 'PRE_A1', ['greetings']),
  v('un', 'un', 'one', 'PRE_A1', ['numbers']),
  v('deux', 'deux', 'two', 'PRE_A1', ['numbers']),
  v('trois', 'trois', 'three', 'PRE_A1', ['numbers']),
  v('dix', 'dix', 'ten', 'PRE_A1', ['numbers']),
  v('eau', "l'eau", 'water', 'PRE_A1', ['drinks'], { gender: 'f' }),
  v('pain', 'le pain', 'bread', 'PRE_A1', ['food'], { gender: 'm' }),
  v('je-mappelle', "je m'appelle", 'my name is', 'A1', ['greetings']),
  v('comment-tu-tappelles', "comment tu t'appelles ?", "what's your name?", 'A1', ['greetings']),
  v('enchante', 'enchanté / enchantée', 'pleased to meet you', 'A1', ['greetings']),
  v('ca-va', 'ça va ?', 'how are you? / I’m fine', 'A1', ['greetings']),
  v('je-viens-de', 'je viens de', 'I come from', 'A1', ['greetings']),
  v('famille', 'la famille', 'family', 'A1', ['family'], { gender: 'f' }),
  v('mere', 'la mère', 'mother', 'A1', ['family'], { gender: 'f' }),
  v('pere', 'le père', 'father', 'A1', ['family'], { gender: 'm' }),
  v('frere', 'le frère', 'brother', 'A1', ['family'], { gender: 'm' }),
  v('soeur', 'la sœur', 'sister', 'A1', ['family'], { gender: 'f' }),
  v('avoir', 'avoir', 'to have', 'A1', ['family'], { partOfSpeech: 'verb' }),
  v('etre', 'être', 'to be', 'A1', ['greetings'], { partOfSpeech: 'verb' }),
  v('cafe', 'le café', 'coffee / café', 'A1', ['drinks'], { gender: 'm' }),
  v('the', 'le thé', 'tea', 'A1', ['drinks'], { gender: 'm' }),
  v('addition', "l'addition", 'the bill', 'A1', ['food'], { gender: 'f' }),
  v('je-voudrais', 'je voudrais', 'I would like', 'A1', ['food', 'shopping']),
  v('combien', 'combien ?', 'how much?', 'A1', ['shopping']),
  v('ou-est', 'où est… ?', 'where is…?', 'A1', ['directions']),
  v('gauche', 'à gauche', 'to the left', 'A1', ['directions']),
  v('droite', 'à droite', 'to the right', 'A1', ['directions']),
  v('tout-droit', 'tout droit', 'straight ahead', 'A1', ['directions']),
  v('gare', 'la gare', 'train station', 'A1', ['transportation'], { gender: 'f' }),
];

const FR_GRAMMAR: AuthoredGrammar[] = [
  {
    key: 'fr-gender',
    title: 'le, la, un, une',
    cefr: 'A1',
    summary: 'Every French noun is masculine or feminine, and the article shows which.',
    explanation:
      'French nouns carry a gender that is rarely predictable from meaning: le livre but la table. Learn the article with the noun. Before a vowel sound, le and la both become l\': l\'eau, l\'hôtel.',
    examples: [
      { target: 'le livre', native: 'the book (m)' },
      { target: 'la table', native: 'the table (f)' },
      { target: "l'eau", native: 'the water (f, elided)' },
    ],
    commonMistakes: [
      { wrong: 'la livre', right: 'le livre', why: '"Livre" (book) is masculine. "La livre" exists but means a pound.' },
      { wrong: 'le eau', right: "l'eau", why: 'Before a vowel sound the article elides to l\'.' },
    ],
  },
  {
    key: 'fr-etre-avoir',
    title: 'être and avoir',
    cefr: 'A1',
    summary: 'The two verbs everything else is built on — and French "has" its age.',
    explanation:
      'être: je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont. avoir: j\'ai, tu as, il/elle a, nous avons, vous avez, ils/elles ont. Like Spanish and unlike English, French uses avoir for age: j\'ai vingt-cinq ans.',
    examples: [
      { target: 'Je suis américain.', native: "I'm American." },
      { target: "J'ai deux sœurs.", native: 'I have two sisters.' },
      { target: "J'ai vingt-cinq ans.", native: "I'm twenty-five." },
    ],
    commonMistakes: [
      { wrong: 'Je suis vingt-cinq ans.', right: "J'ai vingt-cinq ans.", why: 'French expresses age with avoir, not être.' },
    ],
  },
  {
    key: 'fr-tu-vous',
    title: 'tu and vous',
    cefr: 'A1',
    summary: 'vous is not only plural — it is also the polite singular.',
    explanation:
      'Use tu with friends, family, children and peers your own age. Use vous with anyone you have just met, anyone older, and in every shop, office and official setting. Getting this wrong is more noticeable in France than the equivalent mistake in Spanish; when in doubt, use vous and wait to be invited to tutoyer.',
    examples: [
      { target: 'Comment allez-vous ?', native: 'How are you? (formal)' },
      { target: 'Comment ça va ?', native: 'How are you? (informal)' },
    ],
    commonMistakes: [
      { wrong: "Tu as l'heure ? (to a stranger)", right: "Vous avez l'heure ?", why: 'A stranger takes vous in French, even for a small question.' },
    ],
  },
  {
    key: 'fr-negation',
    title: 'ne… pas',
    cefr: 'A1',
    summary: 'French negation wraps around the verb.',
    explanation:
      'Put ne before the verb and pas after it: je ne parle pas français. Before a vowel, ne becomes n\': je n\'ai pas. In casual speech the ne often disappears — "je sais pas" — but it belongs in anything written.',
    examples: [
      { target: 'Je ne parle pas anglais.', native: "I don't speak English." },
      { target: "Je n'ai pas de frères.", native: "I don't have brothers." },
    ],
    commonMistakes: [
      { wrong: 'Je parle pas français.', right: 'Je ne parle pas français.', why: 'Dropping "ne" is common in speech but wrong in writing.' },
      { wrong: "Je n'ai pas des frères.", right: "Je n'ai pas de frères.", why: 'After a negative, du/de la/des all become "de".' },
    ],
  },
];

const FR_CULTURE: AuthoredCulture[] = [
  {
    key: 'fr-bonjour-rule',
    title: 'Always say bonjour first',
    cefr: 'PRE_A1',
    topic: 'etiquette',
    variantCodes: [],
    body:
      'In France, entering a shop, a bakery or a waiting room without saying "bonjour" is genuinely rude, and starting with a request instead is the single fastest way to get a cold reception. Say bonjour, then ask. After around 6pm it becomes bonsoir.',
  },
  {
    key: 'fr-tu-vous-culture',
    title: 'Who gets tu?',
    cefr: 'A1',
    topic: 'register',
    variantCodes: ['fr-FR'],
    body:
      'French draws the tu/vous line more firmly than Spanish draws tú/usted. Colleagues may use vous for months; a shop assistant is always vous. Québec is noticeably more relaxed, where tu appears sooner between strangers of similar age. Wait to be invited: "on peut se tutoyer".',
  },
  {
    key: 'fr-quebec-differences',
    title: 'French in Québec',
    cefr: 'A1',
    topic: 'regional differences',
    variantCodes: ['fr-CA'],
    body:
      'Québécois French differs in vocabulary and rhythm: "magasiner" for shopping, "char" for car, "dépanneur" for a corner shop, and "bienvenue" used as "you\'re welcome". Anglicisms are sometimes avoided where France accepts them: "courriel" rather than "email", "fin de semaine" rather than "week-end".',
  },
];

const FR_SCENARIOS: AuthoredScenario[] = [
  {
    key: 'fr-boulangerie',
    title: 'At the bakery',
    setting: 'A neighbourhood bakery in the morning, with a queue behind you.',
    partnerRole: 'A brisk but friendly baker',
    learnerRole: 'A customer',
    cefr: 'A1',
    goals: ['Greet the baker', 'Order bread and a pastry', 'Ask the price', 'Pay and say goodbye'],
    openingLine: 'Bonjour ! Vous désirez ?',
    complications: ['The item the learner asks for has sold out'],
    vocabulary: ['bonjour', 'pain', 'je-voudrais', 'combien', 'merci'],
  },
  {
    key: 'fr-meeting-someone',
    title: 'Meeting someone new',
    setting: 'A language exchange evening in a café.',
    partnerRole: 'A friendly French speaker who uses vous at first',
    learnerRole: 'A newcomer',
    cefr: 'A1',
    goals: ['Greet them', 'Give your name', 'Say where you are from', 'Ask about them'],
    openingLine: 'Bonsoir ! Vous êtes ici pour l’échange linguistique ?',
    vocabulary: ['bonsoir', 'je-mappelle', 'je-viens-de', 'enchante'],
  },
  {
    key: 'fr-asking-directions',
    title: 'Asking for the station',
    setting: 'You are lost and stop someone in the street.',
    partnerRole: 'A local who gives directions quickly',
    learnerRole: 'A visitor',
    cefr: 'A1',
    goals: ['Get their attention politely', 'Ask where the station is', 'Check you understood'],
    openingLine: 'Oui ?',
    complications: ['The directions are given fast and must be repeated'],
    vocabulary: ['pardon', 'ou-est', 'gare', 'gauche', 'droite'],
  },
];

const TTS_SOURCE = 'lingonest-tts-pipeline';
const TTS_LICENCE = 'proprietary-generated';

const FR_DIALOGUES: { key: string; transcript: string; speeds?: ('slow' | 'normal' | 'natural')[] }[] = [
  { key: 'fr/pre-a1/u1/greetings', transcript: '— Bonjour ! — Bonjour, madame. — Au revoir. — Bonne journée !' },
  { key: 'fr/pre-a1/u2/sounds-r', transcript: 'rouge, Paris, merci, bonjour' },
  { key: 'fr/a1/u1/introductions', transcript: "— Bonsoir, je m'appelle Claire. — Enchanté. Moi, c'est Tom. — Vous venez d'où ? — Je viens de Chicago.", speeds: ['slow', 'normal'] },
  { key: 'fr/a1/u2/family', transcript: "— Tu as des frères et sœurs ? — Oui, j'ai une sœur et deux frères. — Et quel âge a ta sœur ? — Elle a trente ans.", speeds: ['slow', 'normal'] },
  { key: 'fr/a1/u3/boulangerie', transcript: '— Bonjour, vous désirez ? — Je voudrais une baguette, s’il vous plaît. — Et avec ceci ? — C’est tout, merci. Ça fait combien ?', speeds: ['slow', 'normal'] },
  { key: 'fr/a1/u4/directions', transcript: '— Pardon, où est la gare ? — Tout droit, puis à gauche. C’est à cinq minutes.', speeds: ['slow', 'normal'] },
];

const FR_MEDIA: AuthoredMedia[] = [
  ...FR_VOCABULARY.filter((item) => item.audio).map((item) => ({
    key: item.audio!,
    kind: 'audio' as const,
    path: `audio/${item.audio}.m4a`,
    source: TTS_SOURCE,
    licence: TTS_LICENCE,
    voice: 'fr-FR-female-1',
    speed: 'slow' as const,
    transcript: item.term,
  })),
  ...FR_DIALOGUES.flatMap((d) =>
    (d.speeds ?? ['normal']).map((speed) => ({
      key: speed === 'normal' ? d.key : `${d.key}-${speed}`,
      kind: 'audio' as const,
      path: `audio/${d.key}${speed === 'normal' ? '' : `-${speed}`}.m4a`,
      source: TTS_SOURCE,
      licence: TTS_LICENCE,
      voice: 'fr-FR-multi',
      speed,
      transcript: d.transcript,
    })),
  ),
  ...['fr/img/eau', 'fr/img/pain', 'fr/img/cafe', 'fr/img/gare'].map((key) => ({
    key,
    kind: 'image' as const,
    path: `images/${key}.webp`,
    source: 'lingonest-illustration-set',
    licence: 'proprietary-commissioned',
  })),
];

const FR_PRE_A1 = course({
  slug: 'fr-pre-a1-foundations',
  title: 'First Steps in French',
  description: 'The sounds of French, the bonjour rule, courtesy and numbers — before any grammar.',
  cefr: 'PRE_A1',
  units: [
    unit({
      slug: 'fr-pre-a1-u1',
      title: 'Bonjour',
      objective: 'Greet people the way French expects.',
      theme: 'greetings',
      cefr: 'PRE_A1',
      realWorldTask: 'Walk into a shop, greet the staff, and leave politely.',
      lessons: [
        lesson({
          slug: 'fr-pre-a1-u1-l1',
          title: 'Bonjour and Au Revoir',
          objective: 'Greet and leave.',
          canDo: 'I can greet someone and say goodbye in French.',
          cefr: 'PRE_A1',
          minutes: 6,
          vocabulary: ['bonjour', 'bonsoir', 'au-revoir'],
          culture: ['fr-bonjour-rule'],
          activities: [
            listen({
              audio: 'fr/pre-a1/u1/greetings',
              instruction: 'Listen to the exchange.',
              question: 'What does the shopkeeper say back?',
              options: ['Bonjour, madame.', 'Au revoir.', 'Merci.'],
              answer: 'Bonjour, madame.',
              transcript: '— Bonjour ! — Bonjour, madame. — Au revoir. — Bonne journée !',
              speed: 'slow',
              why: 'The greeting is always returned, usually with madame or monsieur.',
            }),
            mcq({
              question: 'You walk into a bakery. What do you say before anything else?',
              options: ['Bonjour', 'Je voudrais du pain', 'Combien ?'],
              answer: 'Bonjour',
              why: 'Starting with a request instead of bonjour is genuinely rude in France — this one habit changes how you are treated.',
              tags: ['culture:bonjour-rule'],
            }),
            wordMatch({
              instruction: 'Match each greeting.',
              pairs: [
                ['bonjour', 'hello / good morning'],
                ['bonsoir', 'good evening'],
                ['au revoir', 'goodbye'],
              ],
              tags: ['vocab:bonjour', 'vocab:bonsoir', 'vocab:au-revoir'],
            }),
            speak({ target: 'Bonjour !', audio: 'fr/vocab/bonjour', phonetic: 'bon-ZHOOR', focusPhonemes: ['r', 'nasal-on'] }),
            reviewChallenge({ count: 4 }),
          ],
        }),
        lesson({
          slug: 'fr-pre-a1-u1-l2',
          title: 'Merci and S\'il Vous Plaît',
          objective: 'Use the courtesy words.',
          canDo: 'I can say please, thank you and sorry.',
          cefr: 'PRE_A1',
          minutes: 6,
          vocabulary: ['merci', 'sil-vous-plait', 'pardon', 'oui', 'non'],
          activities: [
            wordMatch({
              instruction: 'Match each expression.',
              pairs: [
                ['merci', 'thank you'],
                ["s'il vous plaît", 'please'],
                ['pardon', 'sorry / excuse me'],
              ],
              tags: ['vocab:merci', 'vocab:sil-vous-plait', 'vocab:pardon'],
            }),
            mcq({
              question: 'Which "please" do you use with a shop assistant?',
              options: ["s'il vous plaît", "s'il te plaît", 'merci'],
              answer: "s'il vous plaît",
              why: 'Vous with anyone you do not know; "s\'il te plaît" is for friends and children.',
              tags: ['grammar:fr-tu-vous'],
            }),
            dialogueCompletion({
              lines: [
                { speaker: 'Vous', text: 'Un café, ___.' },
                { speaker: 'Serveur', text: 'Voilà.' },
                { speaker: 'Vous', text: 'Merci.' },
              ],
              options: ["s'il vous plaît", 'pardon', 'au revoir'],
              answer: "s'il vous plaît",
              why: 'The polite phrase closes the request.',
            }),
            speak({ target: "Merci, s'il vous plaît", audio: 'fr/vocab/merci', focusPhonemes: ['r'] }),
            reviewChallenge({ count: 5 }),
          ],
        }),
        lesson({
          slug: 'fr-pre-a1-u1-l3',
          title: 'Sounds and Numbers',
          objective: 'Handle the French r, nasal vowels, and count to ten.',
          canDo: 'I can attempt French sounds and count to ten.',
          cefr: 'PRE_A1',
          minutes: 8,
          isReview: true,
          vocabulary: ['un', 'deux', 'trois', 'dix', 'eau', 'pain'],
          activities: [
            listen({
              audio: 'fr/pre-a1/u2/sounds-r',
              instruction: 'Listen to four words with the French r.',
              question: 'Where is the French r produced?',
              options: ['In the back of the throat', 'With the tip of the tongue', 'With the lips'],
              answer: 'In the back of the throat',
              transcript: 'rouge, Paris, merci, bonjour',
              speed: 'slow',
              why: 'The French r is uvular, unlike the Spanish rolled r or the English r.',
              tags: ['phoneme:fr-r'],
            }),
            speak({ target: 'rouge, Paris, merci', focusPhonemes: ['fr-r'] }),
            mcq({
              question: 'How is the final consonant in "trois" pronounced?',
              options: ['It is silent', 'Like an s', 'Like a z'],
              answer: 'It is silent',
              why: 'French usually drops a final consonant — until liaison brings it back before a vowel.',
              tags: ['phoneme:silent-final'],
            }),
            spelling({
              instruction: 'Write the French for "water".',
              answer: "l'eau",
              why: 'The article elides before a vowel sound: l\'eau.',
              tags: ['vocab:eau', 'grammar:fr-gender'],
            }),
            timedChallenge({
              instruction: 'Say the French number.',
              items: [
                ['1', 'un'],
                ['2', 'deux'],
                ['3', 'trois'],
                ['10', 'dix'],
              ],
              seconds: 45,
            }),
            realWorldTask({
              situation: 'You go into a bakery for bread. Greet, order, thank them and leave.',
              goals: ['Say bonjour first', 'Ask for bread politely', 'Thank them', 'Say goodbye'],
            }),
          ],
        }),
        lesson({
          slug: 'fr-pre-a1-u1-l4',
          title: 'Pre-A1 Checkpoint',
          objective: 'Check the foundations.',
          canDo: 'I can greet, thank, count and make a simple request in French.',
          cefr: 'PRE_A1',
          minutes: 12,
          isCheckpoint: true,
          activities: [
            listen({
              audio: 'fr/pre-a1/u1/greetings',
              instruction: 'Listening.',
              question: 'How does the shopkeeper reply?',
              options: ['Bonjour, madame.', 'Au revoir.', 'Merci.'],
              answer: 'Bonjour, madame.',
              transcript: '— Bonjour ! — Bonjour, madame. — Au revoir. — Bonne journée !',
              speed: 'normal',
              why: 'The greeting is always returned before anything else.',
            }),
            timedChallenge({
              instruction: 'Vocabulary.',
              items: [
                ['hello', 'bonjour'],
                ['thank you', 'merci'],
                ['please (formal)', "s'il vous plaît"],
                ['one', 'un'],
                ['ten', 'dix'],
              ],
              seconds: 90,
            }),
            buildSentence({
              target: "Bonjour un pain s'il vous plaît",
              tokens: ["s'il", 'Bonjour', 'plaît', 'un', 'vous', 'pain'],
              instruction: 'Greet and ask for a bread politely.',
              why: 'Bonjour first — always — then the request, then the courtesy phrase.',
            }),
            speak({ target: "Bonjour, un pain s'il vous plaît.", focusPhonemes: ['fr-r'] }),
            speakResponse({
              situation: 'You walk into a bakery and the baker greets you.',
              question: 'Bonjour ! Vous désirez ?',
              goal: 'Greet back and order politely',
              criteria: ['Returns the greeting', 'Makes a request', 'Uses a courtesy phrase'],
            }),
            realWorldTask({
              situation: 'Buy bread at a French bakery from start to finish.',
              goals: ['Say bonjour', 'Order', 'Ask the price', 'Thank them and leave'],
            }),
          ],
        }),
      ],
    }),
  ],
});

const FR_A1 = course({
  slug: 'fr-a1-survival',
  title: 'French A1: Getting By',
  description:
    'Introduce yourself, talk about your family, order in a café, and find your way — with the tu/vous distinction handled properly from the start.',
  cefr: 'A1',
  units: [
    unit({
      slug: 'fr-a1-u1',
      title: 'Introductions',
      objective: 'Introduce yourself and choose tu or vous correctly.',
      theme: 'greetings',
      cefr: 'A1',
      realWorldTask: 'Introduce yourself to a French speaker using the right level of formality.',
      lessons: [
        lesson({
          slug: 'fr-a1-u1-l1',
          title: "Je m'appelle",
          objective: 'Say your name and ask someone theirs.',
          canDo: 'I can introduce myself in French.',
          cefr: 'A1',
          minutes: 8,
          vocabulary: ['je-mappelle', 'comment-tu-tappelles', 'enchante', 'ca-va'],
          activities: [
            listen({
              audio: 'fr/a1/u1/introductions',
              instruction: 'Listen to two people meeting.',
              question: 'Where is Tom from?',
              options: ['Chicago', 'Paris', 'Montréal'],
              answer: 'Chicago',
              transcript: "— Bonsoir, je m'appelle Claire. — Enchanté. Moi, c'est Tom. — Vous venez d'où ? — Je viens de Chicago.",
              speed: 'slow',
              why: '"Je viens de Chicago."',
            }),
            tapTranslation({
              source: "Je m'appelle Claire.",
              options: ['My name is Claire.', 'I call Claire.', 'I know Claire.'],
              answer: 'My name is Claire.',
              why: 'Literally "I call myself" — a reflexive verb, like Spanish "me llamo".',
              tags: ['vocab:je-mappelle'],
            }),
            buildSentence({
              target: "Bonjour je m'appelle Marie",
              tokens: ["m'appelle", 'Bonjour', 'Marie', 'je'],
              instruction: 'Introduce yourself as Marie.',
              why: 'Greeting first, then the introduction.',
              tags: ['vocab:je-mappelle'],
            }),
            speak({ target: "Je m'appelle…", focusPhonemes: ['fr-r', 'nasal-an'] }),
            converse({
              scenario: 'fr-meeting-someone',
              goals: ['Greet them', 'Give your name', 'Say where you are from', 'Ask about them'],
              minTurns: 4,
            }),
          ],
        }),
        lesson({
          slug: 'fr-a1-u1-l2',
          title: 'tu or vous?',
          objective: 'Choose the right form for the situation.',
          canDo: 'I can decide whether to use tu or vous.',
          cefr: 'A1',
          minutes: 8,
          grammar: ['fr-tu-vous'],
          culture: ['fr-tu-vous-culture', 'fr-quebec-differences'],
          activities: [
            categorize({
              instruction: 'Sort each person by the form you would use.',
              categories: ['tu', 'vous'],
              mapping: {
                'a close friend': 'tu',
                'a shop assistant': 'vous',
                'a child': 'tu',
                'your new manager': 'vous',
              },
              why: 'Vous with anyone you have just met or who is in a professional role; tu with friends, family and children.',
              tags: ['grammar:fr-tu-vous'],
            }),
            correctGrammar({
              incorrect: "Pardon, tu as l'heure ? (to a stranger in the street)",
              correct: "Pardon, vous avez l'heure ?",
              why: 'A stranger takes vous in French, even for a one-line question.',
              topic: 'fr-tu-vous',
            }),
            mcq({
              question: 'In Québec, how does the tu/vous line differ?',
              options: [
                'tu appears sooner between strangers of similar age',
                'vous is not used at all',
                'there is no difference',
              ],
              answer: 'tu appears sooner between strangers of similar age',
              why: 'Québécois usage is noticeably more relaxed than in France, though vous is still used in formal settings.',
              tags: ['culture:quebec'],
            }),
            speak({ target: 'Comment allez-vous ?' }),
            reviewChallenge({ count: 6 }),
          ],
        }),
        lesson({
          slug: 'fr-a1-u1-l3',
          title: 'être and avoir',
          objective: 'Use the two core verbs.',
          canDo: 'I can say who I am and what I have.',
          cefr: 'A1',
          minutes: 9,
          vocabulary: ['etre', 'avoir', 'je-viens-de'],
          grammar: ['fr-etre-avoir'],
          activities: [
            fillBlank({
              template: 'Je {{blank}} américain.',
              answers: ['suis'],
              wordBank: ['suis', 'ai', 'es'],
              why: 'Nationality takes être: je suis.',
              tags: ['grammar:fr-etre-avoir'],
            }),
            fillBlank({
              template: "J'{{blank}} vingt-cinq ans.",
              answers: ['ai'],
              wordBank: ['ai', 'suis', 'as'],
              why: 'Like Spanish, French expresses age with avoir.',
              tags: ['grammar:fr-etre-avoir'],
            }),
            correctGrammar({
              incorrect: 'Je suis vingt-cinq ans.',
              correct: "J'ai vingt-cinq ans.",
              why: 'Age uses avoir, not être — the same pattern as Spanish tener.',
              topic: 'fr-etre-avoir',
            }),
            translate({
              source: 'I have two sisters.',
              answer: "J'ai deux sœurs.",
              alternatives: ["J'ai 2 sœurs"],
              why: 'Avoir plus the number and noun; the je elides to j\' before a vowel.',
              tags: ['grammar:fr-etre-avoir'],
            }),
            reviewChallenge({ count: 6 }),
          ],
        }),
        lesson({
          slug: 'fr-a1-u1-l4',
          title: 'Unit 1 Review',
          objective: 'Complete a first-meeting conversation.',
          canDo: 'I can hold a short first conversation in French.',
          cefr: 'A1',
          minutes: 9,
          isReview: true,
          activities: [
            storyCompletion({
              story: "Bonsoir, je {{blank}} Tom. Je {{blank}} de Chicago et j'{{blank}} trente ans.",
              answers: ["m'appelle", 'viens', 'ai'],
              wordBank: ["m'appelle", 'viens', 'ai', 'suis', 'est'],
              why: 'Name, origin and age — the three facts a first conversation needs.',
            }),
            timedChallenge({
              instruction: 'Translate as many as you can.',
              items: [
                ['my name is', "je m'appelle"],
                ['pleased to meet you', 'enchanté'],
                ['I come from', 'je viens de'],
                ['I have', "j'ai"],
                ['thank you', 'merci'],
              ],
              seconds: 75,
            }),
            write({
              task: 'Write four sentences introducing yourself in French, using vous with the reader.',
              goal: 'Write a formal self-introduction',
              criteria: ['Uses être and avoir correctly', 'Uses vous consistently', 'Four sentences'],
              minWords: 20,
            }),
            realWorldTask({
              situation: 'You join a French conversation group and introduce yourself to the organiser.',
              goals: ['Greet formally', 'Give your name and origin', 'Give your age or profession', 'Ask a question back'],
            }),
          ],
        }),
      ],
    }),
    unit({
      slug: 'fr-a1-u2',
      title: 'Family',
      objective: 'Talk about your family.',
      theme: 'family',
      cefr: 'A1',
      realWorldTask: 'Describe your family to a French speaker in several sentences.',
      lessons: [
        lesson({
          slug: 'fr-a1-u2-l1',
          title: 'Family Words',
          objective: 'Name family members with the right article.',
          canDo: 'I can name my family members.',
          cefr: 'A1',
          minutes: 8,
          vocabulary: ['famille', 'mere', 'pere', 'frere', 'soeur'],
          grammar: ['fr-gender'],
          activities: [
            wordMatch({
              instruction: 'Match each word.',
              pairs: [
                ['la mère', 'mother'],
                ['le père', 'father'],
                ['le frère', 'brother'],
                ['la sœur', 'sister'],
              ],
              tags: ['vocab:mere', 'vocab:pere', 'vocab:frere', 'vocab:soeur'],
            }),
            categorize({
              instruction: 'Sort each noun by its article.',
              categories: ['le', 'la'],
              mapping: { père: 'le', mère: 'la', frère: 'le', sœur: 'la', famille: 'la' },
              why: 'Gender is a property of the word; learning it with the article is the only reliable route.',
              tags: ['grammar:fr-gender'],
            }),
            listen({
              audio: 'fr/a1/u2/family',
              instruction: 'Listen to the conversation.',
              question: 'How old is the sister?',
              options: ['Thirty', 'Thirteen', 'Three'],
              answer: 'Thirty',
              transcript: "— Tu as des frères et sœurs ? — Oui, j'ai une sœur et deux frères. — Et quel âge a ta sœur ? — Elle a trente ans.",
              speed: 'slow',
              why: '"Trente" is thirty; "treize" would be thirteen.',
            }),
            reviewChallenge({ count: 6 }),
          ],
        }),
        lesson({
          slug: 'fr-a1-u2-l2',
          title: 'Negation',
          objective: 'Say what you do not have.',
          canDo: 'I can make negative sentences.',
          cefr: 'A1',
          minutes: 9,
          grammar: ['fr-negation'],
          activities: [
            mcq({
              question: 'Which is correct?',
              options: ['Je ne parle pas français.', 'Je parle ne pas français.', 'Je pas parle français.'],
              answer: 'Je ne parle pas français.',
              why: 'Negation wraps the verb: ne before, pas after.',
              tags: ['grammar:fr-negation'],
            }),
            correctGrammar({
              incorrect: "Je n'ai pas des frères.",
              correct: "Je n'ai pas de frères.",
              why: 'After a negative, du, de la and des all become "de".',
              topic: 'fr-negation',
            }),
            fillBlank({
              template: 'Elle {{blank}} habite {{blank}} à Paris.',
              answers: ["n'", 'pas'],
              wordBank: ["n'", 'pas', 'ne', 'non'],
              why: 'Before a vowel, ne becomes n\'.',
              tags: ['grammar:fr-negation'],
            }),
            speakResponse({
              situation: 'Someone asks whether you have brothers or sisters.',
              question: 'Tu as des frères et sœurs ?',
              goal: 'Answer, including at least one negative',
              criteria: ['Uses avoir correctly', 'Uses ne… pas correctly if answering negatively'],
            }),
            reviewChallenge({ count: 6 }),
          ],
        }),
      ],
    }),
    unit({
      slug: 'fr-a1-u3',
      title: 'Café and Shopping',
      objective: 'Order and pay.',
      theme: 'food',
      cefr: 'A1',
      realWorldTask: 'Order at a bakery or café and pay, starting with bonjour.',
      lessons: [
        lesson({
          slug: 'fr-a1-u3-l1',
          title: 'Je voudrais',
          objective: 'Order politely.',
          canDo: 'I can order food and drink politely.',
          cefr: 'A1',
          minutes: 9,
          vocabulary: ['je-voudrais', 'cafe', 'the', 'combien', 'addition'],
          activities: [
            listen({
              audio: 'fr/a1/u3/boulangerie',
              instruction: 'Listen to the bakery exchange.',
              question: 'What does the customer order?',
              options: ['A baguette', 'A coffee', 'Two croissants'],
              answer: 'A baguette',
              transcript: '— Bonjour, vous désirez ? — Je voudrais une baguette, s’il vous plaît. — Et avec ceci ? — C’est tout, merci. Ça fait combien ?',
              speed: 'slow',
              why: '"Je voudrais une baguette" — the polite conditional.',
            }),
            mcq({
              question: 'Why "je voudrais" rather than "je veux"?',
              options: ['It is the polite form', 'It is the past tense', 'They are identical'],
              answer: 'It is the polite form',
              why: '"Je veux" (I want) sounds blunt to a stranger; the conditional softens it.',
              tags: ['vocab:je-voudrais'],
            }),
            buildSentence({
              target: "Je voudrais un café s'il vous plaît",
              tokens: ["s'il", 'Je', 'café', 'voudrais', 'plaît', 'un', 'vous'],
              instruction: 'Order a coffee politely.',
              why: 'The request, then the courtesy phrase.',
              tags: ['vocab:je-voudrais'],
            }),
            converse({
              scenario: 'fr-boulangerie',
              goals: ['Greet the baker', 'Order bread and a pastry', 'Ask the price', 'Pay and say goodbye'],
              minTurns: 5,
            }),
          ],
        }),
      ],
    }),
    unit({
      slug: 'fr-a1-u4',
      title: 'Getting Around',
      objective: 'Ask for and follow directions.',
      theme: 'travel',
      cefr: 'A1',
      realWorldTask: 'Ask a French speaker for directions and follow them.',
      lessons: [
        lesson({
          slug: 'fr-a1-u4-l1',
          title: 'Où est… ?',
          objective: 'Ask where something is and understand the answer.',
          canDo: 'I can ask for directions and follow them.',
          cefr: 'A1',
          minutes: 9,
          vocabulary: ['ou-est', 'gauche', 'droite', 'tout-droit', 'gare'],
          activities: [
            listen({
              audio: 'fr/a1/u4/directions',
              instruction: 'Listen to the directions.',
              question: 'Which way after going straight?',
              options: ['Left', 'Right', 'Back'],
              answer: 'Left',
              transcript: '— Pardon, où est la gare ? — Tout droit, puis à gauche. C’est à cinq minutes.',
              speed: 'slow',
              why: '"Puis à gauche" — then left.',
            }),
            wordMatch({
              instruction: 'Match each direction.',
              pairs: [
                ['à gauche', 'to the left'],
                ['à droite', 'to the right'],
                ['tout droit', 'straight ahead'],
              ],
              tags: ['vocab:gauche', 'vocab:droite', 'vocab:tout-droit'],
            }),
            mcq({
              question: 'Careful: what is the difference between "à droite" and "tout droit"?',
              options: [
                'One is "to the right", the other is "straight ahead"',
                'They mean the same thing',
                'One is formal',
              ],
              answer: 'One is "to the right", the other is "straight ahead"',
              why: 'These two trip up almost every learner, and they send you in different directions.',
              tags: ['vocab:droite', 'vocab:tout-droit'],
            }),
            converse({
              scenario: 'fr-asking-directions',
              goals: ['Get their attention politely', 'Ask where the station is', 'Check you understood'],
              minTurns: 4,
            }),
            realWorldTask({
              situation: 'You are lost in Lyon and need the nearest station.',
              goals: ['Say pardon and get attention', 'Ask where the station is', 'Ask them to repeat', 'Thank them'],
            }),
          ],
        }),
        lesson({
          slug: 'fr-a1-u4-l2',
          title: 'A1 Checkpoint',
          objective: 'Assess the level across the six skills.',
          canDo: 'I can introduce myself, order, and find my way in French.',
          cefr: 'A1',
          minutes: 16,
          isCheckpoint: true,
          activities: [
            listen({
              audio: 'fr/a1/u3/boulangerie',
              instruction: 'Listening at normal speed.',
              question: 'What does the customer say at the end?',
              options: ['C’est tout, merci.', 'Au revoir.', 'Je voudrais deux baguettes.'],
              answer: 'C’est tout, merci.',
              transcript: '— Bonjour, vous désirez ? — Je voudrais une baguette, s’il vous plaît. — Et avec ceci ? — C’est tout, merci. Ça fait combien ?',
              speed: 'normal',
              why: '"C’est tout" closes the order before asking the price.',
            }),
            storyCompletion({
              story: "Reading: Je {{blank}} Claire. J'{{blank}} vingt ans et je {{blank}} de Lyon.",
              answers: ["m'appelle", 'ai', 'viens'],
              wordBank: ["m'appelle", 'ai', 'viens', 'suis', 'est'],
              why: 'Name, age with avoir, origin with venir de.',
            }),
            correctGrammar({
              incorrect: 'Je suis vingt ans et je parle pas français.',
              correct: "J'ai vingt ans et je ne parle pas français.",
              why: 'Age takes avoir, and written negation needs both ne and pas.',
              topic: 'fr-etre-avoir',
            }),
            timedChallenge({
              instruction: 'Vocabulary.',
              items: [
                ['my name is', "je m'appelle"],
                ['I would like', 'je voudrais'],
                ['where is', 'où est'],
                ['to the left', 'à gauche'],
                ['how much', 'combien'],
              ],
              seconds: 100,
            }),
            speakResponse({
              situation: 'Speaking: you meet a French tutor for the first time.',
              question: 'Bonjour ! Présentez-vous, s’il vous plaît.',
              goal: 'Introduce yourself formally',
              criteria: ['Uses vous', 'Name and origin', 'Age or profession'],
            }),
            write({
              task: 'Writing: write a short message introducing yourself and asking for directions to the station.',
              goal: 'Combine an introduction with a request',
              criteria: ['Correct être/avoir', 'A polite request', 'Correct negation if used'],
              minWords: 35,
            }),
            realWorldTask({
              situation: 'You arrive in a French town, buy bread, then ask a passer-by for the station.',
              goals: ['Greet before each request', 'Order and pay', 'Ask for directions', 'Thank both people'],
              constraints: ['French only'],
            }),
          ],
        }),
      ],
    }),
  ],
});

export const FR_CURRICULUM: AuthoredCurriculum = {
  languageCode: 'fr',
  courses: [FR_PRE_A1, FR_A1],
  vocabulary: FR_VOCABULARY,
  grammar: FR_GRAMMAR,
  culture: FR_CULTURE,
  scenarios: FR_SCENARIOS,
  media: FR_MEDIA,
};
