import {
  audioChoice,
  buildSentence,
  categorize,
  converse,
  correctGrammar,
  course,
  dialogueCompletion,
  fillBlank,
  lesson,
  listen,
  mcq,
  realWorldTask,
  reviewChallenge,
  speak,
  speakResponse,
  spelling,
  timedChallenge,
  translate,
  unit,
  wordMatch,
  write,
} from '../../dsl/builders';
import type {
  AuthoredCulture,
  AuthoredCurriculum,
  AuthoredGrammar,
  AuthoredMedia,
  AuthoredScenario,
  AuthoredVocabulary,
} from '../../dsl/types';

/**
 * Japanese for English speakers.
 *
 * Japanese is the language that proves the architecture: it needs a writing
 * system module before anything else, it is not space-separated, and its
 * politeness levels are grammatical rather than optional. All of that is
 * declared as data on the language record — no application code changes.
 */

const v = (
  key: string,
  term: string,
  translation: string,
  cefr: AuthoredVocabulary['cefr'],
  categories: string[],
  extra: Partial<AuthoredVocabulary> = {},
): AuthoredVocabulary => ({ key, term, translation, cefr, categories, audio: `ja/vocab/${key}`, ...extra });

const JA_VOCABULARY: AuthoredVocabulary[] = [
  v('konnichiwa', 'こんにちは', 'hello (daytime)', 'PRE_A1', ['greetings'], { pronunciation: 'konnichiwa' }),
  v('ohayou', 'おはようございます', 'good morning (polite)', 'PRE_A1', ['greetings'], { pronunciation: 'ohayō gozaimasu' }),
  v('konbanwa', 'こんばんは', 'good evening', 'PRE_A1', ['greetings'], { pronunciation: 'konbanwa' }),
  v('sayounara', 'さようなら', 'goodbye', 'PRE_A1', ['greetings'], { pronunciation: 'sayōnara' }),
  v('arigatou', 'ありがとうございます', 'thank you (polite)', 'PRE_A1', ['greetings'], { pronunciation: 'arigatō gozaimasu' }),
  v('sumimasen', 'すみません', 'excuse me / sorry / thank you', 'PRE_A1', ['greetings'], { pronunciation: 'sumimasen' }),
  v('hai', 'はい', 'yes', 'PRE_A1', ['greetings'], { pronunciation: 'hai' }),
  v('iie', 'いいえ', 'no', 'PRE_A1', ['greetings'], { pronunciation: 'iie' }),
  v('ichi', 'いち', 'one', 'PRE_A1', ['numbers'], { pronunciation: 'ichi' }),
  v('ni', 'に', 'two', 'PRE_A1', ['numbers'], { pronunciation: 'ni' }),
  v('san', 'さん', 'three', 'PRE_A1', ['numbers'], { pronunciation: 'san' }),
  v('juu', 'じゅう', 'ten', 'PRE_A1', ['numbers'], { pronunciation: 'jū' }),
  v('mizu', 'みず', 'water', 'PRE_A1', ['drinks'], { pronunciation: 'mizu' }),
  v('pan', 'パン', 'bread', 'PRE_A1', ['food'], { pronunciation: 'pan', example: 'パンをください。' }),
  v('watashi', 'わたし', 'I / me', 'A1', ['greetings'], { pronunciation: 'watashi' }),
  v('namae', 'なまえ', 'name', 'A1', ['greetings'], { pronunciation: 'namae' }),
  v('desu', 'です', 'is / am / are (polite)', 'A1', ['greetings'], { pronunciation: 'desu' }),
  v('yoroshiku', 'よろしくおねがいします', 'pleased to meet you', 'A1', ['greetings'], { pronunciation: 'yoroshiku onegaishimasu' }),
  v('nihongo', 'にほんご', 'Japanese language', 'A1', ['school'], { pronunciation: 'nihongo' }),
  v('kudasai', 'ください', 'please give me', 'A1', ['food', 'shopping'], { pronunciation: 'kudasai' }),
  v('ikura', 'いくらですか', 'how much is it?', 'A1', ['shopping'], { pronunciation: 'ikura desu ka' }),
  v('doko', 'どこ', 'where', 'A1', ['directions'], { pronunciation: 'doko' }),
  v('eki', 'えき', 'station', 'A1', ['transportation'], { pronunciation: 'eki' }),
  v('kazoku', 'かぞく', 'family', 'A1', ['family'], { pronunciation: 'kazoku' }),
  v('ani', 'あに', 'older brother (my own)', 'A1', ['family'], { pronunciation: 'ani' }),
  v('ane', 'あね', 'older sister (my own)', 'A1', ['family'], { pronunciation: 'ane' }),
  v('sensei', 'せんせい', 'teacher', 'A1', ['school', 'work'], { pronunciation: 'sensei' }),
  v('gakusei', 'がくせい', 'student', 'A1', ['school'], { pronunciation: 'gakusei' }),
];

const JA_GRAMMAR: AuthoredGrammar[] = [
  {
    key: 'ja-wa-desu',
    title: 'X は Y です',
    cefr: 'A1',
    summary: 'The basic sentence: topic, は, then what it is, then です.',
    explanation:
      'Japanese marks the topic with は (written "ha" but pronounced "wa") and closes the sentence with です for politeness. わたしはトムです — "As for me, [I am] Tom". The topic is usually dropped once it is obvious, which is why real Japanese has far fewer pronouns than English.',
    examples: [
      { target: 'わたしはトムです。', native: 'I am Tom.' },
      { target: 'これはみずです。', native: 'This is water.' },
      { target: 'せんせいですか。', native: 'Are you a teacher?' },
    ],
    commonMistakes: [
      { wrong: 'わたしトムです。', right: 'わたしはトムです。', why: 'The topic needs the particle は.' },
      { wrong: 'わたしはトム。', right: 'わたしはトムです。', why: 'Without です the sentence is casual, which is wrong with someone you have just met.' },
    ],
  },
  {
    key: 'ja-particles-wo-ni',
    title: 'Particles を and に',
    cefr: 'A1',
    summary: 'を marks the object, に marks the destination or time.',
    explanation:
      'を (pronounced "o") marks what the action is done to: みずをください. に marks where you are going or when something happens: がっこうにいきます, しちじにおきます. Particles carry the grammar that English carries with word order, which is why word order in Japanese is far more flexible.',
    examples: [
      { target: 'みずをください。', native: 'Water, please.' },
      { target: 'えきにいきます。', native: 'I am going to the station.' },
      { target: 'しちじにおきます。', native: 'I get up at seven.' },
    ],
    commonMistakes: [
      { wrong: 'みずにください。', right: 'みずをください。', why: 'The thing you want is the object, so it takes を.' },
    ],
  },
  {
    key: 'ja-politeness',
    title: 'Politeness levels',
    cefr: 'A1',
    summary: 'です/ます is the safe register; casual forms come later.',
    explanation:
      'Japanese politeness is grammatical, not optional. The です/ます forms are appropriate with anyone you do not know well, and with anyone senior to you. The casual forms (だ, plain verbs) are for close friends and family. Starting a conversation with a stranger in casual Japanese is a real social error, not just informality.',
    examples: [
      { target: 'いきます', native: 'I go (polite)' },
      { target: 'いく', native: 'I go (casual)' },
    ],
    commonMistakes: [
      { wrong: 'なまえは？ (to a stranger)', right: 'おなまえはなんですか。', why: 'The polite form and the honorific お are expected with someone you have just met.' },
    ],
  },
];

const JA_CULTURE: AuthoredCulture[] = [
  {
    key: 'ja-sumimasen',
    title: 'すみません does three jobs',
    cefr: 'PRE_A1',
    topic: 'etiquette',
    variantCodes: [],
    body:
      'すみません means "excuse me", "sorry" and — often — "thank you", in the sense of "sorry to have troubled you". You will hear it used to get a waiter\'s attention, to apologise for bumping into someone, and to accept a favour. It is probably the single most useful word in Japanese.',
  },
  {
    key: 'ja-name-suffixes',
    title: 'さん and why you never use it about yourself',
    cefr: 'A1',
    topic: 'etiquette',
    variantCodes: [],
    body:
      'Attach さん to other people\'s names (たなかさん), never to your own. Use the family name unless invited otherwise. せんせい replaces さん for teachers and doctors. Getting this wrong is not offensive so much as immediately marking you as a beginner — and it is easy to fix.',
  },
  {
    key: 'ja-writing-systems',
    title: 'Three writing systems, one language',
    cefr: 'PRE_A1',
    topic: 'writing',
    variantCodes: [],
    body:
      'Japanese uses hiragana (native words and grammar), katakana (loanwords and emphasis) and kanji (characters borrowed from Chinese). Learners start with hiragana, add katakana, and pick up kanji gradually. Romaji — Japanese written in the Latin alphabet — is a crutch that slows reading down, so this course moves off it quickly.',
  },
];

const JA_SCENARIOS: AuthoredScenario[] = [
  {
    key: 'ja-self-introduction',
    title: 'Introducing yourself',
    setting: 'The first day of a Japanese class. The teacher asks you to introduce yourself.',
    partnerRole: 'A patient teacher who speaks slowly and politely',
    learnerRole: 'A new student',
    cefr: 'A1',
    goals: ['Greet the group', 'Give your name', 'Say where you are from', 'Close with よろしくおねがいします'],
    openingLine: 'はじめまして。じこしょうかいをおねがいします。',
    vocabulary: ['konnichiwa', 'watashi', 'desu', 'yoroshiku'],
  },
  {
    key: 'ja-convenience-store',
    title: 'At a convenience store',
    setting: 'A convenience store counter. You are buying water and bread.',
    partnerRole: 'A polite shop assistant using keigo',
    learnerRole: 'A customer',
    cefr: 'A1',
    goals: ['Ask for what you want', 'Ask the price', 'Pay', 'Thank them'],
    openingLine: 'いらっしゃいませ。',
    complications: ['The assistant asks whether you want a bag'],
    vocabulary: ['mizu', 'pan', 'kudasai', 'ikura', 'arigatou'],
  },
  {
    key: 'ja-asking-station',
    title: 'Asking where the station is',
    setting: 'A street corner in a Japanese city.',
    partnerRole: 'A helpful passer-by',
    learnerRole: 'A visitor',
    cefr: 'A1',
    goals: ['Get attention with すみません', 'Ask where the station is', 'Thank them'],
    openingLine: 'はい、なんでしょうか。',
    vocabulary: ['sumimasen', 'doko', 'eki', 'arigatou'],
  },
];

const TTS_SOURCE = 'lingonest-tts-pipeline';
const TTS_LICENCE = 'proprietary-generated';

const JA_DIALOGUES: { key: string; transcript: string; speeds?: ('slow' | 'normal' | 'natural')[] }[] = [
  { key: 'ja/pre-a1/u1/greetings', transcript: '— こんにちは。— こんにちは。— さようなら。— さようなら。' },
  { key: 'ja/pre-a1/u2/hiragana-a', transcript: 'あ、い、う、え、お' },
  { key: 'ja/pre-a1/u2/hiragana-ka', transcript: 'か、き、く、け、こ' },
  { key: 'ja/pre-a1/u3/numbers', transcript: 'いち、に、さん、し、ご、ろく、なな、はち、きゅう、じゅう' },
  { key: 'ja/a1/u1/introduction', transcript: '— はじめまして。わたしはトムです。アメリカからきました。よろしくおねがいします。', speeds: ['slow', 'normal'] },
  { key: 'ja/a1/u2/store', transcript: '— いらっしゃいませ。— みずとパンをください。— はい、さんびゃくえんです。— ありがとうございます。', speeds: ['slow', 'normal'] },
  { key: 'ja/a1/u3/station', transcript: '— すみません、えきはどこですか。— まっすぐいって、ひだりです。— ありがとうございます。', speeds: ['slow', 'normal'] },
];

const JA_MEDIA: AuthoredMedia[] = [
  ...JA_VOCABULARY.filter((item) => item.audio).map((item) => ({
    key: item.audio!,
    kind: 'audio' as const,
    path: `audio/${item.audio}.m4a`,
    source: TTS_SOURCE,
    licence: TTS_LICENCE,
    voice: 'ja-JP-female-1',
    speed: 'slow' as const,
    transcript: item.term,
  })),
  ...JA_DIALOGUES.flatMap((d) =>
    (d.speeds ?? ['normal']).map((speed) => ({
      key: speed === 'normal' ? d.key : `${d.key}-${speed}`,
      kind: 'audio' as const,
      path: `audio/${d.key}${speed === 'normal' ? '' : `-${speed}`}.m4a`,
      source: TTS_SOURCE,
      licence: TTS_LICENCE,
      voice: 'ja-JP-multi',
      speed,
      transcript: d.transcript,
    })),
  ),
  ...['ja/img/mizu', 'ja/img/pan', 'ja/img/eki'].map((key) => ({
    key,
    kind: 'image' as const,
    path: `images/${key}.webp`,
    source: 'lingonest-illustration-set',
    licence: 'proprietary-commissioned',
  })),
];

const JA_PRE_A1 = course({
  slug: 'ja-pre-a1-foundations',
  title: 'First Steps in Japanese',
  description:
    'Hiragana, the sounds of Japanese, greetings and numbers — the writing-system module that everything else depends on.',
  cefr: 'PRE_A1',
  units: [
    unit({
      slug: 'ja-pre-a1-u1',
      title: 'Greetings',
      objective: 'Greet people at any time of day.',
      theme: 'greetings',
      cefr: 'PRE_A1',
      realWorldTask: 'Greet a Japanese speaker appropriately for the time of day.',
      lessons: [
        lesson({
          slug: 'ja-pre-a1-u1-l1',
          title: 'こんにちは',
          objective: 'Use the three time-of-day greetings.',
          canDo: 'I can greet someone in Japanese at any time of day.',
          cefr: 'PRE_A1',
          minutes: 6,
          vocabulary: ['konnichiwa', 'ohayou', 'konbanwa', 'sayounara'],
          activities: [
            listen({
              audio: 'ja/pre-a1/u1/greetings',
              instruction: 'Listen to the greetings.',
              question: 'Which greeting is used during the day?',
              options: ['こんにちは', 'こんばんは', 'おはようございます'],
              answer: 'こんにちは',
              transcript: '— こんにちは。— こんにちは。— さようなら。— さようなら。',
              speed: 'slow',
              why: 'こんにちは covers roughly late morning to early evening.',
            }),
            wordMatch({
              instruction: 'Match each greeting to its time.',
              pairs: [
                ['おはようございます', 'morning'],
                ['こんにちは', 'daytime'],
                ['こんばんは', 'evening'],
              ],
              tags: ['vocab:ohayou', 'vocab:konnichiwa', 'vocab:konbanwa'],
            }),
            mcq({
              question: 'You arrive at work at 8am. What do you say?',
              options: ['おはようございます', 'こんばんは', 'さようなら'],
              answer: 'おはようございます',
              why: 'The polite ございます is expected at work; おはよう alone is for friends and family.',
              tags: ['vocab:ohayou', 'grammar:ja-politeness'],
            }),
            speak({ target: 'こんにちは', audio: 'ja/vocab/konnichiwa', phonetic: 'kon-nichi-wa' }),
            reviewChallenge({ count: 4 }),
          ],
        }),
        lesson({
          slug: 'ja-pre-a1-u1-l2',
          title: 'ありがとう and すみません',
          objective: 'Use the two courtesy words that carry most interactions.',
          canDo: 'I can thank someone and get their attention politely.',
          cefr: 'PRE_A1',
          minutes: 6,
          vocabulary: ['arigatou', 'sumimasen', 'hai', 'iie'],
          culture: ['ja-sumimasen'],
          activities: [
            mcq({
              question: 'You want to get a waiter\'s attention. What do you say?',
              options: ['すみません', 'ありがとうございます', 'さようなら'],
              answer: 'すみません',
              why: 'すみません works as "excuse me", "sorry" and even "thank you" for a favour.',
              tags: ['vocab:sumimasen', 'culture:sumimasen'],
            }),
            mcq({
              question: 'Someone holds a door for you. Which is most natural?',
              options: ['すみません', 'いいえ', 'こんにちは'],
              answer: 'すみません',
              why: 'Japanese often thanks by apologising for the trouble caused — one of the clearest differences from English.',
              tags: ['culture:sumimasen'],
            }),
            dialogueCompletion({
              lines: [
                { speaker: 'You', text: '___' },
                { speaker: 'てんいん', text: 'はい、どうぞ。' },
              ],
              options: ['すみません', 'さようなら', 'いいえ'],
              answer: 'すみません',
              why: 'Getting attention comes before the request.',
            }),
            speak({ target: 'ありがとうございます', audio: 'ja/vocab/arigatou', phonetic: 'arigatō gozaimasu' }),
            reviewChallenge({ count: 5 }),
          ],
        }),
      ],
    }),
    unit({
      slug: 'ja-pre-a1-u2',
      title: 'Hiragana',
      objective: 'Read the first rows of hiragana.',
      theme: 'writing',
      cefr: 'PRE_A1',
      realWorldTask: 'Read a short hiragana word aloud without romaji.',
      lessons: [
        lesson({
          slug: 'ja-pre-a1-u2-l1',
          title: 'あいうえお',
          objective: 'Read and write the five vowels.',
          canDo: 'I can read the five hiragana vowels.',
          cefr: 'PRE_A1',
          minutes: 8,
          culture: ['ja-writing-systems'],
          activities: [
            listen({
              audio: 'ja/pre-a1/u2/hiragana-a',
              instruction: 'Listen to the five vowels.',
              question: 'How many vowel sounds does Japanese have?',
              options: ['Five', 'Twelve', 'Three'],
              answer: 'Five',
              transcript: 'あ、い、う、え、お',
              speed: 'slow',
              why: 'Every hiragana character is built on these five vowels, which is what makes the system learnable in days rather than months.',
            }),
            wordMatch({
              instruction: 'Match each character to its sound.',
              pairs: [
                ['あ', 'a'],
                ['い', 'i'],
                ['う', 'u'],
                ['え', 'e'],
                ['お', 'o'],
              ],
            }),
            audioChoice({
              audio: 'ja/pre-a1/u2/hiragana-a',
              instruction: 'Listen. Which character comes first?',
              options: ['あ', 'お', 'う'],
              answer: 'あ',
              speed: 'slow',
              why: 'The syllabary is always recited in the order あいうえお, and dictionaries follow it too.',
            }),
            spelling({
              instruction: 'Write the hiragana for "water".',
              answer: 'みず',
              why: 'みず — two characters, no spaces. Japanese does not separate words with spaces.',
              tags: ['vocab:mizu'],
            }),
            reviewChallenge({ count: 5 }),
          ],
        }),
        lesson({
          slug: 'ja-pre-a1-u2-l2',
          title: 'かきくけこ',
          objective: 'Read the k-row.',
          canDo: 'I can read the first two rows of hiragana.',
          cefr: 'PRE_A1',
          minutes: 8,
          activities: [
            listen({
              audio: 'ja/pre-a1/u2/hiragana-ka',
              instruction: 'Listen to the k-row.',
              question: 'What is the pattern?',
              options: ['Consonant + each of the five vowels', 'Random sounds', 'Five consonants'],
              answer: 'Consonant + each of the five vowels',
              transcript: 'か、き、く、け、こ',
              speed: 'slow',
              why: 'Each row applies one consonant to the five vowels — learn the pattern once, and the rest of the syllabary follows.',
            }),
            wordMatch({
              instruction: 'Match each character.',
              pairs: [
                ['か', 'ka'],
                ['き', 'ki'],
                ['く', 'ku'],
                ['け', 'ke'],
                ['こ', 'ko'],
              ],
            }),
            categorize({
              instruction: 'Sort each character by its row.',
              categories: ['vowel row', 'k row'],
              mapping: { あ: 'vowel row', い: 'vowel row', か: 'k row', き: 'k row', こ: 'k row' },
              why: 'The syllabary is a grid: rows are consonants, columns are vowels.',
            }),
            reviewChallenge({ count: 6 }),
          ],
        }),
        lesson({
          slug: 'ja-pre-a1-u2-l3',
          title: 'Numbers and Review',
          objective: 'Count to ten and review hiragana.',
          canDo: 'I can count to ten and read basic hiragana.',
          cefr: 'PRE_A1',
          minutes: 8,
          isReview: true,
          vocabulary: ['ichi', 'ni', 'san', 'juu', 'mizu', 'pan'],
          activities: [
            listen({
              audio: 'ja/pre-a1/u3/numbers',
              instruction: 'Listen to one to ten.',
              question: 'Which number is "さん"?',
              options: ['Three', 'One', 'Ten'],
              answer: 'Three',
              transcript: 'いち、に、さん、し、ご、ろく、なな、はち、きゅう、じゅう',
              speed: 'slow',
              why: 'いち、に、さん — one, two, three.',
            }),
            timedChallenge({
              instruction: 'Say the Japanese number.',
              items: [
                ['1', 'いち'],
                ['2', 'に'],
                ['3', 'さん'],
                ['10', 'じゅう'],
              ],
              seconds: 60,
            }),
            mcq({
              question: 'Why is パン written in katakana rather than hiragana?',
              options: ['It is a loanword', 'It is a name', 'It is a number'],
              answer: 'It is a loanword',
              why: 'Katakana marks words borrowed from other languages — パン comes from Portuguese "pão".',
              tags: ['vocab:pan', 'culture:writing-systems'],
            }),
            realWorldTask({
              situation: 'You are at a convenience store and want water and bread.',
              goals: ['Get attention politely', 'Ask for two items', 'Thank them'],
            }),
          ],
        }),
        lesson({
          slug: 'ja-pre-a1-u2-l4',
          title: 'Producing Japanese',
          objective: 'Move from recognising kana to producing words and short phrases.',
          canDo: 'I can write and say basic Japanese words without romaji.',
          cefr: 'PRE_A1',
          minutes: 9,
          vocabulary: ['mizu', 'pan', 'sumimasen', 'arigatou'],
          activities: [
            spelling({
              instruction: 'Write "bread" in katakana.',
              answer: 'パン',
              why: 'Loanwords are written in katakana, which is why パン is not written in hiragana.',
              tags: ['vocab:pan'],
            }),
            spelling({
              instruction: 'Write "hello" in hiragana.',
              answer: 'こんにちは',
              why: 'Note the final は — written "ha" but pronounced "wa", because it is the topic particle in origin.',
              tags: ['vocab:konnichiwa'],
            }),
            buildSentence({
              target: 'みず を ください',
              tokens: ['ください', 'みず', 'を'],
              instruction: 'Ask for water.',
              why: 'The object takes を, and ください closes a polite request.',
              tags: ['grammar:ja-particles-wo-ni'],
            }),
            speak({ target: 'すみません、みずをください。', phonetic: 'sumimasen, mizu o kudasai' }),
            speakResponse({
              situation: 'You are at a counter and want water.',
              question: 'いらっしゃいませ。',
              goal: 'Get attention and ask for water politely',
              criteria: ['Uses すみません or responds appropriately', 'Uses を', 'Uses ください'],
            }),
            realWorldTask({
              situation: 'Buy water at a Japanese convenience store and thank the assistant.',
              goals: ['Ask for the item', 'Understand the price', 'Thank them'],
            }),
          ],
        }),
        lesson({
          slug: 'ja-pre-a1-u2-l5',
          title: 'Pre-A1 Checkpoint',
          objective: 'Check the greetings, the kana and the first requests.',
          canDo: 'I can greet, read basic hiragana, count, and ask for something politely.',
          cefr: 'PRE_A1',
          minutes: 14,
          isCheckpoint: true,
          activities: [
            listen({
              audio: 'ja/pre-a1/u3/numbers',
              instruction: 'Listening.',
              question: 'Which number is "じゅう"?',
              options: ['Ten', 'One', 'Three'],
              answer: 'Ten',
              transcript: 'いち、に、さん、し、ご、ろく、なな、はち、きゅう、じゅう',
              speed: 'normal',
              why: 'じゅう closes the count at ten.',
            }),
            wordMatch({
              instruction: 'Reading: match each character to its sound.',
              pairs: [
                ['あ', 'a'],
                ['か', 'ka'],
                ['み', 'mi'],
                ['ず', 'zu'],
              ],
            }),
            timedChallenge({
              instruction: 'Vocabulary.',
              items: [
                ['hello (daytime)', 'こんにちは'],
                ['thank you', 'ありがとうございます'],
                ['excuse me', 'すみません'],
                ['water', 'みず'],
                ['three', 'さん'],
              ],
              seconds: 100,
            }),
            spelling({
              instruction: 'Write "water" in hiragana.',
              answer: 'みず',
              why: 'Two characters, no spaces — Japanese does not separate words.',
              tags: ['vocab:mizu'],
            }),
            buildSentence({
              target: 'みず を ください',
              tokens: ['ください', 'を', 'みず'],
              instruction: 'Ask for water politely.',
              why: 'The object particle を, then ください.',
              tags: ['grammar:ja-particles-wo-ni'],
            }),
            speakResponse({
              situation: 'Speaking: you enter a shop and the assistant greets you.',
              question: 'いらっしゃいませ。',
              goal: 'Ask for two items politely and thank them',
              criteria: ['Uses ください', 'Names two items', 'Thanks the assistant'],
            }),
            realWorldTask({
              situation: 'Greet someone in the morning, buy water and bread, and thank the shop assistant.',
              goals: ['Greet appropriately for the time', 'Ask for two items', 'Understand the price', 'Thank them'],
              constraints: ['Polite register throughout'],
            }),
          ],
        }),
      ],
    }),
  ],
});

const JA_A1 = course({
  slug: 'ja-a1-survival',
  title: 'Japanese A1: Getting By',
  description:
    'Introduce yourself, buy things, ask where something is, and talk about your family — all in the polite register you will actually need.',
  cefr: 'A1',
  units: [
    unit({
      slug: 'ja-a1-u1',
      title: 'Introducing Yourself',
      objective: 'Give a proper Japanese self-introduction.',
      theme: 'greetings',
      cefr: 'A1',
      realWorldTask: 'Give a 30-second self-introduction to a Japanese speaker.',
      lessons: [
        lesson({
          slug: 'ja-a1-u1-l1',
          title: 'わたしは…です',
          objective: 'Build the basic Japanese sentence.',
          canDo: 'I can say who I am using は and です.',
          cefr: 'A1',
          minutes: 9,
          vocabulary: ['watashi', 'namae', 'desu'],
          grammar: ['ja-wa-desu'],
          activities: [
            listen({
              audio: 'ja/a1/u1/introduction',
              instruction: 'Listen to the self-introduction.',
              question: 'Where is the speaker from?',
              options: ['America', 'Australia', 'England'],
              answer: 'America',
              transcript: '— はじめまして。わたしはトムです。アメリカからきました。よろしくおねがいします。',
              speed: 'slow',
              why: 'アメリカからきました — I came from America.',
            }),
            mcq({
              question: 'What does は do in わたしはトムです?',
              options: ['Marks the topic', 'Means "and"', 'Makes it a question'],
              answer: 'Marks the topic',
              why: 'は marks what the sentence is about. It is written "ha" but pronounced "wa".',
              tags: ['grammar:ja-wa-desu'],
            }),
            correctGrammar({
              incorrect: 'わたしトムです。',
              correct: 'わたしはトムです。',
              why: 'The topic needs the particle は.',
              topic: 'ja-wa-desu',
            }),
            buildSentence({
              target: 'わたし は トム です',
              tokens: ['です', 'わたし', 'トム', 'は'],
              instruction: 'Say "I am Tom".',
              why: 'Topic, particle, what it is, then です.',
              tags: ['grammar:ja-wa-desu'],
            }),
            speak({ target: 'わたしはトムです', phonetic: 'watashi wa Tomu desu' }),
            converse({
              scenario: 'ja-self-introduction',
              goals: ['Greet the group', 'Give your name', 'Say where you are from', 'Close with よろしくおねがいします'],
              minTurns: 4,
            }),
          ],
        }),
        lesson({
          slug: 'ja-a1-u1-l2',
          title: 'Politeness',
          objective: 'Use the です/ます register consistently.',
          canDo: 'I can speak politely to someone I have just met.',
          cefr: 'A1',
          minutes: 8,
          vocabulary: ['yoroshiku', 'sensei', 'gakusei', 'nihongo'],
          grammar: ['ja-politeness'],
          culture: ['ja-name-suffixes'],
          activities: [
            mcq({
              question: 'How do you refer to yourself with さん?',
              options: ['You never do', 'Always', 'Only in writing'],
              answer: 'You never do',
              why: 'さん is applied to other people, never to yourself.',
              tags: ['culture:name-suffixes'],
            }),
            correctGrammar({
              incorrect: 'わたしはたなかさんです。(introducing yourself as Tanaka)',
              correct: 'わたしはたなかです。',
              why: 'Drop さん when talking about yourself.',
              topic: 'ja-politeness',
            }),
            categorize({
              instruction: 'Sort each form by register.',
              categories: ['polite', 'casual'],
              mapping: { 'いきます': 'polite', 'いく': 'casual', 'です': 'polite', 'だ': 'casual' },
              why: 'Politeness in Japanese is grammatical, so choosing the wrong form is a grammar error as much as a social one.',
              tags: ['grammar:ja-politeness'],
            }),
            speakResponse({
              situation: 'You are introducing yourself to a new manager.',
              question: 'はじめまして。じこしょうかいをおねがいします。',
              goal: 'Give a polite self-introduction',
              criteria: ['Uses です', 'Gives name and origin', 'Closes with よろしくおねがいします'],
            }),
            reviewChallenge({ count: 6 }),
          ],
        }),
      ],
    }),
    unit({
      slug: 'ja-a1-u2',
      title: 'Shopping',
      objective: 'Buy things and understand prices.',
      theme: 'shopping',
      cefr: 'A1',
      realWorldTask: 'Buy two items at a convenience store and understand the total.',
      lessons: [
        lesson({
          slug: 'ja-a1-u2-l1',
          title: 'をください',
          objective: 'Ask for what you want.',
          canDo: 'I can ask for something in a shop.',
          cefr: 'A1',
          minutes: 9,
          vocabulary: ['kudasai', 'ikura', 'mizu', 'pan'],
          grammar: ['ja-particles-wo-ni'],
          activities: [
            listen({
              audio: 'ja/a1/u2/store',
              instruction: 'Listen at the shop counter.',
              question: 'How much is the total?',
              options: ['300 yen', '30 yen', '3000 yen'],
              answer: '300 yen',
              transcript: '— いらっしゃいませ。— みずとパンをください。— はい、さんびゃくえんです。— ありがとうございます。',
              speed: 'slow',
              why: 'さんびゃくえん — three hundred yen.',
            }),
            fillBlank({
              template: 'みず{{blank}}ください。',
              answers: ['を'],
              wordBank: ['を', 'は', 'に'],
              why: 'The thing you want is the object, marked by を.',
              tags: ['grammar:ja-particles-wo-ni'],
            }),
            correctGrammar({
              incorrect: 'みずにください。',
              correct: 'みずをください。',
              why: 'に marks a destination; the object of the request takes を.',
              topic: 'ja-particles-wo-ni',
            }),
            translate({
              source: 'Water and bread, please.',
              answer: 'みずとパンをください。',
              alternatives: ['みずとパンをください'],
              why: 'と joins the two nouns; を marks the whole thing being requested.',
              tags: ['grammar:ja-particles-wo-ni'],
            }),
            converse({
              scenario: 'ja-convenience-store',
              goals: ['Ask for what you want', 'Ask the price', 'Pay', 'Thank them'],
              minTurns: 5,
            }),
          ],
        }),
      ],
    }),
    unit({
      slug: 'ja-a1-u3',
      title: 'Getting Around',
      objective: 'Ask where something is.',
      theme: 'travel',
      cefr: 'A1',
      realWorldTask: 'Ask a passer-by where the station is and understand the answer.',
      lessons: [
        lesson({
          slug: 'ja-a1-u3-l1',
          title: 'どこですか',
          objective: 'Ask where a place is.',
          canDo: 'I can ask where something is.',
          cefr: 'A1',
          minutes: 9,
          vocabulary: ['doko', 'eki', 'sumimasen'],
          activities: [
            listen({
              audio: 'ja/a1/u3/station',
              instruction: 'Listen to the exchange.',
              question: 'Which way is the station?',
              options: ['Straight, then left', 'Straight, then right', 'Behind you'],
              answer: 'Straight, then left',
              transcript: '— すみません、えきはどこですか。— まっすぐいって、ひだりです。— ありがとうございます。',
              speed: 'slow',
              why: 'まっすぐいって、ひだりです — go straight, then it is on the left.',
            }),
            buildSentence({
              target: 'えき は どこ です か',
              tokens: ['か', 'えき', 'です', 'は', 'どこ'],
              instruction: 'Ask where the station is.',
              why: 'The question particle か closes the sentence — Japanese needs no change in word order for questions.',
              tags: ['grammar:ja-wa-desu'],
            }),
            mcq({
              question: 'What turns a Japanese statement into a question?',
              options: ['Adding か at the end', 'Changing the word order', 'Raising the pitch only'],
              answer: 'Adding か at the end',
              why: 'か is the question particle; the rest of the sentence is unchanged.',
              tags: ['grammar:ja-wa-desu'],
            }),
            converse({
              scenario: 'ja-asking-station',
              goals: ['Get attention with すみません', 'Ask where the station is', 'Thank them'],
              minTurns: 4,
            }),
          ],
        }),
      ],
    }),
    unit({
      slug: 'ja-a1-u4',
      title: 'Family and Review',
      objective: 'Talk about your family and consolidate the level.',
      theme: 'family',
      cefr: 'A1',
      realWorldTask: 'Tell a Japanese speaker about your family in three sentences.',
      lessons: [
        lesson({
          slug: 'ja-a1-u4-l1',
          title: 'Family Words',
          objective: 'Name family members, and notice that Japanese has two sets of words.',
          canDo: 'I can talk about my family.',
          cefr: 'A1',
          minutes: 9,
          vocabulary: ['kazoku', 'ani', 'ane'],
          activities: [
            wordMatch({
              instruction: 'Match each word.',
              pairs: [
                ['かぞく', 'family'],
                ['あに', 'my older brother'],
                ['あね', 'my older sister'],
              ],
              tags: ['vocab:kazoku', 'vocab:ani', 'vocab:ane'],
            }),
            mcq({
              question: 'Why does Japanese have two words for "older brother"?',
              options: [
                'One is for your own family, one for someone else’s',
                'One is written, one spoken',
                'They are regional variants',
              ],
              answer: 'One is for your own family, one for someone else’s',
              why: 'あに is your own brother; おにいさん is someone else\'s. Humility about your own family is built into the vocabulary.',
              tags: ['vocab:ani'],
            }),
            buildSentence({
              target: 'あに は がくせい です',
              tokens: ['です', 'あに', 'がくせい', 'は'],
              instruction: 'Say your older brother is a student.',
              why: 'The same topic-comment pattern as わたしはトムです.',
              tags: ['grammar:ja-wa-desu'],
            }),
            reviewChallenge({ count: 6 }),
          ],
        }),
        lesson({
          slug: 'ja-a1-u4-l2',
          title: 'A1 Checkpoint',
          objective: 'Assess the level.',
          canDo: 'I can introduce myself, buy things and ask for directions in polite Japanese.',
          cefr: 'A1',
          minutes: 16,
          isCheckpoint: true,
          activities: [
            listen({
              audio: 'ja/a1/u1/introduction',
              instruction: 'Listening at normal speed.',
              question: 'How does the speaker close the introduction?',
              options: ['よろしくおねがいします', 'さようなら', 'ありがとう'],
              answer: 'よろしくおねがいします',
              transcript: '— はじめまして。わたしはトムです。アメリカからきました。よろしくおねがいします。',
              speed: 'normal',
              why: 'A self-introduction almost always ends this way.',
            }),
            timedChallenge({
              instruction: 'Translate as many as you can.',
              items: [
                ['excuse me', 'すみません'],
                ['thank you', 'ありがとうございます'],
                ['water', 'みず'],
                ['where', 'どこ'],
                ['station', 'えき'],
                ['please give me', 'ください'],
              ],
              seconds: 100,
            }),
            correctGrammar({
              incorrect: 'わたしトムです。みずにください。',
              correct: 'わたしはトムです。みずをください。',
              why: 'Two particle errors: the topic needs は, and the object of a request needs を.',
              topic: 'ja-wa-desu',
            }),
            speakResponse({
              situation: 'Speaking: introduce yourself to a Japanese class.',
              question: 'じこしょうかいをおねがいします。',
              goal: 'Give a complete polite self-introduction',
              criteria: ['Uses は and です correctly', 'Says name and origin', 'Closes appropriately'],
            }),
            write({
              task: 'Writing: write a four-sentence self-introduction in hiragana and katakana.',
              goal: 'Produce a written self-introduction',
              criteria: ['Uses は correctly', 'Uses です', 'No romaji'],
              minWords: 10,
            }),
            realWorldTask({
              situation:
                'You arrive in a Japanese city, buy water at a convenience store, then ask a passer-by where the station is.',
              goals: ['Buy two items and pay', 'Ask where the station is', 'Thank both people appropriately'],
              constraints: ['Polite register throughout'],
            }),
          ],
        }),
      ],
    }),
  ],
});

export const JA_CURRICULUM: AuthoredCurriculum = {
  languageCode: 'ja',
  courses: [JA_PRE_A1, JA_A1],
  vocabulary: JA_VOCABULARY,
  grammar: JA_GRAMMAR,
  culture: JA_CULTURE,
  scenarios: JA_SCENARIOS,
  media: JA_MEDIA,
};
