import {
  buildSentence,
  converse,
  correctGrammar,
  course,
  dialogueCompletion,
  dictation,
  fillBlank,
  lesson,
  listen,
  mcq,
  multiAnswer,
  realWorldTask,
  reviewChallenge,
  speak,
  speakResponse,
  spelling,
  storyCompletion,
  tapTranslation,
  timedChallenge,
  unit,
  wordMatch,
  write,
} from '../../dsl/builders';
import type { AuthoredCurriculum } from '../../dsl/types';
import { EN_CULTURE, EN_GRAMMAR, EN_MEDIA, EN_SCENARIOS, EN_VOCABULARY } from './shared';

const EN_PRE_A1 = course({
  slug: 'en-pre-a1-foundations',
  title: 'First Steps in English',
  description:
    'Greetings, courtesy, numbers and the phrases that keep a conversation going before you have the words for anything else.',
  cefr: 'PRE_A1',
  units: [
    unit({
      slug: 'en-pre-a1-u1',
      title: 'Hello and Goodbye',
      objective: 'Greet someone, thank them, and say goodbye.',
      theme: 'greetings',
      cefr: 'PRE_A1',
      realWorldTask: 'Greet a neighbour or colleague and say goodbye without switching languages.',
      lessons: [
        lesson({
          slug: 'en-pre-a1-u1-l1',
          title: 'Hello',
          objective: 'Greet someone and understand a greeting back.',
          canDo: 'I can say hello and goodbye.',
          cefr: 'PRE_A1',
          minutes: 5,
          vocabulary: ['hello', 'goodbye'],
          activities: [
            listen({
              audio: 'en/pre-a1/u1/greetings',
              instruction: 'Listen to the short exchange.',
              question: 'What does the second speaker say?',
              options: ['Hi, good morning.', 'Goodbye.', 'Thank you.'],
              answer: 'Hi, good morning.',
              transcript: '— Hello. — Hi, good morning. — Goodbye. — See you later.',
              speed: 'slow',
              why: 'A greeting is normally returned before anything else.',
            }),
            wordMatch({
              instruction: 'Match each word to when you use it.',
              pairs: [
                ['hello', 'meeting someone'],
                ['goodbye', 'leaving'],
              ],
              tags: ['vocab:hello', 'vocab:goodbye'],
            }),
            mcq({
              question: 'It is 9 in the morning. What is the most natural greeting?',
              options: ['Good morning', 'Good night', 'Goodbye'],
              answer: 'Good morning',
              why: '"Good night" is only used when leaving at night, never as a greeting.',
              tags: ['vocab:hello'],
            }),
            speak({ target: 'Good morning', audio: 'en/vocab/hello' }),
            reviewChallenge({ count: 4 }),
          ],
        }),
        lesson({
          slug: 'en-pre-a1-u1-l2',
          title: 'Please and Thank You',
          objective: 'Use the courtesy words English speakers expect constantly.',
          canDo: 'I can say please, thank you and sorry.',
          cefr: 'PRE_A1',
          minutes: 6,
          vocabulary: ['please', 'thank-you', 'sorry'],
          activities: [
            listen({
              audio: 'en/pre-a1/u1/courtesy',
              instruction: 'Listen to four short exchanges.',
              question: 'What is the reply to "thank you"?',
              options: ["You're welcome.", 'Please.', 'Sorry.'],
              answer: "You're welcome.",
              transcript: '— Thank you. — You’re welcome. — Please. — Sorry.',
              speed: 'slow',
              why: '"You\'re welcome" is the standard reply; "no problem" is a common informal alternative.',
            }),
            mcq({
              question: 'You need to get past someone. What do you say?',
              options: ['Excuse me', 'Thank you', 'Please'],
              answer: 'Excuse me',
              why: '"Excuse me" gets attention or asks for space; "sorry" apologises for something you did.',
              tags: ['vocab:sorry'],
            }),
            dialogueCompletion({
              lines: [
                { speaker: 'You', text: 'A coffee, ___.' },
                { speaker: 'Server', text: 'Here you go.' },
                { speaker: 'You', text: 'Thank you.' },
              ],
              options: ['please', 'sorry', 'goodbye'],
              answer: 'please',
              why: 'English adds "please" to a request; leaving it out sounds abrupt.',
              tags: ['vocab:please'],
            }),
            speak({ target: 'Thank you very much', audio: 'en/vocab/thank-you' }),
            reviewChallenge({ count: 5 }),
          ],
        }),
        lesson({
          slug: 'en-pre-a1-u1-l3',
          title: 'Numbers and Review',
          objective: 'Count and review the unit.',
          canDo: 'I can count to ten and use basic courtesy.',
          cefr: 'PRE_A1',
          minutes: 7,
          isReview: true,
          vocabulary: ['one', 'two', 'three', 'ten', 'twenty', 'water', 'bread', 'yes', 'no'],
          activities: [
            wordMatch({
              instruction: 'Match the number to the digit.',
              pairs: [
                ['one', '1'],
                ['two', '2'],
                ['three', '3'],
                ['ten', '10'],
              ],
              tags: ['vocab:one', 'vocab:two', 'vocab:three'],
            }),
            spelling({
              instruction: 'You hear "water". Write it.',
              answer: 'water',
              why: 'English spelling rarely matches the sound, so writing words down early pays off.',
              tags: ['vocab:water'],
            }),
            timedChallenge({
              instruction: 'Say the English for each.',
              items: [
                ['1', 'one'],
                ['2', 'two'],
                ['3', 'three'],
                ['10', 'ten'],
              ],
              seconds: 45,
            }),
            realWorldTask({
              situation: 'You are buying two bottles of water. Ask for them politely and thank the cashier.',
              goals: ['Ask for two waters', 'Use please', 'Thank them'],
            }),
          ],
        }),
        lesson({
          slug: 'en-pre-a1-u1-l4',
          title: 'Pre-A1 Checkpoint',
          objective: 'Check that the basics have stuck.',
          canDo: 'I can greet, thank, count and ask for something politely.',
          cefr: 'PRE_A1',
          minutes: 12,
          isCheckpoint: true,
          activities: [
            listen({
              audio: 'en/pre-a1/u1/courtesy',
              instruction: 'Listening.',
              question: 'Which phrase is the reply to "thank you"?',
              options: ["You're welcome.", 'Please.', 'Sorry.'],
              answer: "You're welcome.",
              transcript: '— Thank you. — You’re welcome. — Please. — Sorry.',
              speed: 'normal',
              why: 'Recognising the reply matters as much as producing the thanks.',
            }),
            timedChallenge({
              instruction: 'Vocabulary.',
              items: [
                ['a greeting', 'hello'],
                ['gratitude', 'thank you'],
                ['a request word', 'please'],
                ['the number 3', 'three'],
                ['the number 10', 'ten'],
              ],
              seconds: 90,
            }),
            buildSentence({
              target: 'Two waters please',
              tokens: ['please', 'Two', 'waters'],
              instruction: 'Ask for two waters politely.',
              why: 'The polite word comes at the end of a short request.',
            }),
            speak({ target: 'Good morning. Two waters, please. Thank you.' }),
            speakResponse({
              situation: 'You are at a counter buying water.',
              question: 'Hi, what can I get you?',
              goal: 'Order politely and thank them',
              criteria: ['Names what they want', 'Uses please', 'Thanks the server'],
            }),
            realWorldTask({
              situation: 'Greet a neighbour, ask for something small, and say goodbye — all in English.',
              goals: ['Greet appropriately', 'Make a polite request', 'Thank them', 'Say goodbye'],
            }),
          ],
        }),
      ],
    }),
  ],
});

const EN_A1 = course({
  slug: 'en-a1-everyday',
  title: 'English A1: Getting Started',
  description:
    'Introduce yourself, talk about your family and job, make an appointment, and handle the everyday exchanges of a new country.',
  cefr: 'A1',
  units: [
    unit({
      slug: 'en-a1-u1',
      title: 'Introducing Yourself',
      objective: 'Say who you are and ask about someone else.',
      theme: 'greetings',
      cefr: 'A1',
      realWorldTask: 'Introduce yourself to a new colleague and ask two questions about them.',
      lessons: [
        lesson({
          slug: 'en-a1-u1-l1',
          title: 'I am…',
          objective: 'Use "to be" to say who you are.',
          canDo: 'I can introduce myself using "I am".',
          cefr: 'A1',
          minutes: 8,
          vocabulary: ['my-name-is', 'nice-to-meet-you'],
          grammar: ['en-be'],
          activities: [
            listen({
              audio: 'en/a1/u1/introductions',
              instruction: 'Listen to two people meeting.',
              question: 'What is the second speaker called?',
              options: ['Chris', 'Ana', 'Sam'],
              answer: 'Chris',
              transcript: '— Hi, I’m Ana. — Nice to meet you, Ana. I’m Chris. — Nice to meet you too.',
              speed: 'slow',
              why: '"I\'m Chris" — the contraction of "I am".',
            }),
            fillBlank({
              template: 'Hi, I {{blank}} Ana.',
              answers: ['am'],
              wordBank: ['am', 'is', 'are'],
              why: '"I" always takes "am".',
              tags: ['grammar:en-be'],
            }),
            correctGrammar({
              incorrect: 'I nurse.',
              correct: 'I am a nurse.',
              why: 'English needs both the verb "to be" and an article before a profession.',
              topic: 'en-be',
            }),
            multiAnswer({
              question: 'Which sentences are correct?',
              options: ['She is a teacher.', 'They are at work.', 'He are tired.', 'I is ready.'],
              answers: ['She is a teacher.', 'They are at work.'],
              why: '"He" takes is; "I" takes am.',
              tags: ['grammar:en-be'],
            }),
            speak({ target: "Hi, I'm — nice to meet you." }),
            converse({
              scenario: 'en-first-day-introductions',
              goals: ['Greet them', 'Say your name and role', 'Ask a question back'],
              minTurns: 4,
            }),
          ],
        }),
        lesson({
          slug: 'en-a1-u1-l2',
          title: 'Where Are You From?',
          objective: 'Say where you are from and where you live.',
          canDo: 'I can say where I am from and where I live now.',
          cefr: 'A1',
          minutes: 8,
          grammar: ['en-be', 'en-present-simple'],
          activities: [
            tapTranslation({
              source: "I'm from Guatemala, but I live in Chicago now.",
              options: [
                'Origin and current home',
                'Two places I have visited',
                'Where I work',
              ],
              answer: 'Origin and current home',
              direction: 'target_to_native',
              why: 'English separates where you are from ("be from") and where you live ("live in").',
              tags: ['grammar:en-be'],
            }),
            fillBlank({
              template: 'She {{blank}} from Poland and {{blank}} in Boston.',
              answers: ['is', 'lives'],
              wordBank: ['is', 'lives', 'are', 'live'],
              why: 'Third person singular takes "is" and the -s ending on the verb.',
              tags: ['grammar:en-present-simple'],
            }),
            correctGrammar({
              incorrect: 'He live in New York.',
              correct: 'He lives in New York.',
              why: 'Third person singular adds -s in the present simple.',
              topic: 'en-present-simple',
            }),
            speakResponse({
              situation: 'A colleague asks about your background.',
              question: 'So where are you from originally?',
              goal: 'Say where you are from and where you live now',
              criteria: ['Uses "be from" correctly', 'Names both places', 'Asks a question back'],
            }),
            reviewChallenge({ count: 6 }),
          ],
        }),
        lesson({
          slug: 'en-a1-u1-l3',
          title: 'Small Talk',
          objective: 'Handle "How are you?" the way it is actually used.',
          canDo: 'I can handle everyday small talk.',
          cefr: 'A1',
          minutes: 8,
          vocabulary: ['how-are-you', 'excuse-me'],
          culture: ['en-small-talk'],
          activities: [
            mcq({
              question: 'A cashier says "Hi, how are you?". What is the expected reply?',
              options: ['Good, thanks — you?', 'A description of your health', 'Nothing'],
              answer: 'Good, thanks — you?',
              why: 'In the US this is a greeting, not a real question. A short answer and the question returned is the whole exchange.',
              tags: ['culture:small-talk'],
            }),
            dialogueCompletion({
              lines: [
                { speaker: 'Colleague', text: "Morning! How's it going?" },
                { speaker: 'You', text: '___' },
              ],
              options: ['Good, thanks. You?', 'I am sick since Tuesday.', 'Goodbye.'],
              answer: 'Good, thanks. You?',
              why: 'Short, positive, and hand the question back.',
            }),
            speak({ target: "Good, thanks — how about you?" }),
            reviewChallenge({ count: 5 }),
          ],
        }),
        lesson({
          slug: 'en-a1-u1-l4',
          title: 'Unit 1 Review',
          objective: 'Put a full introduction together.',
          canDo: 'I can introduce myself completely.',
          cefr: 'A1',
          minutes: 9,
          isReview: true,
          vocabulary: ['family', 'mother', 'father', 'brother', 'sister'],
          activities: [
            dictation({
              audio: 'en/a1/u1/introductions',
              answer: "Hi, I'm Ana",
              alternatives: ['hi im ana', 'Hi, I am Ana'],
              instruction: 'Listen and write the first line.',
              speed: 'slow',
              why: 'Contractions are how people actually speak, so they are worth writing out.',
            }),
            storyCompletion({
              story: "Hi, I {{blank}} Marco. I {{blank}} from Peru and I {{blank}} in Miami.",
              answers: ['am', 'am', 'live'],
              wordBank: ['am', 'live', 'is', 'lives'],
              why: '"Be" for identity and origin, "live" for where you are now.',
            }),
            write({
              task: 'Write four sentences introducing yourself: name, origin, where you live, and what you do.',
              goal: 'Produce a written self-introduction',
              criteria: ['Correct forms of "to be"', 'Article before the profession', 'Four sentences'],
              minWords: 20,
            }),
            realWorldTask({
              situation: 'It is your first day at a new job and someone introduces themselves.',
              goals: ['Introduce yourself', 'Say what you do', 'Ask them a question'],
            }),
          ],
        }),
      ],
    }),
    unit({
      slug: 'en-a1-u2',
      title: 'Work and Schedules',
      objective: 'Talk about your job, your hours and your schedule.',
      theme: 'work',
      cefr: 'A1',
      realWorldTask: 'Explain your work schedule to someone and ask about theirs.',
      lessons: [
        lesson({
          slug: 'en-a1-u2-l1',
          title: 'What Do You Do?',
          objective: 'Say what your job is.',
          canDo: 'I can say what my job is and ask someone else.',
          cefr: 'A1',
          minutes: 8,
          vocabulary: ['work', 'job', 'manager'],
          grammar: ['en-articles'],
          activities: [
            listen({
              audio: 'en/a1/u2/workplace',
              instruction: 'Listen to the conversation about work.',
              question: 'When does the speaker work?',
              options: ['Nights', 'Mornings', 'Weekends only'],
              answer: 'Nights',
              transcript: '— What do you do? — I’m a nurse. I work nights at the hospital. — That’s a hard schedule.',
              speed: 'slow',
              why: '"I work nights" — the plural is how English expresses a regular night shift.',
            }),
            correctGrammar({
              incorrect: 'I am nurse.',
              correct: 'I am a nurse.',
              why: 'English needs an article before a countable profession — a difference from Spanish and many other languages.',
              topic: 'en-articles',
            }),
            fillBlank({
              template: 'She works as {{blank}} engineer.',
              answers: ['an'],
              wordBank: ['an', 'a', 'the'],
              why: '"An" comes before a vowel sound.',
              tags: ['grammar:en-articles'],
            }),
            speakResponse({
              situation: 'Someone at a community event asks about your job.',
              question: 'So what do you do?',
              goal: 'Say what you do and where',
              criteria: ['Uses an article before the profession', 'Names the workplace or field'],
            }),
            reviewChallenge({ count: 6 }),
          ],
        }),
        lesson({
          slug: 'en-a1-u2-l2',
          title: 'Shifts and Hours',
          objective: 'Talk about working hours.',
          canDo: 'I can describe my working hours.',
          cefr: 'A1',
          minutes: 8,
          vocabulary: ['shift', 'schedule'],
          activities: [
            buildSentence({
              target: 'My shift starts at seven in the morning',
              tokens: ['morning', 'My', 'at', 'shift', 'the', 'starts', 'seven', 'in'],
              instruction: 'Say your shift starts at seven in the morning.',
              why: 'English puts the time after the verb, and "in the morning" at the end.',
            }),
            fillBlank({
              template: 'I work {{blank}} Monday {{blank}} Friday.',
              answers: ['from', 'to'],
              wordBank: ['from', 'to', 'at', 'in'],
              why: '"From… to…" gives a range of days.',
            }),
            mcq({
              question: 'Which is correct?',
              options: ['I finish at 5pm.', 'I finish in 5pm.', 'I finish on 5pm.'],
              answer: 'I finish at 5pm.',
              why: '"At" for clock times, "on" for days, "in" for months and years.',
            }),
            speak({ target: 'My shift starts at seven and finishes at three.' }),
            reviewChallenge({ count: 6 }),
          ],
        }),
        lesson({
          slug: 'en-a1-u2-l3',
          title: 'Unit 2 Review',
          objective: 'Consolidate work language.',
          canDo: 'I can talk about my job and hours.',
          cefr: 'A1',
          minutes: 9,
          isReview: true,
          activities: [
            timedChallenge({
              instruction: 'Translate the idea into English.',
              items: [
                ['profession + article', 'I am a nurse'],
                ['night work', 'I work nights'],
                ['range of days', 'from Monday to Friday'],
                ['clock time', 'at seven'],
              ],
              seconds: 60,
            }),
            write({
              task: 'Describe your working week in four sentences: what you do, when you start and finish, and one thing you like.',
              goal: 'Describe a work schedule in writing',
              criteria: ['Correct present simple', 'Correct time prepositions', 'Article before the profession'],
              minWords: 25,
            }),
            realWorldTask({
              situation: 'A new colleague asks what your hours are and whether you ever work weekends.',
              goals: ['State your hours', 'Answer the weekend question', 'Ask about theirs'],
            }),
          ],
        }),
        lesson({
          slug: 'en-a1-u2-l4',
          title: 'A1 Checkpoint',
          objective: 'Assess the level across the six skills.',
          canDo: 'I can introduce myself, talk about my job and handle everyday small talk.',
          cefr: 'A1',
          minutes: 16,
          isCheckpoint: true,
          activities: [
            listen({
              audio: 'en/a1/u2/workplace',
              instruction: 'Listening at normal speed.',
              question: 'What is the speaker’s job?',
              options: ['A nurse', 'A teacher', 'A driver'],
              answer: 'A nurse',
              transcript: '— What do you do? — I’m a nurse. I work nights at the hospital. — That’s a hard schedule.',
              speed: 'normal',
              why: '"I\u2019m a nurse" — with the article, as English requires.',
            }),
            storyCompletion({
              story: 'Reading: My name {{blank}} Elena. I {{blank}} from Ukraine and I {{blank}} at a clinic.',
              answers: ['is', 'am', 'work'],
              wordBank: ['is', 'am', 'work', 'are', 'works'],
              why: '"To be" for identity and origin, present simple for the job.',
            }),
            correctGrammar({
              incorrect: 'He work in a restaurant and he have 30 years.',
              correct: 'He works in a restaurant and he is 30 years old.',
              why: 'Third person -s, and English expresses age with "be", not "have".',
              topic: 'en-present-simple',
            }),
            timedChallenge({
              instruction: 'Vocabulary and grammar.',
              items: [
                ['profession with article', 'I am a nurse'],
                ['origin', 'I am from'],
                ['work hours', 'I work nights'],
                ['polite request', 'could you'],
              ],
              seconds: 90,
            }),
            speakResponse({
              situation: 'Speaking: a colleague asks about you on your first day.',
              question: 'So tell me about yourself — where are you from and what did you do before?',
              goal: 'Give a full personal and professional introduction',
              criteria: ['Name and origin', 'Current or previous job', 'Asks a question back'],
            }),
            write({
              task: 'Writing: write a short message introducing yourself to a new team, including your role and your hours.',
              goal: 'Produce a written introduction',
              criteria: ['Correct "to be"', 'Article before the profession', 'Correct time prepositions'],
              minWords: 40,
            }),
            realWorldTask({
              situation: 'You start a new job and need to introduce yourself to three colleagues.',
              goals: ['Greet each person', 'Say your name and role', 'Ask one question', 'Respond to their answer'],
            }),
          ],
        }),
      ],
    }),
  ],
});

const EN_A2 = course({
  slug: 'en-a2-real-life',
  title: 'English A2: Real Life',
  description:
    'Make appointments, deal with a landlord, describe symptoms, and ask for what you need at work — the situations that decide how a new country feels.',
  cefr: 'A2',
  units: [
    unit({
      slug: 'en-a2-u1',
      title: 'Appointments and Health',
      objective: 'Book an appointment and describe a problem.',
      theme: 'health',
      cefr: 'A2',
      realWorldTask: 'Call a clinic, book an appointment and confirm what to bring.',
      lessons: [
        lesson({
          slug: 'en-a2-u1-l1',
          title: 'Making an Appointment',
          objective: 'Book a time and handle an alternative.',
          canDo: 'I can book an appointment by phone.',
          cefr: 'A2',
          minutes: 9,
          vocabulary: ['appointment', 'insurance'],
          grammar: ['en-modals-requests'],
          culture: ['en-appointments'],
          activities: [
            listen({
              audio: 'en/a1/u3/appointment',
              instruction: 'Listen to the phone call.',
              question: 'What does the caller ask for instead?',
              options: ['The afternoon', 'Another day', 'A different clinic'],
              answer: 'The afternoon',
              transcript: '— I’d like to make an appointment. — Sure. Is Tuesday at ten all right? — Could we do the afternoon instead?',
              speed: 'normal',
              why: '"Could we do the afternoon instead?" is a polite counter-offer.',
            }),
            mcq({
              question: 'Which request is politest with a stranger?',
              options: ['Could we do Thursday instead?', 'We do Thursday.', 'I want Thursday.'],
              answer: 'Could we do Thursday instead?',
              why: '"Could" softens the request; the bare statement sounds like an instruction.',
              tags: ['grammar:en-modals-requests'],
            }),
            correctGrammar({
              incorrect: 'Give me an appointment Thursday.',
              correct: 'Could I make an appointment for Thursday, please?',
              why: 'The bare imperative reads as an order. A modal plus "please" is the expected register on the phone.',
              topic: 'en-modals-requests',
            }),
            converse({
              scenario: 'en-doctor-appointment',
              goals: ['Say why you are calling', 'Describe the symptom', 'Agree a date and time', 'Confirm what to bring'],
              minTurns: 6,
              cefr: 'A2',
            }),
            reviewChallenge({ count: 7 }),
          ],
        }),
        lesson({
          slug: 'en-a2-u1-l2',
          title: 'Describing Symptoms',
          objective: 'Say what is wrong and how long it has lasted.',
          canDo: 'I can describe a symptom and its duration.',
          cefr: 'A2',
          minutes: 9,
          vocabulary: ['symptom', 'prescription'],
          grammar: ['en-past-simple'],
          activities: [
            fillBlank({
              template: "I've had a headache {{blank}} Monday.",
              answers: ['since'],
              wordBank: ['since', 'for', 'from'],
              why: '"Since" plus a point in time, "for" plus a length of time.',
            }),
            correctGrammar({
              incorrect: 'I have headache since three days.',
              correct: "I've had a headache for three days.",
              why: 'Three errors: the article, the present perfect for something still true, and "for" with a length of time.',
              topic: 'en-past-simple',
            }),
            speakResponse({
              situation: 'A doctor asks what is wrong.',
              question: 'What seems to be the problem?',
              goal: 'Describe the symptom and how long it has lasted',
              criteria: ['Names the symptom', 'Gives a duration with for or since', 'Answers a follow-up'],
              cefr: 'A2',
            }),
            reviewChallenge({ count: 7 }),
          ],
        }),
      ],
    }),
    unit({
      slug: 'en-a2-u2',
      title: 'Housing and Work Requests',
      objective: 'Report a problem and ask for what you need.',
      theme: 'home',
      cefr: 'A2',
      realWorldTask: 'Report a repair to a landlord and agree a time when you are actually home.',
      lessons: [
        lesson({
          slug: 'en-a2-u2-l1',
          title: 'Reporting a Repair',
          objective: 'Explain a problem and push for a date.',
          canDo: 'I can report a problem in my home and agree a repair time.',
          cefr: 'A2',
          minutes: 10,
          vocabulary: ['landlord', 'rent', 'lease', 'deposit', 'bill'],
          activities: [
            listen({
              audio: 'en/a2/u1/repair',
              instruction: 'Listen to the call with the landlord.',
              question: 'Why does the tenant push back?',
              options: ['They are at work then', 'They do not want the repair', 'The date is too soon'],
              answer: 'They are at work then',
              transcript: '— The heating hasn’t worked since Friday. — I’ll send someone Thursday morning. — I’m at work then. Could it be after five?',
              speed: 'normal',
              why: 'Giving the reason before the counter-offer makes the request easy to accept.',
            }),
            buildSentence({
              target: 'The heating has not worked since Friday',
              tokens: ['Friday', 'The', 'not', 'has', 'worked', 'heating', 'since'],
              instruction: 'Explain that the heating has not worked since Friday.',
              why: 'A problem that started in the past and is still true takes the present perfect.',
              cefr: 'A2',
            }),
            converse({
              scenario: 'en-landlord-repair',
              goals: ['Explain the problem', 'Say how long it has been happening', 'Ask when it will be fixed', 'Agree a time'],
              minTurns: 6,
              cefr: 'A2',
            }),
            write({
              task: 'Write a short message to a landlord about a broken appliance, including when it broke and when you are available.',
              goal: 'Report a problem in writing and propose a time',
              criteria: ['States the problem', 'Gives a duration', 'Proposes a specific time'],
              minWords: 40,
              cefr: 'A2',
            }),
          ],
        }),
        lesson({
          slug: 'en-a2-u2-l2',
          title: 'Asking at Work',
          objective: 'Make a workplace request that gets a yes.',
          canDo: 'I can ask my manager for something and give a reason.',
          cefr: 'A2',
          minutes: 10,
          vocabulary: ['shift', 'overtime', 'paycheck', 'deadline'],
          culture: ['en-workplace-directness'],
          activities: [
            mcq({
              question: 'Which opening is most likely to get a yes from a manager?',
              options: [
                'I wanted to check whether I could swap Saturday — Maria has already agreed to cover it.',
                'I am not working Saturday.',
                'Can I have Saturday off? I do not know who will cover.',
              ],
              answer: 'I wanted to check whether I could swap Saturday — Maria has already agreed to cover it.',
              why: 'Polite framing plus a solved problem. US workplaces reward bringing the answer with the request.',
              tags: ['culture:workplace-directness'],
            }),
            converse({
              scenario: 'en-shift-change',
              goals: ['Make a polite request', 'Give a reason', 'Propose a solution', 'Confirm the outcome'],
              minTurns: 5,
              cefr: 'A2',
            }),
            speakResponse({
              situation: 'You need to leave an hour early on Friday for an appointment.',
              question: 'Sure, what did you need?',
              goal: 'Make the request, give a reason and offer a solution',
              criteria: ['Uses a polite modal', 'Gives a reason', 'Offers to make the time up or arrange cover'],
              cefr: 'A2',
            }),
          ],
        }),
        lesson({
          slug: 'en-a2-u2-l3',
          title: 'A2 Checkpoint',
          objective: 'Assess the level across the six skills.',
          canDo: 'I can handle appointments, housing and workplace requests in English.',
          cefr: 'A2',
          minutes: 18,
          isCheckpoint: true,
          activities: [
            listen({
              audio: 'en/a2/u2/shift',
              instruction: 'Listening at natural speed.',
              question: 'Has the colleague already agreed?',
              options: ['Yes', 'No', 'It is not mentioned'],
              answer: 'Yes',
              transcript: '— Could I swap Saturday with Maria? — Does she agree? — Yes, she already said she can cover it.',
              speed: 'natural',
              why: '"She already said she can cover it."',
            }),
            storyCompletion({
              story:
                'Reading: I {{blank}} to the clinic on Tuesday because I {{blank}} had a cough for two weeks. The doctor {{blank}} me a prescription.',
              answers: ['went', 'had', 'gave'],
              wordBank: ['went', 'had', 'gave', 'go', 'give'],
              why: 'Past simple for the finished events.',
              cefr: 'A2',
            }),
            correctGrammar({
              incorrect: "I didn't went to work because I have fever since Monday.",
              correct: "I didn't go to work because I've had a fever since Monday.",
              why: 'After "did" the verb returns to its base form, and a condition still true takes the present perfect.',
              topic: 'en-past-simple',
            }),
            speakResponse({
              situation: 'Speaking: you need to explain an absence to your manager.',
              question: 'I noticed you were out yesterday — everything okay?',
              goal: 'Explain the absence and what you did about it',
              criteria: ['Past tense used correctly', 'Gives a reason', 'Says what happens next'],
              cefr: 'A2',
            }),
            write({
              task: 'Writing: write an email to a landlord about a repair, including when the problem started and two times you are available.',
              goal: 'Write a clear message with a request',
              criteria: ['States the problem and its duration', 'Offers two specific times', 'Uses a polite closing'],
              minWords: 60,
              cefr: 'A2',
            }),
            realWorldTask({
              situation: 'You need to book a medical appointment, but the first two times offered clash with your shift.',
              goals: ['Explain why you are calling', 'Decline two times politely', 'Agree a workable time', 'Confirm the details'],
              cefr: 'A2',
            }),
          ],
        }),
      ],
    }),
  ],
});

export const EN_CURRICULUM: AuthoredCurriculum = {
  languageCode: 'en',
  courses: [EN_PRE_A1, EN_A1, EN_A2],
  vocabulary: EN_VOCABULARY,
  grammar: EN_GRAMMAR,
  culture: EN_CULTURE,
  scenarios: EN_SCENARIOS,
  media: EN_MEDIA,
};
